.github/ISSUE_TEMPLATE.md
* Notes
* etc.
Per the 18F Content Guide, I replaced _etc._ with _And so on_. (This also improves consistency between sections.)
=> Minor copy edit

CONTRIBUTING.md
* Notes
* etc.
Just changed a few words -- this looks good to go!
=> A few minor copy edits!

LICENSE.md
* Notes
* etc.
In keeping with the 18F content guide, I changed the capitalized "Government" to its lowercase form.
=> Lowercased "government"

circle.yml
... now that we can push the repo live! Yay!
REMEMBER, after merging this, `staging` also needs to be merged to `master`.
=> Remove test deploy config, replace with live version

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Updates issue and pull request templates to reflect the types of issues/PRs that will happen in this repo and provides a link to the web-design-standards repo for Standards changes.
=> [Issue and PR templates]: Update issue and pull request template

README.md
I found myself running the commands in the wrong directory. Writing out explicitly what directory to run the commands on for each step should make this clearer.
Let's over communicate ❤️
=> [README]: Write out the directory for each step in installation instructions

_includes/navbar.html
Updates the markup corresponding to https://github.com/18F/web-design-standards/pull/1497.
=> [Media block]: Update media block markup in site banner

_includes/sidenav/about-our-work.html, css/styleguide.scss, pages/about-our-work/research.md
Adds Research page to About our work.
/cc @kategarklavs @jameshupp
=> [About our work]: Add Research page

circle.yml, config/cf/manifest-release.yml, config/cf/manifest-staging.yml, config/cf/manifest-user-testing.yml, manifest-staging.yml
This pull request does a tiny bit of clean up in regards to our deployment schema for the WDS staging and production instances. This is the start of the work we'll be doing to incorporate a more streamlined with our new multiple repository workflow.
=> Clean up Circle CI config and files

_includes/repo-split.html, _layouts/styleguide.html, css/styleguide.scss
=> Remove repo split disclaimer banner from website.

_config.yml, css/_override_variables.scss, css/styleguide.scss, package.json
This pull request is a catch all for updates that need to be made to be in sync with the `v0.13.2` release of the Standards. 
Refs #69 for a full checklist of items that need updating for this release.
=> Updates for v0.13.2 release

pages/design-principles.md
Updated the design principles with the latest version from the fall 2016 research and team workshops.
=> Update design principles with new layout and design.

_config.yml, css/_override_variables.scss, package.json
This pull request is a catch all for updates that need to be made to be in sync with the `v0.13.3` release of the Standards.
=> Updates for v0.13.3 release

_includes/analytics.html
Per request from @jehlers, we are removing the Ethnio code snippet on the website.
=> Remove Ethnio code from website

pages/getting-started/developers.md
Changes, mainly documentation, to make it easier for developers to customize the standards.
=> Change deprecated defaults reference to variables

pages/about-our-work/research-strategy.md
=> Clarified who "the team" is

pages/about-our-work/research-strategy.md
=> Copy edits

_includes/sidenav/about-our-work.html, pages/about-our-work/research-strategy.md
Include the research strategy into the site that includes some additional services we can provide to partner agencies.
=> Update research strategy

_config.yml, package.json
Updating files in prep for the [0.14.0 release](https://github.com/18F/web-design-standards/issues/1615).
=> Prep for release 0.14.0

_includes/sidenav/about-our-work.html, pages/about-our-work/research-strategy.md, pages/about-our-work/research.md
Fixes #92 
@bradnunnally does this look okay to you? I changed the verbiage in the sidenav to match "Current research" in place of "Research".
=> Fix issue on about us side navigation

_includes/sidenav/about-our-work.html, css/styleguide.scss, pages/about-our-work/releases.md
This pull requests completes the work for adding the Github release notes to the website.
Shout out to @femmebot @ericronne and @hursey013 for your feedback to help refine the layout 🎉
=> Adding link to "Release notes" section

_data/nav.yml, pages/whats-new/overview.md, pages/whats-new/releases.md, pages/whats-new/research-strategy.md
This pull request adds the What's New page and it's subnav to the repo.
=> Adding What's New page and nav

_data/nav.yml, pages/getting-started/overview.md
=> Getting started copy edits

css/styleguide.scss, pages/getting-started/video-tutorials.md
=> Update video page

_includes/footer.html
Updated with new text (per @yowill). See screenshot below for how it looks on Desktop view.
=> Update content in the footer for 1.0

pages/whats-new/research.md
Moved copy around to avoid the “wall of text” feel the page had.
Ready for review @juliaelman or @shawnbot
=> Cleaned up the leading copy of Research

_includes/nav/README.md, pages/whats-new/overview.md, pages/whats-new/research.md
Completes the request outlined in #170
=> Remove stray primes with actual double quotes.

css/styleguide.scss
https://standards.usa.gov/design-principles/
=> fix design principles footer margin too large. 

_components/page-templates/template-docs.html, _components/page-templates/template-landing.html, _includes/navbar.html
Refs https://github.com/18F/web-design-standards/issues/1772
=> Remove accesskey value from templates and navbar.

_config.yml, _includes/post.html, _posts/2017-03-21-nasa-journey-with-us-web-design-standards.md
=> Add NASA case study update

_posts/2017-03-31-u-s-customs-and-border-patrol-case-study.md
@yowill and @shawnbot - Here is the news update for the CBP case study pull request. It's ready for review.
=> Added the CBP Blog post

package.json
@shawnbot fixed something to allow my branch to preview on Federalist.
=> Preview fix

pages/home.md
Added the code for the homepage that allows us to track if people click the buttons for training or customization. 
The GA code is good to go.
=> Add services analytics

pages/design-principles.html
=> Fixing typo in design principles

pages/performance/why.md
Includes most recents addressed from google doc.
=> Publish why to track performance guide.

_posts/2017-04-26-fractal-federalist.md
Add a blurb to the Federalist post about being open for business, fixed a link.
=> add plug for Federalist

pages/performance/what.md
Taken from https://github.com/18F/web-design-standards/issues/1852
which is a good explanation.
Publish the "What is performance" page. on performance section of site
=> Publish what is performance

pages/home.md
Fixes 18F/web-design-standards#1914
=> updating homepage copy

pages/performance/how.md
Because it could change what metrics you would select.
* Notes
* etc.
=> Add HTTP/2 advice on selecting metrics

_data/nav.yml
=> Add back the performance navigation

pages/performance/why.md
=> Update why section lead

pages/performance/research.md
Adds a page describing our web performance research process and findings.
=> Add research document

_data/implementations.yml
fixes #303 
I skipped the 18F Drupal theme because it's no longer being maintained and the one by Brock Fanning is more up to date.
=> adding extra implementations

pages/performance/why.md
=> fixed small typos

pages/getting-started/developers.md
This fixes 18F/web-design-standards#1886.
=> Make email a mailto: link

_data/implementations.yml
Fixes 18F/web-design-standards#2001.
=> List jekyll theme

_components/page-templates/template-docs.html, _components/page-templates/template-landing.html, _includes/code/components/header-basic-mega.html, _includes/code/components/header-basic.html, _includes/code/components/header-extended-mega.html, _includes/code/components/header-extended.html, _includes/code/components/template-docs.html, _includes/code/components/template-landing.html
=> Fix remaining aria-label="Home" occurrences

_posts/2017-07-10-vets-case-study.md
fixes 18f/web-design-standards#1986
=> adding vets.gov content

pages/getting-started/developers.md
Adds documentation to developer guide on how to extend and use the JavaScript. 
I removed outdated information about jQuery as well, I mistakenly committed it to the develop branch here: https://github.com/18F/web-design-standards-docs/commit/bafe664640ae2bb024c576f3b666bff4b4ed11de
Fixes https://github.com/18F/web-design-standards/issues/1975
- I found through investigation that our components do not yet emit events when actions happen, which would greatly improve the API to extend them. This is something that should be looked into.
- The USWDS JS code is not exposed in a global scope at all, meaning it's very hard to extend from it if developers are not using an npm/build CommonJS module workflow. This is another thing to look into and would be an easy fix.
- Our JS code has very little …
=> JS customization documentation

_includes/code/components/address-form.html
Fixes https://github.com/18F/web-design-standards/issues/818
=> Adds US Military address to address form

css/styleguide.scss
Vertically align the content pieces which are side by side for visual
reasons. It's only applied to the first three because when the headers
to the left get smaller, it's not really required.
Fixes https://github.com/18F/web-design-standards/issues/634
=> Type css details line up

_posts/2017-07-24-code-gov-case-study.md
fixes 18F/web-design-standards#2042
=> adding code.gov case study

_posts/2017-07-25-oes-case-study.md
fixes 18F/web-design-standards#2041
=> adding oes case study

_posts/2017-07-24-code-gov-case-study.md, _posts/2017-07-25-oes-case-study.md
Adds the OES and Code.gov case studies
=> Content updates

_posts/2017-08-14-fec-case-study.md
Fixes https://github.com/18F/web-design-standards/issues/2103#event-1204803418.
=> Add FEC case study.

_data/implementations.yml
Fixes #380.
😎 [Federalist preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/toolness-patch-1/getting-started/implementations/#npm-and-gulp)
=> Add 18F/uswds-simple-sass to  implementations page

_includes/banner.html
=> Update gov banner

README.md
Adds incremental regeneration command to the README's utility command list.
=> Add incremental regeneration command to README

pages/getting-started/developers.md
Fixes 18F/web-design-standards#996
=> clarity around usa-* css class prefix

_components/grids.md, _includes/code/components/grids.html, css/styleguide.scss
There are no code samples on the grid page anymore, this adds it back in.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/fix-grid-code-sample/components/grids/)
Fixes #356.
=> [Grid]: Add code samples to grids page

_layouts/landing.html, pages/home.md
Fixes #391
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/add-home-links)
Wanted to check we liked the text of the links... "See getting started," "See UI components," etc...
=> Add links to 4 callouts on homepage

_includes/footer.html
Fixes #432.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/update-footer)
=> Remove 18F logo from footer and update text refer to OPP

pages/home.md
- Adds `+training` and `+customization` to email links for ease of filtering. See: https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html
- Adds cc to 18F business development
cc @d-kenny
=> CC 18F bizdev to inquiry email link

_includes/nav/page-item.html, css/styleguide.scss
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/update-header-nav)
Fixes #296.
=> Use extended header navigation styles for docs site

_includes/footer.html
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards/update-footer-text)
=> Fix OPP name and add link to TTS in footer

_layouts/landing.html
Minor validation issue found running https://validator.w3.org/nu/?doc=https%3A%2F%2Fstandards.usa.gov%2F
=> Close span in the landing hero callout

package-lock.json, package.json
Upgrades the USWDS package to 1.4.4
=> Upgrade USWDS version to 1.4.4

_components/sidenav.md
Added a line to the sidenav guidance to reference the `$sidenav-current-border-width` variable that now controls the highlight width.
=> Add sidenav highlight var to sidenav guidance

_posts/2017-12-20-2017-where-weve-been-where-were-going.md
😎 https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/dw-vision-post/whats-new/updates/2017/12/20/2017-where-weve-been-where-were-going/
=> Add 2017 review and vision post to What's New

css/styleguide.scss
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/fix-home-diamond)
Fixes #439.
=> Fix decorative diamond on homepage in Chrome

_includes/nav/list.html, _includes/nav/page-item.html
Fix for https://github.com/18F/web-design-standards-docs/issues/430
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/bh-sidenav-overview)
=> Use link text defined in nav.yml file for sidenav

_includes/accessibility.html
=> Fix misspelled "aria-labelledby" in forms documentation

_posts/2018-01-17-changing-our-name.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/add-name-post/whats-new/updates/2018/01/17/changing-our-name/)
=> Add name change post to News

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, _config.yml, _posts/README.md, package-lock.json, package.json, pages/getting-started/implementations.md
Changes references to the name of this repo to uswds-site
=> update uswds-docs to uswds-site

_data/milestones.yml
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-naming-done/whats-new/product-roadmap/)
=> Change naming task to done in Product roadmap

package-lock.json, package.json
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-v1.4.5)
=> Update to use USWDS v1.4.5

pages/whats-new/overview.md
All hail the US Web Design System!
=> Fixes broken link to 18F blog

package-lock.json, package.json
=> update to use uswds-1.4.6

_posts/2018-02-20-wordpress-theme-benjamin.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-benjamin-article/whats-new/updates/2018/02/20/wordpress-theme-benjamin/)
Related: https://github.com/uswds/uswds/issues/2303
cc @AndreaSigz
=> Add "WordPress Theme ‘Benjamin’" article

_components/form-controls/06-validation.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-validation-security-note/components/form-controls/#validation)
Fixes #382.
=> Add disclaimer about validation component security

_components/footers.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-note-footer-icons/components/footers/)
Fixes #393.
=> Add resource for additional social media icons

pages/design-principles.html
Simple grammar fix. Update "is" to "are" on line 31.
Keep up the good work :)
=> [uswds-site]: Change "is" to "are" in design principles

_data/implementations.yml
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/fix-rails-gem-info/getting-started/implementations/#rails-gem)
Fixes #506.
=> Update the rails gem info to not maintained

package-lock.json, package.json
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/use-uswds-1.6.0)
=> Use uswds-1.6.0

RELEASE.md, _config.yml, pages/getting-started/showcase-all.md
Dependent on https://github.com/uswds/uswds/pull/2385 aka merge that first.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-showcase-path)
=> Update showcase path

_posts/2018-02-22-nsf-seed-fund.md, _posts/2018-03-22-dds-case-study.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-dds-interview/whats-new/updates/2018/03/22/dds-case-study/)
Closes https://github.com/uswds/uswds/issues/2076.
cc @AndreaSigz for visibility
=> Add DDS case study

.circleci/config.yml, package-lock.json
This caches project dependencies on CircleCI to speed up build times.
=> Add caching to CircleCI

package-lock.json, package.json
https://github.com/uswds/uswds/releases/tag/v1.6.1
=> Use USWDS v1.6.1

package-lock.json, package.json
https://github.com/uswds/uswds/releases/tag/v1.6.3
=> Use USWDS v1.6.3

config/gulp/images.js
Fix syntax error in images build script
=> npm watch fix

_components/utilities/box-shadow.md, _components/utilities/float.md, _components/utilities/list-reset.md
- [Box shadow](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-new-utes/utilities/box-shadow/)
- [Float](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-new-utes/utilities/float/)
- [List reset](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-new-utes/utilities/list-reset/)
=> Add box shadow, float, and list reset to utility docs

.circleci/config.yml, package-lock.json, package.json
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/use-1.6.4)
=> Use USWDS 1.6.4

package-lock.json, package.json
Resolves the issue outlined here: https://github.com/uswds/uswds/issues/2537
Fixes #550.
Axe is not working locally.
/cc @toolness
=> Update chrome remote interface

package-lock.json, package.json
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/use-1.6.6)
=> Use USWDS v1.6.6

_posts/2017-03-01-post-1-0-research-strategy-workshop.md, _posts/2017-03-27-u-s-web-design-standards-exposure-analytics.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/maya-patch-1/whats-new/updates/2017/03/01/post-1-0-research-strategy-workshop/)
=> Fix headings of (older) blog post

_includes/banner.html, _includes/navbar.html, package-lock.json
This brings in the changes we made to the USWDS header so that the HTML validates.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/fix-header-validation)
Fixes #586.
=> Fix header validation issue

_components/grids.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/fix-grid-div-docs/components/grids/)
Fixes https://github.com/uswds/uswds/issues/1236
=> Fix grid div recommendation

_components/icons.md, _data/nav.yml
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/add-icons-page/components/icons/)
Fixes https://github.com/uswds/uswds/issues/762.
=> Add a minimal Icons page

_includes/footer.html
quick PR to change the link from one that redirects
=> update federalist link

package-lock.json
Fixes 4 out of 5 Snyk issues with `npm audit fix`
=> Fix Snyk issues

_components/utilities/border.md, _components/utilities/margin-and-padding.md, _components/utilities/paragraph-styles.md, _data/uswds_tokens.yml, _data/utilities.yml, pages/style/overview.md
- Also add leading zeroes
- - -
Fixes #591
=> Use units() instead of spacing() for spacing unit fns

css/_project-custom.scss
This updates the color vars to 2.0 tokens in the proper format. 
Requires https://github.com/uswds/uswds/pull/2685
- - -
OK https://github.com/uswds/uswds/pull/2685 is merged — this should work now
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-update-vars/)
=> Update color vars to 2.0 tokens

_components/buttons.md
Fixes #631 - eliminates a word that I assume was a typo to improve documentation.
=> Remove typo on button documentation

utils/check-contrast.js
To run:
**NOTE** you can quiet the output a bit by removing the debug flag (--d) from the following command
* `npm run check-contrast -- --ca --d`
=> adds check for contrast between all families

_data/uswds_tokens.yml, pages/style/color/theme-palette.md
Documentation changes that go with the changes in https://github.com/uswds/uswds/pull/2714.
=> Update warning variable name

_components/typography/01-typefaces.md, css/_uswds-theme-typography.scss
This will make the site look normal once https://github.com/uswds/uswds/pull/2731 goes through
=> Add new typography settings

_data/uswds_tokens.yml, css/_project-custom.scss, css/_uswds-theme-color.scss
Use the accurate theme colors from the USWDS repo and make sure docs are accurate.
=> Fix theme colors docs

_includes/code/components/buttons.html, css/_project-custom.scss, package-lock.json
Update buttons page to show all buttons available.
Updates the `project_custom.scss` file bc there were a bunch of errors with older vars. I did this in a bit of a hurry so will likely have to go back and check that I used the correct sizes.
Related to https://github.com/uswds/uswds/issues/2171.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-buttons-page/components/buttons/)
=> Update buttons page

.circleci/config.yml, package.json
Updates the cache key again. My hunch is that since the previous update job was cancelled a new cache was never saved. Basing new branches off of this seems to work properly. 🤞 
I added an env variable to circle so we can update the cache version in the future without having to push a code change
=> Test updating cache key again

_components/utilities/border.md, _components/utilities/clearfix.md, _components/utilities/color.md, _components/utilities/display.md, _components/utilities/flex.md, _components/utilities/float.md, _components/utilities/font-size-and-family.md, _components/utilities/height-and-width.md, _components/utilities/list-reset.md, _components/utilities/margin-and-padding.md, _components/utilities/outline.md, _components/utilities/paragraph-styles.md, _components/utilities/shadow.md, _components/utilities/template.md, _components/utilities/text-styles.md, pages/style/typescale.md
Removes all `#0` links and replaces them with real docs links
=> Replace all dummy links with real links

package-lock.json, package.json
=> Update to 1.6.9

css/_uswds-theme-custom-styles.scss
The latest changes affected the display of buttons. This adds more specificity to custom buttons.
=> Fix button specificity problems

package-lock.json, pages/home.md
This fixes a broken link in https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf
=> Forward `getting-started` to site home

_data/tokens/color.yml, _includes/download-buttons.html, _includes/tokens/get-system-colors.html, package-lock.json, package.json, pages/design-tokens/color/overview.md, pages/design-tokens/color/system-tokens.md, pages/documentation/getting-started/download.html, utils/check-contrast.js
[Preview TK]()
Adds the blue-cool color family to the docs.
**Do not merge until the beta 5 release.**
=> [DO NOT MERGE] Add blue-cool docs

.snyk, package-lock.json, package.json
This addresses the security vulnerabilities identified by `npm audit` and `snyk test`.
🐾 [Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/sc_package-updates/)
=> Package security updates

_components/utilities/display.md, pages/design-tokens/z-index.md
[Token preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-fix-z-index/design-tokens/z-index/)
[Utilities preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-fix-z-index/utilities/display/#z-index)
Featuring the return of z-index...
=> Use proper z-index for z-index example sections

_includes/code/components/alerts.html, css/_uswds-theme-custom-styles.scss, package-lock.json
Update hover styles of govt banner button, code button, and footer links.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-hover-styles/components/tag/)
---
TODO on the `uswds/uswds` repo: 
Update links on dark background to `color('base-light');` instead of `color('base-lighter');`
=> Update hover styles of various buttons

_includes/download-buttons.html, pages/documentation/getting-started/download.html
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-update-beta-refs/)
=> Update references to beta 7

package.json
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/use-1.6.10/)
=> Use uswds 1.6.10

pages/documentation/getting-started/developers.md
Preview: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-docs-sidenav/documentation/developers/#long-term-support-of-v1x
Related to https://github.com/uswds/uswds/issues/1916.
=> Add long-term support sidenav item to docs

_data/milestones.yml, css/_uswds-theme-custom-styles.scss, pages/whats-new/product-roadmap.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-roadmap/about/product-roadmap/)
Can anything else be marked "done"?
=> Update product roadmap

_components/headers/headers.html, _components/page-templates/page-templates.html, _config.yml
- [Page templates preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/use-fractal-links/page-templates/)
- [Headers preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/use-fractal-links/components/header/)
=> Use fractal site for link preview for headers and page templates

pages/documentation/guidance/accessibility.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-a11y-page/documentation/accessibility/)
=> Add a11y for teams content

_components/form-controls/form-controls.md
Implements fixes in #768 but on the v2 branch.
cc @blacktm
=> Fix form sidebar links

_config.yml
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/mb-v1-update-readme-ref/documentation/developers/)
Fixes #770.
=> Add release-1.6.10 ref to install-readme on v1 site

.circleci/config.yml, _config.yml, _includes/download-buttons.html, _layouts/landing.html, package-lock.json, package.json, pages/documentation/getting-started/download.html
- Update to USWDS 2.0.2
- Update references to 2.0.2
Note: we will return to pointing to the `develop` branch once this is complete.
=> Use 2.0.2 and update references

_includes/banner-news.html
Update the v2 banner link to `designsystem.digital.gov` from `v2.designsystem.digital.gov`
=> v1: Update banner URL

_components/typography/typography.md, pages/about/research.md, pages/documentation/getting-started/designers.md, pages/documentation/getting-started/migration.md
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/fix-bad-link/)
- Fixes some bad links (thanks @dotmike)
- Replaces references to `USWDS 2.0` with `USWDS 2`
- - -
Supercedes #782
=> Fix bad links and references

.browserslistrc, _config.yml, config/gulp/sass.js, package-lock.json
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/fix-header-demo/components/header/) :sparkles:
- This fixes the outside demo url we use for certain components to the most recent USWDS version (2.0.3)
- This also updates our broswerslist config to use the most current best practices for specifying browsers (config file, no specified versions)
- - -
Fixes https://github.com/uswds/uswds/issues/3065
=> Fix header demo and update browserslist

config/gulp/doc-util.js, config/gulp/javascript.js, package-lock.json, package.json
This resolves a critical dependency on `lodash.template`
=> Remove gulp-util dep and replace with maintained packages

_config.yml, _data/variables.yml, _includes/download-buttons.html, _layouts/landing.html, css/settings/_uswds-theme-components.scss, css/uswds-components.scss, package-lock.json, package.json, pages/documentation/getting-started/download.html
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/dw-update-to-2.2.0/) ✨
=> Update to 2.2.0

_data/implementations.yml
Point to the WordPress distributions of the Benjamin theme and the Franklin plugin rather than the Github repos.
=> Update Implementations page in documentation

css/_uswds-theme-custom-styles.scss
This fixes an issue that prevents proper printing in Firefox. 
Fixes #820
=> Remove inline-block declaration

_config.yml, _includes/download-buttons.html, _layouts/landing.html, package-lock.json, package.json, pages/documentation/getting-started/download.html
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/use-2.4.0/)
=> Update site to 2.4.0

_includes/footer.html
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/dw-fas-footer/)
=> Add FAS to footer, remove TTS Solutions

_includes/footer.html
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/dw-fas-footer/)
=> Improve footer language

config/gulp/sass.js
=> USWDS-Site: Disable forceMediaMerge in CSSO.

_config.yml, _includes/download-buttons.html, _layouts/landing.html, package-lock.json, package.json, pages/documentation/getting-started/download.html
[Preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/v2.5.1/)
=> Use USWDS 2.5.1

README.md
@jaredcunha Do these changes square with your install experience? I double-checked on my side as well.
=> Update and improve the local linking instructions

_components/form-controls/05-date-input.md, package-lock.json, package.json
Numeric inputs still contain many usability and accessibility issues, and should be avoided in favor of `text` inputs with a `pattern` and `inputmode` attribute.
Related Issue: https://github.com/uswds/uswds/issues/3350
Pull request on USWDS: https://github.com/uswds/uswds/pull/3371
Research and rationale: https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers
=> USWDS-3350: Update guidance date inputs

pages/documentation/getting-started/designers.md
This adds the new Sketch files from `uswds-for-designers`
https://github.com/uswds/uswds-for-designers
=> Add updated Sketch assets

pages/about/overview.md
As a USWDS Customer I would like to see the vision statement of the framework. Added vision statement to about overview page.
Content audit indicated vision and mission were missing.
=> [USWDS Site] - Add vision & mission statement.

_posts/2017-03-01-post-1-0-research-strategy-workshop.md, _posts/2017-03-21-nasa-journey-with-us-web-design-standards.md, _posts/2017-03-21-update-design-assets.md, _posts/2017-03-27-u-s-web-design-standards-exposure-analytics.md, _posts/2017-03-31-u-s-customs-and-border-patrol-case-study.md, _posts/2017-04-26-fractal-federalist.md, _posts/2017-06-06-usda-case-study.md, _posts/2017-06-19-usajobs-case-study.md, _posts/2017-07-10-vets-case-study.md, _posts/2017-07-24-code-gov-case-study.md, _posts/2017-07-25-oes-case-study.md, _posts/2017-08-14-fec-case-study.md, _posts/2017-11-08-USAGov-case-study.md, _posts/2017-12-20-2017-where-weve-been-where-were-going.md, _posts/2018-01-17-changing-our-name.md, _posts/2018-02-20-wordpress-theme-benjamin.md, _posts/2018-02-22-nsf-seed-fund.md, _posts/2018-03-22-dds-case-study.md, _posts/2019-04-08-introducing-uswds-2-0.md
Fixes:
https://github.com/uswds/uswds-site/issues/951
Updated category name for blog posts `About USWDS → About`.
=> USWDS-Site-951 - About: Add missing sidenav on blog posts.

pages/whats-new/overview.md
Resolves #945.
[Preview 🔍](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-remove-old-metrics/about/whats-new/)
[Old](https://designsystem.digital.gov/about/whats-new/)
=> USWDS - About: Remove dated analytics from What's New.

_includes/banner-alert.html, _includes/navbar.html, css/styleguide.scss
Resolves #940
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-deprecated-warning/)
~https://user-images.githubusercontent.com/3385219/81342964-c17f2800-9079-11ea-8b88-6eed807057ac.png~
=> USWDS - V1: Add deprecated text banner.

_components/form-controls/08-character-count.md
=> USWDS-SITE - 957 Align character count guidance

config/gulp/doc-util.js
Resolves https://github.com/uswds/uswds-site/issues/954
Previously was showing in notifications as `undefined - undefined`.
=> USWDS-Site - 954: Removes package name and version from doc-util.js.

css/_uswds-theme-custom-styles.scss, pages/whats-new/product-roadmap.md
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-update-roadmap/about/product-roadmap/)
Card → Done
Button group → Done
Autocomplete combobox → Done
Button group → Done
Breadcrumb → In progress
Date picker → In progress
Date range picker → In progress
Tooltip → In progress
Document upload → In progress
Time picker → On deck
Date and time picker → On deck
Anchor → On deck
Simplify and improve design assets → Done
=> Update roadmap with current project status

package.json
=> Update package.json - add name

.snyk, _data/variables.yml
Add the `$test-system-color-tokens` setting and flag it as an internal setting.
=> Add color test setting

_components/form-controls/09-combo-box.md
=> USWDS-SITE Add tables for new properties and procedures

pages/documentation/getting-started/designers.md
Resolves https://github.com/uswds/uswds-site/issues/875
@afeijoo edits welcome, but I wanted to make sure Maya got credit and the slack link was shown. 
Do we need to add a GA event for this outbound link? Do you know what that would look like?
[Preview 👁](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-figma-link/documentation/designers#uswds-for-designers) 
=> USWDS-875: Add Figma link to USWDS for Designers.

_components/form-controls/03-combo-box.md, _components/form-controls/05-date-picker.md, _components/form-controls/06-date-range-picker.md
=> USWDS-SITE-937 Default Value Documentation

_components/banner.md, _includes/code/components/banner-code.html, _includes/code/components/banner.html, package-lock.json, package.json
- Use updated banner versions
- Copyedit throughout
- Add clearer point about unaltered text
- Add content variant for non-DOD .mil sites
- Remove point about consolidating agency information into the banner
=> Update banner guidance

package-lock.json, package.json
=> Use USWDS 2.8.0

_includes/analytics.html
This adds a TTS subagency to our DAP script source to help organize TTS-level reporting.
=> Add TTS subagency to DAP script src

pages/whats-new/product-roadmap.md
This updates our progress on recent components and USWDS Jekyll, as well as makes a couple copyedits to update the roadmap with the most current names for our components.
=> Update roadmap to reflect current progress

.snyk, css/_uswds-theme-custom-styles.scss
Fixes homepage issues outlined in https://github.com/uswds/uswds/issues/3578.
Still need to take care of issue in date picker. Cause outlined in [slack](https://gsa-tts.slack.com/archives/C050HRGN7/p1596825395189200?thread_ts=1596823621.187400&cid=C050HRGN7).
=> USWDS - Homepage: Fix IE11 issues.

_data/implementations.yml
**The implementation’s target language and/or framework:**
Tailwind CSS plugin
**The author’s name (or alias) and contact URL or email address:**
Brian Hurst, https://github.com/hursey013
**The most recent version of USWDS that the project targets**
2.8
**Any useful caveats or other notes**
Does not include USWDS components or page templates
=> Add USWDS Tailwind CSS plugin to implementations page

_data/implementations.yml
[Preview 👁](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-implementations-salesforce/documentation/implementations/)
Resolves #1021
Adds Salesforce Lightning USWDS [implementation](https://github.com/GSA/uswds-sf-lightning-community). Thanks @mvogelgesang!
=> USWDS - Documentation: Add Salesforce Lightning implementation.

.snyk, _includes/analytics.html, _includes/head.html, _includes/scripts.html, package-lock.json, package.json
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-move-dap-head/) → 
- Moves analytics to the `head` and out of the `body` per best practices
- Add `async` property and `type` to the DAP script
- Move GA before DAP per best practices
- Move all analytics before stylesheets per best practices
- Use modern browser (post IE9) GA code
- Update Snyk settings
=> Move analytics to the head

_components/identifier.md, _data/nav.yml, _data/settings/components/identifier.yml, _includes/code/components/identifier.html, _includes/footer.html, config/crawl.js, css/settings/_uswds-theme-components.scss, package-lock.json, package.json
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/add-identifier/components/identifier/)
This is still pending final final Spanish copy, but it's good enough to review and merge right now. We can add final copy in a subsequent PR.
=> Add identifier component guidance and add to site footer

pages/documentation/getting-started/sample-contract-language.md
[Preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-contract-language/documentation/sample-contract-language/)
Fixes https://github.com/uswds/uswds-site/issues/1066
- Add user scenarios link
- Add de-risking guide link
=> USWDS - Documentation: Update sample contract language page.

.snyk, _includes/download-buttons-design.html, package-lock.json, package.json
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-add-assets-2.3.0/documentation/designers/) → 
This updates the USWDS design asset links to those released in [assets v2.3.0](https://github.com/uswds/uswds-for-designers/releases/tag/v2.3.0).
=> Update links to assets v2.3.0

_components/identifier.md
[Guidance](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-identifier-typo/components/identifier/)
Fixes typo in Identifier guidance `indicator → identifier`.
=> USWDS - Identifier: Fix typo on guidance.

.snyk, _components/page-templates/page-templates.html, package-lock.json, package.json
Part of #1092
Fixes #1094
Updated heading order on Page Templates.
=> a11y - Templates: Update heading order.

.snyk, _includes/head.html, package-lock.json, package.json
Add `uswds-init` script from USWDS 2.10.0 to prevent banner flashing.
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-add-init/) →
=> Add initializer

.snyk, Gemfile, Gemfile.lock, _components/icons.md, _components/site-alert.md, _config.yml, _data/settings/components/checkbox.yml, _data/settings/components/collection.yml, _data/settings/components/radio.yml, _data/settings/components/summary-box.yml, _includes/code/components/process-list.html, _includes/code/syntax.html, _includes/footer.html, package-lock.json, package.json, pages/documentation/getting-started/settings.md
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-site-component-cleanup/) →
=> [Site] Accelerator component cleanup

.snyk
Ran `snyk wizard` to ignore reports for 30 days due to lack of available patches.
---
=> Run snyk wizard to ignore packages for 30 days.

.snyk, css/_uswds-theme-custom-styles.scss, package-lock.json, package.json, pages/whats-new/product-roadmap.md
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-update-2021-roadmap/about/product-roadmap/) →
=> Update with 2021 roadmap items

.snyk, _config.yml, _includes/download-buttons-design.html, files/next/README.md, package-lock.json, package.json, pages/documentation/getting-started/fundamentals.md
Updates USWDS version to latest 2.10.2.
=> Use USWDS 2.10.2

_posts/2021-03-11-whats-next-for-uswds.md
=> [USWDS-Site] Add /next feature card to blog post

_posts/2021-03-01-improving-emergency-response.md, _posts/2021-03-11-whats-next-for-uswds.md, css/uswds-next.scss
=> [USWDS-Site] Darken the/next site-header colors for contrast

Gemfile.lock, _layouts/landing.html
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-next-banner/) →
=> Update notice banner to point to Next report

_includes/next/next-opportunities-list.html
=> Fix grid reflow on /next opportunity lists

_config.yml, pages/documentation/getting-started/fundamentals.md
We changed the primary `uswds` branch to `main` from `master`. This PR updates all references in this repo as well.
=> Update uswds/uswds refs to main

.snyk, package-lock.json, package.json
Based on CircleCI build error on task [4090](https://app.circleci.com/pipelines/github/uswds/uswds-site/1378/workflows/26313484-55ba-4899-93f6-49c2ee43ad81/jobs/4090). Snyk needs to be updated to latest.
=> USWDS - Deps: Update snyk.

package-lock.json, package.json
=> USWDS SITE - POAM | updates snyk 

_includes/download-buttons-design.html, pages/about/key-benefits.md
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-add-designkit-2.4.0/documentation/designers/) →
Adds the most current DL link to the Sketch/XD design assets
=> Update links to Design Kit 2.4.0

pages/design-tokens/color/system-tokens.md
Closes #936.
[Preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-system-color-sidenav/design-tokens/color/system-tokens/)
Ordering is based on the color wheel.
=> USWDS - System Colors: Update color tokens based on color wheel.

.snyk, _includes/code/components/_default.html, _includes/code/components/accordion.html, _includes/code/components/alert.html, _includes/code/components/banner-code.html, _includes/code/components/banner.html, _includes/code/components/breadcrumb.html, _includes/code/components/button.html, package-lock.json, package.json
Fixes mismatching closing tag in headers `_includes/code/components`.
**Old**
```
<h3 class="site-preview-heading">Borderless</h6>
```
**New**
```
<h3 class="site-preview-heading">Borderless</h3>
```
[Accordion example →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-fix-headers/components/accordion/)
---
=> USWDS - Code previews: Fix mismatching headers in previews.

.snyk, package-lock.json, package.json, pages/whats-new/product-roadmap.md
Closes #1239. Updates roadmap by setting _Publish high-level system benefits_ and _Pagination_ to `Done`.
Additional updates are below.
**In progress**
- component-based versioning
- production-ready component templates
- journey maps and service blueprint
**Done**
- Improve migration page
- Improve test suite
[Roadmap preview →
](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-roadmap-1239/about/product-roadmap/)
=> USWDS-Site - Roadmap: update roadmap item status.

css/uswds-next.scss, package-lock.json, package.json
[Next report citations→](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-a11y-next-footnote-links/next/introduction/#citations)
Closes uswds/uswds/issues/4264. Adds underline to footnote links. Fixes 7 reported Siteimprove a11y issues related to _Links are not clearly identifiable._ The remaining 7 issues will be resolved via an update to the Siteimprove reporting. 
Before / After
Also removed unnecessary whitespaces in CSS.
=> USWDS - Next links: add underline to footnote links.

_components/link/link.md
[Link guidance →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-remove-link-note/components/link/)
Removes the yellow note about findings marked `under review` and adds Research findings to Link's subnav.
- Remove note
- Add research findings to subnav
=> USWDS - Links: Update guidance page

_components/link/link.md
[Link guidance page →
](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-link-guidance-update/components/link/)
Updates _About_ copy on Link guidance page.
N/A
=> Link guidance: update about section.

_components/table/table.md
Adding note that link points to plainlanguage.gov
* Notes
* etc.
=> Table external links

_utilities/layout-grid.md
Updating $theme-utility-breakpoints: code snippet to say 1024PX instead of 1040PX
* Notes
* etc.
=> Changing 1040px to 1024px

pages/documentation/getting-started-developers/overview.md, pages/documentation/getting-started-developers/phase-one.md, pages/documentation/getting-started-developers/phase-three.md
Adds the copyedits I missed in https://github.com/uswds/uswds-site/pull/1362
=> Add final copyedits

pages/documentation/getting-started-developers/overview.md, pages/documentation/getting-started-developers/phase-three.md, pages/documentation/getting-started-developers/phase-two.md
[
Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-getting-started-devs-edits/documentation/getting-started-for-developers/)
TK
TK
* Notes
* etc.
=> Getting Started Devs: Copy edits

css/settings/_uswds-theme-utilities.scss
Clone of https://github.com/uswds/uswds-site/pull/1288, which went sideways for some reason
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-update-colors/design-tokens/color/state-tokens/) →
=> Update emergency colors

_utilities/overview.md
Addressed logic and grammatical errors
Revised for concision, clarity, and inclusivity
=> copyedit round 1 utilities

_utilities/layout-grid.md
Revised for grammatical accuracy, consistency, clarity, and accessibility.
=> copyedit round 1 layout grid

_components/button/guidance/implementation.md, _components/button/guidance/usability.md
Revised for inclusive language, grammatical accuracy, and clarity.
=> Copyedit round 1 button

_components/header/guidance/variants/basic-mega/about.md, _components/header/guidance/variants/basic-mega/when-to-consider-something-else.md, _components/header/guidance/variants/basic-mega/when-to-use.md, _components/header/guidance/variants/basic/about.md, _components/header/guidance/variants/basic/when-to-consider-something-else.md, _components/header/guidance/variants/extended-mega/about.md, _components/header/guidance/variants/extended-mega/when-to-consider-something-else.md, _components/header/guidance/variants/extended-mega/when-to-use.md, _components/header/guidance/variants/extended/about.md, _components/header/header.html
Revised for grammatical accuracy, inclusive language, and concision.
=> Copyedit round 1 header

_components/banner/banner.md, _components/banner/guidance/accessibility.md, _components/banner/guidance/implementation.md, _components/banner/guidance/usability.md, _components/banner/guidance/when-to-consider-something-else.md
Revised for grammar, clarity, and inclusive language
=> Copyedit round 1 banner

_components/form/form.md, _includes/accessibility.html
Revised for grammar, clarity, and inclusive language.
=> Copyedit round 1 component form

pages/documentation/website-standards.md
For consistency with other pages, revised so that the lead text is a complete sentence with end punctuation.
=> Revised lead text

_components/typography/typography.md
Addressed comma errors and consistency issues.
Removed confusing passive voice.
Ensured lists are introduced by a complete sentence.
=> Copyedit round 1 typography

pages/design-principles/design-principles.md
Revised lead text for consistency.
Conducted general copyedit of page.
=> Copyedit round 1 design principles

pages/design-tokens/color/overview.md
Revised for grammar, consistency, style guide compliance, accessibility, and inclusivity.
=> copyedit round 1 color

_data/tokens/spacing.yml
=> USWDS Site: Spacing - Changed tablet-lg breakpoint from 880px to 800px

pages/documentation/getting-started-developers/phase-two.md
Fixes theme path based on recent README update to uswds-compile.
=> Fix uswds-compile path in Phase 2

Gemfile.lock, _components/button-group/button-group.md, _components/data-visualizations/data-visualizations.md, _components/form/form.md, _components/header/header.html, _components/table/table.md, _components/typography/typography.md, _includes/touchpoint-survey-script.html, _layouts/component.html, pages/design-tokens/color/overview.md, pages/design-tokens/color/state-tokens.md, pages/design-tokens/color/system-tokens.md, pages/design-tokens/color/theme-tokens.md, pages/design-tokens/flex.md, pages/design-tokens/opacity.md, pages/design-tokens/order.md, pages/design-tokens/overview.md, pages/design-tokens/shadow.md, pages/design-tokens/spacing-units.md, pages/design-tokens/typesetting/font-family.md, pages/design-tokens/typesetting/font-size.md, pages/design-tokens/typesetting/font-weight.md, pages/design-tokens/typesetting/font.md, pages/design-tokens/typesetting/letterspacing.md, pages/design-tokens/typesetting/line-height.md, pages/design-tokens/typesetting/measure.md, pages/design-tokens/typesetting/overview.md, pages/design-tokens/z-index.md, pages/ui-components/overview.md, pages/ui-components/packages.md
Resolves #1457.
Install Touchpoints survey on the pages/sections noted [here](https://docs.google.com/document/d/11DMlZeS4eUNc7n2g6hawoUVvHI2gcCeEj4-i660DtRU/edit?usp=sharing)
Script implemented:
`<script src="https://touchpoints.app.cloud.gov/touchpoints/5c2410e4.js" async></script>`
using include `touchpoint-survey-script.html`:
=> USWDS-Site - Touchpoint Survey

_components/date-picker/guidance/when-to-consider-something-else.md
Removing double / to fix broken link
* Notes
* etc.
=> Fixing broken links

_components/time-picker/time-picker.md, _config.yml, package-lock.json, package.json
- Use USWDS 2.13.3 on the site.
- Update Time Picker's initialization props to document `value` prop
=> Use 2.13.3

_config.yml, _includes/footer.html, _includes/touchpoint-survey-script.html
[Sample page with survey ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-hosted-touchpoints/design-tokens/)
Test delivering Touchpoints via "Hosted only on the touchpoints site" so that we can remove the script related to the pa11y-ci crashes and false errors (error notes detailed in https://github.com/uswds/uswds-site/pull/1541).
=> [Test] V3 - Update touchpoints delivery

_includes/touchpoint-survey-script.html
Update Touchpoints survey href to point to current live survey.
=> USWDS 3.0 - Touchpoints href update

pages/ui-components/packages.md
[Packages page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-packages-updates/components/packages/)
Copy edits for packages page
=> USWDS 3.0 - Package page edits

_posts/2022-04-28-introducing-uswds-3-0.md
[Introducing USWDS 3.0 post](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-intro-edits/whats-new/updates/2022/04/28/introducing-uswds-3-0/)
Edits for the "Introducing USWDS 3.0" post
=> USWDS 3.0 - "Introducing USWDS 3.0" edits

_posts/2022-04-28-introducing-uswds-3-0.md
- Update link to migration guide
- Fix capitalization on "Packages"
[Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-intro-post-edits/whats-new/updates/2022/04/28/introducing-uswds-3-0/)
=> USWDS 3.0 - Intro post - Update link to migration guide

_includes/nav/page-collapsible.html, _includes/navbar.html, css/_uswds-theme-custom-styles.scss
[Home page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-nav-icon-fix/)
Update outdated structure for mobile menu nav icons
Current appearance in [`develop`](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/develop/components/packages/):
=> USWDS 3.0 - Repair mobile nav icons

_data/packages.yml, pages/ui-components/packages.md
[Packages page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-packages-copyedits/components/packages/)
=> USWDS 3.0 - Packages page edits

package-lock.json, package.json
=> Use USWDS 3.0.0

_posts/2022-04-28-introducing-uswds-3-0.md, pages/documentation/migration-V3.md
[Migration 3.0 page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-migration-edits/documentation/migration/)
Small copy edits and code checks
=> USWDS 3.0 - Migration page copy edits

package-lock.json, package.json
Sets `@uswds/uswds` to use develop branch. Related to https://github.com/uswds/uswds-site/issues/1618.
=> Use USWDS develop branch

.circleci/config.yml
CircleCi suggested I update the resource class of our containers, so I did!
=> Update CircleCI to large resource class in config.yml

_data/nav.yml, pages/about/contribute.md
[Contribute →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/cm-contribution-guide/about/contribute/)
Resolves #1655 
Creates Contribution guide page and adds nav link. As specified in [Contribution Guidance](https://docs.google.com/document/d/1CLNcJdmcK1LHU1NQIOcfA36oCyalNBOCYPTT0vdvnJY/edit#heading=h.sn6uij4bzeph) doc
=> Add Contribution Guide

pages/whats-new/product-roadmap.md
Updates the Roadmap page according to Elisa & Bonnie's draft.
[Preview link for Roadmap](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/roadmap-page-updates-sprint-12/about/product-roadmap/)
=> Roadmap-page-updates-sprint-12

_components/date-picker/date-picker.md
- fixes #1376
- fixes #1374 
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/content-edits-sprint-12) →
=> Sprint 11 content update

pages/documentation/getting-started-developers/phase-three.md, pages/documentation/getting-started-developers/phase-two.md
Adds additional notes to Phase 2 and 3 of _Getting Started for Devs_. Closes #1615 #1616.
**Phase two** - [preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-getting-started-devs/documentation/getting-started/developers/phase-two-compile/#step-5-initialize-your-project)
Added examples for init and verification - [0a8cebe](https://github.com/uswds/uswds-site/pull/1667/commits/0a8cebea2774ac8b63d9370a8050a2a49c2a0483)
**Phase three** - [preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-getting-started-devs/documentation/getting-started/developers/phase-three-customize/)
Changed filename for theme settings - …
=> Docs - Getting started: update notes on phase 2 and 3

_components/date-range-picker/guidance/usability.md, _components/input-prefix-suffix/guidance/usability.md, _components/link/guidance/usability-should.md, _components/process-list/guidance/when-to-consider-something-else.md, _components/step-indicator/guidance/implementation.md, _components/step-indicator/guidance/usability.md, _components/typography/typography.md
This pull request addresses several community-contributed content updates in the uswds-site backlog. 
It includes updates to:
- minor typos
- URL redirects
- 404 links
- minor formatting errors
It resolves:
- #1377 
- #1384 
- #1385 
- #1391 
- #1394 
- #1395 
- #1399 
- #1400
=> Content edits 22 sprint 13

README.md
Quick change that fixes a broken link
from
https://bundler.io/v1.13/guides/using_bundler_in_application.html#getting-started---installing-bundler-and-bundle-init
to
https://bundler.io/guides/using_bundler_in_applications.html#getting-started---installing-bundler-and-bundle-init
* Notes
* etc.
=> Fix broken Bundler URL in README

pages/about/community.md
Removed Ammie as a community manager on the [Community](https://designsystem.digital.gov/about/community/) page. Can you please review this change and make sure all formatting looks correct on the page? Thank you!
=> removed Ammie Farraj Feijoo from community page

_components/data-visualizations/data-visualizations.md
On the Data Visualization page, update the link in the Colors section that points to the Nightingale article on Medium. The link should now point to: https://nightingaledvs.com/how-to-choose-colors-for-your-data-visualizations/
Link provided by Amanda Makulec from Nightingale, who pointed out that the previous link to Medium sometimes became paywalled for users. Nightingale has migrated to a standalone platform that does not have a paywall.
None.
- [] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
=> Website - Enhancement: Updating link for Colors section

_data/settings/color.yml
The variables for `primary-vivid` and `secondary-vivid` are incorrect. (They repeat the variables for `primary` and `secondary` instead of using the associated vivid variable.)
n/a
=> USWDS-Site: Vivid variable typos on Settings page

_config.yml, _next/01-summary.md, _next/02-introduction.md, _next/03-00-findings.md, _next/03-01-benefits.md, _next/03-02-get-started.md, _next/03-03-team.md, _next/03-04-community.md, _next/03-05-improve.md, _next/04-00-looking-ahead.md, _next/04-01-engagement.md, _next/04-02-guidance.md, _next/04-03-collaboration.md, _next/04-04-vision.md, _next/05-get-involved.md, _posts/2017-04-26-fractal-federalist.md, _posts/2019-04-08-introducing-uswds-2-0.md, _posts/2020-09-08-Improvements-banner.md, _posts/2021-02-05-sharing-the-govlove.md, _posts/2021-03-01-improving-emergency-response.md, _posts/2021-03-11-whats-next-for-uswds.md, _posts/2021-03-24-working-with-uswds-team.md, _posts/2022-04-28-introducing-uswds-3-0.md, package-lock.json
**Fixed an issue with redirects not working properly.**  Removed default `url` setting in Jekyll's `_config.yml` that was messing with redirects in Federalist. For example, previously if you clicked on `Components` in federalist preview, the redirect to `/components/overview` would return a 404.
**Updated USWDS Federalist preview URL**. The `federalist_base` now accurately reflects the new pages.cloud.gov url for USWDS components. The migration from federalist to pages.cloud.gov was done on 09/26/22. 
Additionally preview images are now working properly. For example, when pasting a USWDS link to Slack.
**Before**
**After**
---
=> USWDS - Redirects: Fix 'Components' link in page previews

_layouts/together-content.html, _together/01-summary.md, css/uswds-together.scss
=> 1872 cta in nav

_together/01-summary.md
Remove duplicate paragraph in measure 4 "A commitment to the practice of inclusivity..."
* [Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jd-together-report/together/#:~:text=a%20commitment%20to%20the%20practice%20of%20inclusivity)
=> USWDS-Site - Together report : update summary page to remove duplicate content

_layouts/landing.html
Jacline and I have updated the site banner by:
1. Removing the patterns library content
2. Adding the link to the top tasks survey with custom text 
3. changing the color of the banner
Preview link: [Home page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/bc-jc-touchpoints-for-toptasks/)
=> adding touchpoints top tasks survey to site banner

_config.yml, _data/changelogs/component-form.yml, _data/changelogs/component-header.yml, _data/changelogs/component-in-page-navigation.yml, package-lock.json, package.json
- Uses USWDS 3.4.1
- Adds changelog items for changes in USWDS 3.4.1
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/release-3.4.1/) →
=> Release 3.4.1

css/custom-styles/_copy-code-btn.scss, js/copy-code.js
Reorganized copy code component JS and added code comments.
Related to #2055.
Preview link: [Button](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-copy-component-btn/components/button/)
The previous JS is good, but we can improve further by adding comments. We can also increase readability by separating the code out more.
```bash
. copy-code
├── buildHTML
└── btnFunction
```
```bash
. copy-code
├── createWrapper
├── createCopyButton
├── copyOnClick
└── init
```
This PR does the following:
1. Creates additional top-level `const` for further code reuse
2. Uses BEM naming convention _ex: `usa-copy-code__btn`_ (previously `usa-copy-code--btn`).
3. Separates button and wrapper creation
4. Adds JSDoc comments
5. Adds missing attribute …
=> Copy component refactor

_data/changelogs/component-accordion.yml
Adds the following change log for 
https://github.com/uswds/uswds/issues/5285
[Accordion change log](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-accordion-hc-changelog/components/accordion/#latest-updates)
=> USWDS-Site - Accordion: Create change log for USWDS#5286

_components/identifier/guidance/implementation.md, _data/changelogs/component-identifier.yml
**Updated Accessibility statement link text guidance.** Updated the Identifier guidance to use the text "Accessibility statement" for the required link to an accessibility statement. We improved the supporting links that describe accessibility statements.
Closes https://github.com/uswds/uswds/issues/5092
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/dw-identifier-accessibility/components/identifier/) → 
We'd like to support teams adding Accessibility statement links to their sites. Our existing guidance is a little bit ambiguous (pointing to "parent agency"), and we can clear it up by saying that these links should point to "your website or service's accessibility statement, or to your agency's accessibility statement …
=> Update Identifier Accessibility Statement link text guidance

_data/changelogs/component-table.yml
Created a changelog entry for PR  https://github.com/uswds/uswds/pull/5280
Related to https://github.com/uswds/uswds/pull/5280
Preview link: Table changelog
=> USWDS-Site: Add changelog entry for 5280 (Single quote in sortable table headers)

_data/changelogs/component-button.yml
Added a changelog entry for https://github.com/uswds/uswds/pull/5247
https://github.com/uswds/uswds/issues/5246
[Button change log →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-button-type-changelog/components/button/#latest-updates)
=> USWDS-Site - button: Add change log entry of PR #5247

package-lock.json, pages/patterns/complex-form/progress-easily.md, pages/patterns/create-a-profile/social-security-number.md
Fixed build errors found in https://github.com/uswds/uswds-site/pull/2096
- Updated `package-lock.json` with newest updates from `develop` to repair errors found in [a11y_mobile](https://app.circleci.com/pipelines/github/uswds/uswds-site/4977/workflows/f4e9a2c3-538a-4a2a-b5bf-244f612a2ed4/jobs/18276) tests
- Updated broken/404 links to repair errors found  during [HTML Proofer checks](https://app.circleci.com/pipelines/github/uswds/uswds-site/4977/workflows/f4e9a2c3-538a-4a2a-b5bf-244f612a2ed4/jobs/18275).
Note: HTML Proofer will still flag errors related to `https://github.com/uswds/uswds/releases/tag/v3.5.0`. This will resolve once 3.5.0 is out.
This should resolve some of the build errors found in https://github.com/uswds/uswds-site/pull/2096
Preview link: 
- [Social security number …
=> USWDS-Site: Fix build errors

_data/settings/typography.yml
Added heading top margin and paragraph top margin settings.
=> Final changes from release process

_data/changelogs/component-identifier.yml, _data/changelogs/component-table.yml, _data/changelogs/utilities.yml
Replace placeholder dates with actual dates.
Closes #2199.
| Page | Old | New |
|:--------|------|------|
| Identifier | [preview](https://designsystem.digital.gov/components/identifier/#latest-updates) | [preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-bugfix-changelog-dates/components/identifier/#latest-updates) |
| Table | [preview](https://designsystem.digital.gov/components/table/#latest-updates) | [preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-bugfix-changelog-dates/components/table/#latest-updates) |
| Utilities | [preview](https://designsystem.digital.gov/utilities/#latest-updates) | [preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57 …
=> USWDS - Changelogs: Fix changelog dates

pages/design-tokens/color/overview.md, pages/design-tokens/color/state-tokens.md, pages/design-tokens/color/system-tokens.md, pages/design-tokens/color/theme-tokens.md
**Color token redirects for easier access.** Token pages for `theme`, `state`, and `system` have redirects that quick access to guidance.
Closes #1692.
Preview links for new redirects:
- **Color overview**
- [/color](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-enhancement-token-redirects/color)
- **Theme tokens**
- [/components/colors/theme](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-enhancement-token-redirects/components/colors/theme)
- [/colors/theme](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-enhancement-token-redirects/colors/theme)
- [/color/theme](https://federalist-ead78f8d-8948-417c-a957-c21ec5617 …
=> USWDS-Site - Colors: Add redirects for color tokens

pages/documentation/showcase.md
The General Coordinates Network (GCN) is a public collaboration platform run by NASA for the astronomy research community to share alerts and rapid communications about high-energy, multimessenger, and transient phenomena.
=> USWDS-Site - Showcase: Add NASA's General Coordinates Network to the showcase

_data/changelogs/component-banner.yml
Add changelog entry for banner icon alignment.
https://github.com/uswds/uswds/pull/5370
[Banner changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5370/components/banner/#changelog)
=> USWDS-Site - Changelog: Banner icon alignment [#5370]

_data/changelogs/component-card.yml
Creates changelog for https://github.com/uswds/uswds/pull/5423
https://github.com/uswds/uswds/issues/5401
[Card changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-card-header-first-media-changelog/components/card/#latest-updates)
=> USWDS-Site: Create changelog for USWDS#5423

_data/changelogs/component-modal.yml
Add changelog entry for modal body padding fix.
https://github.com/uswds/uswds/pull/5493
[Modal changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5493/components/modal/#changelog)
=> USWDS-Site - Changelog: Modal body padding  [#5493]

_data/changelogs/component-table.yml
Changelog entry for uswds/uswds#5477
[Table changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-stacked-table-voice-over-fix-changelog/components/table/#latest-updates)
=> USWDS-Site - Changelog: Stacked table VoiceOver fix [#5477]

_data/identifier.yml
**Update site identifier to include up-to-date accessibility statement link text.** We updated the text in our site identifier to read "Accessibility statement" and to link to the most current GSA accessibility statement: https://www.gsa.gov/website-information/accessibility-statement.
Closes #2284 
Preview link: TK
In USWDS 3.5.0 we updated the identifier to use the text “Accessibility statement” but our site's Identifier still says "Accessibility support". Let's update the Identifier to reflect our current guidance, and be sure we link to the GSA.gov accessibility statement with its most up-to-date url: https://www.gsa.gov/website-information/accessibility-statement
- Updated the identifier to use the text “Accessibility statement”.
- Updated the URL to GSA's most up-to-date …
=> USWDS-Site - Update site identifier with new accessibility statement link text/URL

_data/changelogs/component-date-picker.yml
Added changelog entry for https://github.com/uswds/uswds/pull/5374
> Improved keyboard navigation for screen readers.
[Date picker change log →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-date-picker-jaws-changelog/components/date-picker/)
=> USWDS-Site: Add changelog for #5374

_data/changelogs/component-banner.yml
Add changelog entry for optimizing banner flag icons
https://github.com/uswds/uswds/pull/5542
[Banner changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5542/components/banner/#changelog)
=> USWDS-Site - Changelog: Create entry optimized banner icons [#5542]

_data/changelogs/component-footer.yml
Changelog entry for https://github.com/uswds/uswds/pull/5588
https://github.com/uswds/uswds/pull/5588
Preview →
=> USWDS-Site - Changelog: Create entry for Footer a11y links [#5588]

_data/changelogs/component-header.yml
Changelog entry for uswds/uswds#5655
Working branch: uswds/uswds#5655
Feature branch: uswds/uswds#5654
[Preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5655/components/header/)
=> USWDS-Site - Changelog: Header button padding fix [#5655]

_data/monthly-calls.yml, pages/about/monthly-calls.md
Added the monthly call video and details for November 2023. 
Closes #2391
[Monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-nov-mc/about/monthly-calls/)
- Confirm that the information in the update is accurate
- Confirm no spelling or grammatical errors
- Confirm that the links all work as expected.
=> USWDS-Site: Add monthly call for November 2023

.snyk, pages/documentation/getting-started-developers/overview.md
- Updated snyk ignore files
- Updated github readme link to fix html-proofer error
- [Getting started for developers overview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-snyk-jan/documentation/getting-started-for-developers/#what-you-need)
`npx snyk test` is throwing the following error:
```
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1
introduced by @uswds/compile@1.1.0 > gulp@4.0.2 > gulp-cli@2.3.0 > yargs@7.1.2 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1 and 4 other path(s)
This issue was fixed in versions: 3.0.1, 4.1.1, 5.0.1, 6.0.1
✗ Missing Release of Resource after …
```
=> USWDS-Site: Fix snyk and html-proofer errors

_data/monthly-calls.yml
Adding the January 2024 video, along with a description and related links, to the USWDS monthly call page.
This purpose of this PR is to update the monthly call page to include a video (and supplemental information) for hte January 2024 monthly call. This update will keep the page relevant and timely.
Closes #2464 
[Monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/sls-jan-24-mc-page-updates/about/monthly-calls/)
The January 2024 video needs to be added to the USWDS monthly calls page. 
This action will add the January 2024 video to the monthly call page so that the USWDS community can enjoy it!
_Provide a summary of the solution this PR offers._
NA
_For complex PRs, create a list of the significant updates made._ …
=> USWDS-Site: Add January 2024 monthly call

_data/changelogs/component-table.yml
Changelog entry for uswds/uswds#5783.
Closes #2261.
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-table-demo/components/table/#latest-updates)
=> USWDS - Changelog: Add entry for table demo update

_data/changelogs/component-accordion-accessibility.yml, pages/documentation/showcase.md
Follow-up to #2557. Updates changelog date.
=> USWDS-Site - Changelog: Update accordion changelog note

_data/monthly-calls.yml
Added April Monthly call content to the Monthly Calls page.
Note: Also removed a period from the March MC description as we are not including periods in the format there. 
This purpose of this PR is to update the monthly call page to include a video (and supplemental information) for the April 2024 monthly call. This update will keep the page relevant and timely.
Closes #2632 
Preview link: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-MCpageupdate-April/about/monthly-calls/
The April 2024 event needs to be added to the USWDS monthly calls page.
This action will add the April 2024 event to the monthly call page so that the USWDS community can enjoy it!
Please proof the new content and make sure it's formatted correctly.
=> Add April 2024 monthly call

_data/changelogs/component-tooltip.yml
Add changelog entry for tooltip hoverable fix
https://github.com/uswds/uswds/pull/5919
[Tooltip  changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5919/components/tooltip/#latest-updates)
=> USWDS-Site - Changelog: Tooltip hoverable fix [#5919] 

_data/changelogs/component-button-group.yml
Add changelog entry for nested button styles
https://github.com/uswds/uswds/pull/5885
[Button group changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5885/component/button-group#changelog)
=> USWDS-Site - Changelog: Nested button group styles [5885]

_data/changelogs/about-monthly-calls.yml, _data/monthly-calls.yml
Adding May monthly call content to MCs page. We don't have video link yet, so I left that blank. We may have to add at a later date.
> [!NOTE]
> Continuation of @finekatie work to avoid build error.
Closes #2698 
[Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-mayMC-MCspage/about/monthly-calls/)
New May content added to yml file. 
Need review to make sure it was added correctly and that there's no spacing/code issues with link missing.
=> USWDS-Site - Monthly Call page: Update MC page with May content

_data/monthly-calls.yml
Adding June Monthly Call content and link for May Monthly Call video to Monthly Calls page 
Closes #2726 
https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-juneandmay_MCspgupdate/about/monthly-calls/
Needed to get Monthly Calls page up to date with June call info. 
June Monthly Call summary was approved and is ready to be added to the page. Also learned the May Monthly Call video was added on the Digital.gov Events page, so that's added too.
Need someone to look and make sure links work and content is clean and clear.
=> Monthly Calls page: Add June MC content and link for May video 

package-lock.json, package.json
This reverts to USWDS 3.8.1 to see if it has an effect on our site's instance of date picker.
[Date Picker](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/dw-test-3.8.1/components/date-picker/) →
=> Test with USWDS 3.8.1

package-lock.json, package.json
This reverts our site back to USWDS 3.8.2 since determining that our Date Picker issue is not related to any changes in the new release.
=> Revert to USWDS 3.8.2

_data/settings/components/banner.yml
Quick fix to Banner background color token type from `family → color`.
Quick fix, so didn't create an issue.
Preview link: [Settings page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-fix-banner-token-type/documentation/settings/#component-settings-2:~:text=Background%20color%20of%20the%20banner%20and%20its%20content.)
Background color incorrectly lists `family` instead of color.
Changed token type from `family → color`.
1. Visit [settings page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-fix-banner-token-type/documentation/settings/#component-settings-2:~:text=Background%20color%20of%20the%20banner%20and%20its%20content.)
2. Find `$theme-banner-background-color`
3. …
=> USWDS-Site - Documentation: Fix banner token type

.circleci/config.yml
Updated the version of snyk to 2.2.0 in .circleci/config.yaml
_Provide a one or two sentence summary of the update that can be used in the changelog._
Closes #2792 
Preview link:
_Summarize the problem this PR solves in a clear and concise statement._
_Provide a summary of the solution this PR offers._
_For complex PRs, create a list of the significant updates made._
_Share recommended methods for reviewing this change._
=> USWDS-Site - CircleCI: Update snyk version to 2.2.0

_data/changelogs/about-monthly-calls.yml, _data/monthly-calls.yml
Adding August Monthly Call content to Monthly Calls page 
> [!Important]
> The changelog date will need to be updated before merge.
Closes #[6025 ](https://github.com/uswds/uswds/issues/6025)
[Monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-aug_MCspgupdate/about/monthly-calls/)
Needed to get Monthly Calls page up to date with August call info. 
August Monthly Call summary was approved and is ready to be added to the page. Video will not be going up until later in the month. Will need a new ticket or branch off this when it's ready.
Need someone to look and make sure links work and content is clean and clear.
=> Add August MC content

pages/documentation/website-standards.md
Updating links for better support to users and to prevent changes being needed in the future.
Update to #2843 
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/ap-website-standards-updated-links/website-standards)
Confirm content matches the content in [USWDS - Website standards page](https://docs.google.com/document/d/1eN8aLjKGcrxwYR4MFc_E-ShdMhqYRHyiAZ1-jJayl6U/edit) (Google docs 🔒)
Confirm page formatting appears as expected
Confirm changelog entry is appropriate and free from error
=> USWDS-site - Web standards page: links update

.github/PULL_REQUEST_TEMPLATE.md
Added a changelog requirement to the PR template
Closes #2174
1. Confirm that the updated instructions are appropriate and make sense
1. Confirm no spelling or grammatical errors
=> USWDS-Site: Add changelog requirement to PR template

_data/changelogs/pattern-complex-form-keep-a-record.yml, pages/patterns/complex-form/keep-a-record.md
Replacing some phrasing and updating linkage on the Usability guidance content for the [Keep A Record pattern](https://designsystem.digital.gov/patterns/complete-a-complex-form/keep-a-record/). 
Replacing this:
Test print outputs. Test printing using a variety of printers, print-to-PDF options, and assistive output devices, using [representative browser and operating system combinations](https://digital.gov/2013/07/15/digital-metrics-for-federal-agencies) prior to launch. Remember that mobile device users will have additional challenges printing or saving to PDF so some on-screen guidance may be necessary.
with this:
Test print outputs. Test printing using a variety of printers, print-to-PDF options, and assistive output devices, using representative browser and operating system …
=> Updating content and link in Test broadly section

_data/changelogs/component-file-input.yml
Add a changelog entry for https://github.com/uswds/uswds/pull/5997
=> USWDS-Site - Add changelog for file input component CSP fix 5997

_data/changelogs/component-checkbox.yml
Add a changelog for PR uswds/uswds#6162
>[!important]
Related to uswds/uswds#6162
Checkbox changelog
=> USWDS-Site: Add changelog for checkbox SVGs [#6162]

_data/changelogs/template-create-account.yml, _data/changelogs/template-password-reset.yml, _data/changelogs/template-sign-in-form.yml, _templates/form-templates/password-reset/password-reset-form.md, _templates/form-templates/sign-in/sign-in-form.md
Add a changelog for PR uswds/uswds#6308
>[!important]
- [Create account template](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-6308/templates/authentication-pages/create-account/#latest-updates)
- [Sign in form template](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-6308/templates/form-templates/sign-in-form/#latest-updates)
- [Password reset template](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-6308/templates/form-templates/password-reset-form/#latest-updates)
=> USWDS-Site: Add changelog for resolve-id-refs replacement [#6308]

_components/in-page-navigation/in-page-navigation.md, _data/changelogs/component-in-page-navigation.yml
Add a changelog for PR uswds/uswds#6205
>[!important]
[In-page navigation changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/ml-changelog-6205/components/in-page-navigation/#changelog)
=> USWDS-Site: Add changelog for in-page navigation [#6205]

_components/modal/accessibility-tests.md, _components/modal/modal.md, _data/accessibility-tests/modal.yml, _data/changelogs/component-modal-accessibility.yml, _data/changelogs/component-modal.yml
Added accessibility test page for modal component
> [!Important]
> We need to update changelog dates before merge
Closes #2907
- [Modal component page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-a11y-checklist-modal/components/modal/)
- [Modal acecssibility tests page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-a11y-checklist-modal/components/modal/accessibility-tests/)
=> USWDS-Site: Add modal accessibility checklist page

README.md
This pull request updates the `README.md` file for contributing back to the U.S. Web Design System Documentation Website. It removes no longer needed dependency references and creates clearer guidance for folks starting from scratch.
=> Update README.md for USWDS documentation website

_components/input-mask/accessibility-tests.md, _components/input-mask/input-mask.md, _data/accessibility-tests/input-mask.yml, _data/changelogs/component-input-mask-accessibility.md, _data/changelogs/component-input-mask.yml
Fixes #3127
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/js-fix-3127/components/input-mask/)
=> Update input mask component with accessibility test results.

_components/data-visualizations/data-visualizations.md, _components/typography/typography.md, pages/design-tokens/color/overview.md, pages/documentation/guidance/accessibility.md, pages/documentation/showcase.md
Changes to digital.gov — including the move of accessibility.digital.gov to https://digital.gov/guides/accessibility-for-teams — are causing our CircleCI tests to fail and thus preventing us from publishing any updates to the site.
Updating all 404ing links.
Updates or removes links that are no longer available (404s) and enables all tests to pass, so we can proceed with any site publishing.
Discovered via checks on https://github.com/uswds/uswds-site/pull/3139
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/annepetersen-dg-404-fixes/)
Update accessibility.digital.gov links to their correct new locations.
Fixes 404s on:
https://accessibility.digital.gov/visual-design/data-visualizations/ — on the [Data visualization …
=> USWDS-Site: fix new digital.gov 404s

_includes/analytics.html
Update rollup ID
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/mh-update-ga-id/)
=> USWDS Site: update GA ID
