_config.yml
This also excludes the `gulpfile.js` and the `circle.yml` from the build step.
=> Updating _config.yml to point to the correct version of the Standards.

README.md
This pull request removes the disclaimer text at the top of the `README.md` file. It also updates the `npm link` instructions to ensure folks know to build the package locally. Some of the gulp scripts use files inside of our distributed folder, which only gets created during this build process.
=> Update README.md disclaimer and instructions

css/styleguide.scss, js/components/sticky-nav.js
Fixes the sticky nav bug for the site and will fix the bug in #33.
I noted in the CSS that we'll need to update the hardcoded top for when the gov banner is opened (ideally calculated in JS).
Thanks @shawnbot for the help with this 🎉
=> Fix sticky nav bug

README.md
This updates the `npm build:package` command to `npm run build:package`.
=> Update README.md to correct usage of `npm`

README.md, package.json
This pull request adds in a `watch` command, as well as the `nswatch` module to the `package.json` file. This enables users to be able to use this command to automatically build and compile assets from the `web-design-standard` node module, as well as the specific assets for the docs/website itself.
=> Add `npm run watch` command + nswatch to package.json

_includes/download-buttons-design.html
The button for downloading the visual design assets are currently not downloading from the correct path. This pull request fixes this error.
=> Fix assets download button link.

package.json
The `watch` command currently builds the entire assets and site directory if changes are made to each of the folders. This pull requests breaks out those tasks to create incremental changes based on where the updates were made.
=> Adding incremental watch tasks for assets.

package.json
The `watch` command currently points to the incorrect directory for the WDS packaged styles, which therefore does not update the styles correctly when developing locally. This PR solves the crime!
=> Update css watch cmd to point to the correct styles dir for uswds.

README.md, _includes/download-buttons-design.html, circle.yml, config/gulp/build.js, config/gulp/sass.js, js/components/calculate-anchor-position.js, package.json
This fixes #50 and tidies up a couple of the other scripts to simplify the install + build + watch process:
=> Clean up npm scripts

config/gulp/doc-util.js, config/gulp/fonts.js, config/gulp/images.js, config/gulp/javascript.js, package.json
- Don't infer the task name from `__filename` in fonts, images, and javascript gulp configs.
- Reference `gutil.colors` as [chalk](https://www.npmjs.com/package/chalk) in doc-utils so it's clearer which terminal color API we're using.
=> Tidy gulp tasks

_config.yml, _includes/footer.html
This pull request updates the footer per the new copy outlined by @kategarklavs in #25. These updates were suggested per the repository split that happened a month ago.
It also adds in a link to easily point users to the page they are looking at to make any edits 🎉 We are also pointing to blobs instead of trees. You can read more about that here: https://git-scm.com/book/en/v2/Git-Internals-Git-Objects
Also, I found a bug in which we failed to update the `_config.yml` to point to the correct repo url. This PR fixes that!
=> Update footer with new copy and links

_components/accordions.md
Just a quick typo fix on the accordion documentation.
=> Typo fix, "it's" -> "its"

pages/about-our-work/component-maturity-scale.md
The following paragraph is on the [component maturity scale](https://standards.usa.gov/about-our-work/component-maturity-scale/) page:
> Our system is inspired by http://usajobs.github.io/design-system/getting-started/#maturity, who outline a maturity scale of their own in their Getting Started and who use these labels on the individual component page.
While GitHub is hyperlinking that URL above, it is *not* hyperlinked on the generated site, which requires users to manually copy and paste it into a separate browser tab.  However, it's also difficult to read as a raw URL, so I made it hyperlinked text and simplified the sentence a bit:
> Our system is inspired by the [USAJOBS Design System maturity scale](http://usajobs.github.io/design-system/getting-started/#maturity), which uses …
=> Fix un-hyperlinked URL in maturity scale page

_components/labels.md
This PR fixes a small typo in the `labels` documentation.
=> Copy edit: `over do` --> `overdo`

README.md, circle.yml, manifest-demo.yml
This pull request adds the ability to push any branch named `demo-[insert anything!]` to `standards-demo.cloud.gov`. The goal is to make it easy to deploy multiple branches to an instance without have to merge in.
@rogeruiz would <3 your expert cloud.gov eyes on this for a review!
=> Add ability to deploy any branch named demo-*

README.md
Tiny pull request to update the `README.md` to include install docs for `bundler`.
Refs https://github.com/18F/web-design-standards/issues/1287
=> Adding bundler install docs link to README.

README.md
Added some instructions that clarified that npm commands need to occur at the folder in terminal.
=> Updated the instruction to be clear that npm commands need to be ran at the folder level in terminal.

_data/milestones.yml, pages/about-our-work/product-roadmap.md
Solve to stop duplication of ID's on the product roadmap milestones. Also taking this opportunity to update our roadmap to reflect recent changes/updates to it.
Fixes https://github.com/18F/web-design-standards/issues/1458
=> Replace id reference and replace with {{ forloop.index.

_components/form-templates/02-address-form.md
Submitting this pull request to be merged into the work @shawnbot [has submitted](https://github.com/18F/web-design-standards-docs/pull/82) around adding Politespace as part of the docs site, and not the Standards themselves. 
It is also part of the work started in https://github.com/18F/web-design-standards/pull/1606 too.
=> Adding documentation around Politespace deprecation

pages/getting-started/developers.md
Includes expanded information on how to customize the WDS with examples and in depth information on what can be customized.
Most of this information was taken from https://github.com/18F/cg-style, as it's a heavily customized version of the WDS. 
Additional information can be found in individual commit messages.
Review needed: copy editing, stylistic, engineering
=> Add expanded customization section with examples

WHO_IS_USING_USWDS.md, pages/about-our-work/overview.md
I've included some analytics information from both google analytics(thanks @shawnbot and @tdlowden) and github (thanks @juliaelman) to the About Our Work page. 
Also, I've transferred the file WHO_IS_USING_USWDS from the main repo to this one.
=> Add analytics to About Our Work

_includes/code/examples/address-form.html, config/gulp/html.js
NOTE: This pull request is slated to merge into [the work @shawnbot has started](https://github.com/18F/web-design-standards-docs/pull/82) around isolating Politespace to the website only. The goal is to keep the automation work @rogeruiz developed for creating code samples, but also makes it so that we keep our example of implementing Politespace on our address form example.
:thinking: should we include a link to the JS file on this site to that makes Politespace work? I think a link to the code on Github may suffice.
=> Add html to use Politespace on address form example

_components/accordions.md
We received a note from Kyle Butts in regards to this issue (thank you for your contribution!) and how it is displaying incorrectly on the website. Here is what he wrote in his own words + a screenshot:
> On "18F/web-design-standards-docs/staging/_components/accordions.md”, there is a missing '</li>’ a little above where it says “Deprecated”. Causing a rendering error seen below!
=> Add closing </li> in accordion deprecation notes

package.json
This allows the package to be referenced via another project's `package.json` (via a github URL, not necessarily on npm). Without it, `npm` rejects the package.
⚠️ **I'm going to merge this without a review because I need it to fix the [brand site](/18F/brand).**
=> Add version field in package.json

Gemfile, Gemfile.lock, _config.yml, _plugins/jekyll_get.rb, pages/about-our-work/releases.md
This is the initial pull request for getting the release notes onto standards.usa.gov. A few things to note:
- It is using a modified version of ['jekyll_get`](https://github.com/18F/jekyll-get); we could probably remove the caching option, but wanted to work quickly for now and modify as we go.
- This does not make our release notes async. I decided to go this route b/c our release notes *should not* be modified once released. We have been developing a style and layout for them, which is pretty well nailed down at this point.
- There is no link to the release notes in any of the navigation yet. Talked with @bradnunnally and we are good to move forward without that path as part of this initial PR., since that work is currently in progress.
Below is a screenshot for reference:
=> Adding Github release notes to the website

_data/nav.yml
The "About our work" sidenav is currently busted [on staging](https://standards-staging.usa.gov/about-our-work/). This fixes it by removing the component maturity scale link, the corresponding page for which was removed in #124.
=> Nix component maturity scale link

_includes/code/accordion.html, _includes/code/demo.html, _includes/code/preview.html, _includes/code/syntax.html, config/gulp/html.js, css/styleguide.scss, package.json
This removes our dependency on [Prism](http://prismjs.com/) for generating syntax-highlighted versions of each of our component includes in the `gulp html` task and (ab)uses the `markdownify` template filter to [generate syntax blocks](https://github.com/18F/web-design-standards-docs/commit/4c8b1970b9f5a9e974c7a2aaab605153d9a1c64d). This change necessitated adding some new token class names to our CSS to match the ones generated by [rouge](http://rouge.jneen.net/) (Jekyll's default syntax highlighter) and [pygments](http://pygments.org/), on which its class names are based.
The new include for including a syntax block for a given component works like this:
```html
{% include code/syntax.html component='accordion' %}
```
=> Let Jekyll do syntax highlighting

_components/page-templates/template-docs.html, _components/page-templates/template-landing.html
This is a quick fix so that the page template styles are served correctly. Since the pages are [pulled in dynamically](https://github.com/18F/web-design-standards-docs/blob/staging/config/gulp/html.js) we need to add this static fix to make it work correctly.
Also, we should start thinking about how the [html](https://github.com/18F/web-design-standards/tree/staging/src/html) files are currently being used and if they are needed in the main repository.
=> Override page templates with static code.

.scss-lint.yml
So that we don't have to deal with seeing this anymore:
```
WARNING: [Bourbon] [Deprecation] `rem` is deprecated and will be removed in 5.0.0.
```
There is also an issue around changing `rem` to `em` on the main Standards repo in [this issue](https://github.com/18F/web-design-standards/issues/992).
=> Update exclude path for SCSS linting.

_data/nav.yml
Replacing the term `Overview` with `UI components` to be consistent with our other top level nav elements.
=> Change Overview to UI components in nav.yml

_includes/footer.html
This changes the footer image `src` attributes to reference the `/img/` path ("site" images, vs. USWDS), and removes a stray `.` from the chat.18f.gov URL.
=> Fix image paths and broken link href

css/styleguide.scss
We were using `display: inherit` which was causing some weird issues in regards to height of the navigation. Also, reset the site header background color on the header instead of on the div.
Screenshot of fix below:
=> Fix :focus on main navigation

_data/milestones.yml
The URL for our 1.0 launch goal pointed at an old github issue label. Now it's marked as "Done" and goes [here](https://github.com/18F/web-design-standards/labels/%5BRelease%5D%201.0).
=> Mark 1.0 launch goal as done and fix link

_includes/footer.html, css/styleguide.scss, pages/home.md
Fixes #147. I've added button-like links to the home page for our services:
Along the way I also tweaked the icon-in-a-button styles in both these email CTAs and the footer links. Before (left) vs. after (right):
=> Add home calls to action

pages/home.md
Our "Read more about this release" CTA link on the home page currently goes to the Product roadmap. This PR points it at our Releases page.
=> Change "read more" release link to ref Releases

css/styleguide.scss
We don't need the padding added b/c the `height` property is explicitly set.
I also removed the specific bold attribute for `.usa-current` since that is already the default value.
=> Remove padding from <a> in secondary site nav.

_layouts/landing.html
I was testing out the site this morning and noticed that that mobile nav was not appearing onClick. It looks like we forgot to add that snippet to the new landing page layout. This pull request resolves the issue.
=> Adding mobile nav into landing page layout.

pages/design-principles.md
The other four headings have one but this one did not.
=> Add trailing period to heading on principles page

pages/whats-new/product-roadmap.md
See [this comment](https://github.com/18F/web-design-standards/issues/1477#issuecomment-283094193) for reference on where this re-direct is broken. Tested locally and this works 🆗
=> Add redirect from roadmap from /about-our-work/.

_layouts/styleguide.html, css/styleguide.scss
This pull request includes a fix for the side navigation issue outlined in #185 - thanks @bruffridge!
@shawnbot is working on a fix in the Standards [here](https://github.com/18F/web-design-standards/issues/1745), which is an addition of a sticky navigation pattern to our system. This is a simple fix to resolve this bug while we flesh out this new pattern.
=> Fix for side navigation issue in Safari

pages/getting-started/developers.md
The docs were previously migrated, but this instruction had not been updated.
Resolves https://github.com/18F/web-design-standards-docs/issues/192
=> Fix location for HTML components

circle.yml, config/gulp/sass.js, manifest-demo.yml, manifest-staging.yml, manifest.yml, package.json
[😎  Preview on Federalist](https://federalist.fr.cloud.gov/preview/18f/web-design-standards-docs/federalist/)
This is a fix for all of the code-related tasks in #167:
=> Build on Federalist, nix deployment logic

js/form-disable.js, js/search.js, js/start.js
We originally had this disabled for only the search form component example. This pull request removes that specificity and makes it so that all form submissions are disabled for component examples.
=> Disable form submissions on all previews for components

_components/headers/basic-mega.html, _components/headers/basic.html, _components/headers/extended-mega.html, _components/headers/extended.html, _components/page-templates/template-docs.html, _components/page-templates/template-landing.html
back links on header demo pages were broken: https://standards.usa.gov/components/headers/basic/
=> fix demo pages back links

CONTRIBUTING.md
@shawnbot confirmed that he changed `develop` as the new default branch. This makes sense since we did the same thing on the [main repo](https://github.com/18F/web-design-standards) and for us to be consistent.
NOTE: I have deleted the `staging` branch as of submission of this pull request.
=> Update CONTRIBUTING.md w/develop as default branch.

_includes/post.html, _posts/2017-03-31-u-s-customs-and-border-patrol-case-study.md
This ensures that the post excerpts are always wrapped in a `<p>` on the news and updates listing, and moves the CBP post excerpt text into the body so that it can be processed as markdown.
=> Fix CBP post excerpt

_components/page-templates/template-docs.html, _components/page-templates/template-landing.html, _config.yml, _layouts/landing.html, _layouts/post.html, _layouts/styleguide.html
[👀 Preview on Federalist](https://federalist.fr.cloud.gov/preview/18f/web-design-standards-docs/patch-main-tabindex/)
This is a fix for 18F/web-design-standards#1788 that adds `tabindex="-1"` to `<main>` elements throughout the site, which ensures that IE11 (and earlier?) properly focuses the target of the skip navigation link.
=> Fix skip nav link focus issues in IE11

_components/typography/02-pairing-and-styles.md
The `h6`s here were inside the wrong container causing the margin-top to not apply.
=> Fixing broken formatting in typefaces docs

_includes/footer.html
Before (with `.usa-grid-full`, left) vs. after (`.usa-grid`):
=> Fix footer nav alignment

_components/typography/02-pairing-and-styles.md
Noticed "Body" was capitalized when it looks like it shouldn't have been.
=> Lowercase "body" in font pairing

pages/design-principles.html
This wraps up #274 by hiding the performance section. We should revive it and flesh out the text when we're ready to publish the rest of the performance guide pages.
=> Hide performance section on Design Principles

_components/typography/02-pairing-and-styles.md
👀  on [Federalist](https://federalist.fr.cloud.gov/preview/18f/web-design-standards-docs/typography-accordions/)
the typography examples were using the old accordion styles and weren't expanding properly as a result
=> upgrading accordions on typography page

_config.yml
moving the site version to 1.1.0. This updates the download link to point to the new version of the standards, among other things.
=> moving from 1.0.0 to 1.1.0

pages/performance/http2.md
Publish the reviewed HTTP/2 performance guide. Removes the other links in the performance section for pages that are not completed yet.
=> Publish http2 performance guide

_includes/download-buttons-design-retired.html, _includes/download-buttons-design.html, pages/getting-started/designers.md
fixes #288 
The text describing our retired design assets was confusing. 
[Preview on Federalist](https://federalist.fr.cloud.gov/preview/18f/web-design-standards-docs/retired-text/)
=> Updating retired design asset text

_data/implementations.yml
This updates the implementation info to link to @brockfanning's [Drupal project](https://www.drupal.org/project/uswds) instead of our unmaintained one. Brock, let us know if you'd like any of this info listed differently.
cc @fureigh ❤️
=> Link to better Drupal implementation

_includes/code/accordion.html, _includes/perf_example.html, css/styleguide.scss
This adds a class to the alerts used in the performance guide to ensure that they aren't wider than the paragraph content.
The class is on track to be added to the next version of the standards via 18F/web-design-standards#1925
=> adding paragraph width class to example alerts

_includes/perf_example.html, pages/performance/http2.md
removing the blockquote on one of the performance pages because we don't have styles for this in the standards so it just indents the paragraph
=> removing blockquote on http2 perf

_components/colors/01-palette.md
Instead of using `primary` use `$color-primary` to be more explicit about what the exact SASS variable is that is being used. This just involved adding `$color-` to the variable names that already existed.
=> Add explicit SASS variable names to color page

_components/page-templates/template-docs.html, _components/page-templates/template-landing.html, _layouts/landing.html, _layouts/post.html, _layouts/styleguide.html
When v1.1 was released, `tabindex="-1"` was added to many sections on the docs site to ensure the skipnav functionality was working correctly. This is no longer necessary given the javascript rewrites in 1.2 and will no longer create focus outlines around content when a user is using a mouse to navigate and clicking around on the content. 
(meaning this won't happen anymore)
=> removing tabindexes on content

pages/performance/research.md
Updated "as it" to "as is" and "team's" to "teams"
=> USWDS - Web performance research page: Fixed 2 minor content typos

CONTRIBUTING.md
Unfortunately, the existing CoC link 404's for public contributors due to
the fact that the 18F/code-of-conduct repository is currently private.
For more details on this issue, see:
https://github.com/18F/code-of-conduct/issues/4
This PR changes the link to point at 18F's publicly-visible copy of
the latest OGC-approved Code of Conduct, located at:
https://18f.gsa.gov/code-of-conduct/
This page also contains a link to the CoC repository, so that
contributors can still comment on or suggest changes to it
there (well, at least it's once made public again).
It's assumed that once the new CoC becomes approved by OGC, the
aforementioned copy will be updated as needed, so the
link will still be accurate.
=> Fix code of conduct URL in CONTRIBUTING.md.

_posts/2017-06-06-usda-case-study.md, package.json
This adds the USDA case study and upgrades the standards site to 1.2.1
Preview the post [here](https://federalist-proxy-staging.app.cloud.gov/preview/18f/web-design-standards-docs/usda-casestudy/whats-new/updates/2017/06/06/usda-case-study/)
=> Add USDA Case Study

_components/buttons.md, _includes/head.html, _includes/ie-polyfill-scripts.html, _includes/scripts.html, circle.yml, config/crawl.js, crawl.js, package.json, pages/getting-started/developers.md
This is a **work-in-progress** attempt to fix #269, or at least part of it.
1. Generate the site using `jekyll build`.  The `_site` folder should now contain the latest version of the site.
2. Run `npm run crawl`.  It will let you know if it found any errors.
I decided to use [`node-simplecrawler`](https://github.com/cgiffard/node-simplecrawler) because I've had experience using it in the past, and it seems reasonably fast and extensible.
Unlike https://github.com/18F/content-guide/pull/132, I decided not to go with [`html-proofer`](https://github.com/gjtorikian/html-proofer) because it's Ruby-based, and I don't have a ton of experience with Ruby. I also heard rumors that we might consider migrating this site from Jekyll to Hugo; if that happens, we would likely remove Ruby entirely from …
=> Add basic site crawler to find 404s, etc.

_includes/footer.html
When examining the new homepage design in #255 with a screen reader, I noticed that the decorative logos in the footer have alt text, which is distracting because they're decorative--the text of the links they're embedded in already provide enough context for visually impaired users to understand where following them will go.
=> Remove alt text for decorative images in footer

_config.yml, _plugins/incremental_regeneration_fixer.rb
On my system, Jekyll takes upwards of 8 seconds to rebuild itself without incremental regeneration, which is frustrating when I'm trying to rapidly iterate on content.  Enabling [incremental regeneration](https://jekyllrb.com/docs/configuration/#incremental-regeneration) reduces it to 2.5 seconds, which is bearable, but https://github.com/jekyll/jekyll/issues/4112 prevents some of our sections--notably "colors", "typography", "form controls", and "form templates"--from regenerating properly. Changes to these sections result in either no visible changes on the site, or raw markdown/liquid template source being present in the site.
* When trying to figure out what I could do to speed up build time, I enabled liquid profiling via Jekyll's `--profile` option and noticed that almost half our …
=> Add incremental_regeneration_fixer plugin

.gitignore, Gemfile, README.md, _config.yml, _plugins/jekyll_get.rb
This fixes #272 by authenticating with GitHub if the `GITHUB_ACCESS_TOKEN` environment variable is set.
* jekyll_get no longer fails *silently*; it now at least logs an error message.
* It turned out that the fetching of the release notes was throwing an exception, because it was trying to decode the `content` key which didn't exist. I added another configuration parameter to each source called `decode_content` which specifies whether to attempt this decoding or not.
* We now follow the lead of https://github.com/18F/jekyll-get/pull/16 and *always* use cached data if it's available. Unlike that PR, we also always cache our data, because there doesn't seem any reason not to (and making it optional just introduces more branching logic which complicates the code).
If we merge this PR, the …
=> Support GitHub access tokens and cache API results

_includes/navbar.html
When performing an accessibility audit of a different site with @nickbristow last week, he called out the site's logo link, which had an `aria-label` of just "Home", while the visual equivalent had the name of the site on it.  He said that the screen reader representation should be either the site name or the site name followed by "home".
When using a screen reader to examine the new home page in #255 I noticed that this site has the same issue.
Personally I prefer to follow the site name by "home" because it additionally identifies exactly *where* the link takes you, which is obvious from its visual placement on the page, but may not be obvious to users of ATs.
@nickbristow do you think this change makes sense, or did I misinterpret your guidance during our audit of that NSF site?
=> Set aria-label of site logo to "USWDS home"

_components/typography/03-typesetting.md, _components/typography/05-lists.md
Some of our documentation mentions actual `.scss` files, but the files no longer exist because the USWDS directory structure was refactored at some point after the docs were written. This fixes that.
=> Fix paths to SCSS files mentioned in docs.

Gemfile, Gemfile.lock, _plugins/uswds.rb, package.json, pages/getting-started/code-guidelines.md, pages/getting-started/showcase-all.md, pages/whats-new/releases.md, spec/uswds_spec.rb
This fixes #324 by adding two new liquid filters:
* `absolutify_links` converts all relative links into absolute links with the given base URL. This is used in `code-guidelines.md` and `showcase-all.md`.
* `remove_relative_links` simply un-hyperlinks any relative links. We're using it in `releases.md` because GitHub is doing special things to hyperlink relative links that aren't easy for us to reproduce, so it's easier to just un-hyperlink the handful of relative links that exist on the page.
It also adds an rspec-based test suite to the project. Aside from ensuring code quality, it was also *much* faster for me to rapidly iterate on the new liquid filters using TDD than it was to wait on the 2.5 second incremental build time every time I changed code. It also allowed me to work around …
=> Fix relative links in external markdown

_components/form-controls/06-validation.md, _components/form-controls/form-controls.md, _components/form-templates/04-password-reset-form.md, _includes/code/components/password-reset.html, _includes/code/components/validation.html
~~**This PR is currently against #334 because I needed that PR's code to quickly iterate on this PR. However, if absolutely necessary, we can merge this code without merging #334.**~~
This attempts to fix https://github.com/18F/web-design-standards/issues/1432.
> ![validation](https://user-images.githubusercontent.com/124687/27869460-05f2e078-616e-11e7-9e72-e0e4f81254fe.png)
* I wanted to link to some kind of documentation on regular expressions because I'm not sure all our readers will necessarily know what they are.  For now I've linked to https://regexone.com/, but we can either link to a different site or remove the link altogether.
* I also removed the mention of `.js-validate_password` in the code, fixing this repo's side of https://github.com/18F/web-design-standards/issues/1998.
=> Document validator component (take 2)

config/gulp/sass.js
This fixes #322. For now we just fail on errors, not warnings; since warnings are already raised by scss-lint, I figure we can start with errors, and then move to warnings if we want, once we clean them up first.
=> Use scss-lint's failReporter

_includes/code/components/date-input.html
Example for Date Input used elements that contained multiple `class` attributes. Removed second `class` attribute that appeared to reference a non-existent CSS selector.
=> [Website] - [Date Input Example]: Remove extra class attribute from date input example

README.md, circle.yml, config/crawl.js, config/run-axe.js, config/static-server.js, package.json
Fixes #326.
This runs [axe-core](https://github.com/dequelabs/axe-core) on a few pages of the standards during CI and `npm test` runs. In future PRs we can add support for running it on more pages.
A successful run looks something like this:
> ![2017-07-12_15-43-34](https://user-images.githubusercontent.com/124687/28136780-fc177cc0-6718-11e7-8803-750b651de81f.png)
It requires that Chrome/Chromium v59 or higher be installed on the host system. I decided on [headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) because:
* It's maintained by the Google Chrome team, so it's likely to be very well-maintained going forward. Possibly even moreso than Phantom; I vaguely recall seeing a Tweet from Ariya Hidayat a while back saying that Phantom was going to be …
=> Run aXe on a few pages during CI

_data/implementations.yml
This adds [django-uswds-forms](http://django-uswds-forms.readthedocs.io/en/latest/) on the [implementations](https://standards.usa.gov/getting-started/implementations/) page.
django-uswds-forms is a package I wrote a few months ago that encapsulates a bunch of logic we added to CALC in order to make it possible to render [Django `Form` objects](https://docs.djangoproject.com/en/1.11/ref/forms/api/) with Standards-based widgets. This essentially means that developers don't have to write any custom HTML or CSS to get the USWDS user experience.
It's actually completely orthogonal to the other Django package we list, [django-designstandards](https://github.com/department-of-veterans-affairs/django-designstandards): all that package does is add the USWDS JS and CSS to a Django project's …
=> List 18F/django-uswds-forms in implementations.yml

pages/home.md
The current title on the homepage was leftover from the 1.0 launch and being manually updated for new releases. Since we aren't currently announcing a milestone release this is a proposed text change for a more generic homepage title.
=> Change Homepage Title

_config.yml, _data/implementations.yml, _plugins/redcarpet_extender.rb, config/crawl.js, package.json, pages/getting-started/implementations.md
This is just like #358 but takes an alternative approach to fixing duplicate ids caused by the kinds of header TOC issues described in https://github.com/18F/web-design-standards-docs/pull/358#issuecomment-316686935. Instead of using HTML in the markdown for duplicate headers, we subclass Redcarpet to provide our own custom id-collision algorithm.
=> Find duplicate "id" attributes when crawling site (Redcarpet subclassing approach)

_plugins/incremental_regeneration_fixer.rb
Rather than `Error:  undefined method '[]' for nil:NilClass` or `Error:  undefined method 'each' for nil:NilClass`, print out a message saying the config is missing, or allow through an empty config.
=> [Website] Nicer error message/behaviour if no configuration.

_components/buttons.md, _config.yml, _layouts/styleguide.html, css/styleguide.scss, package.json, pages/ui-components/overview.html
Adds a "view in component library" link to the pages on the docs site (just buttons for now)
@toolness is there anyway I could use the code you wrote for embedding fractal code samples to populate that URL field?
=> initial fractal link on Buttons component

_components/typography/02-pairing-and-styles.md
- Changes all pairings to be just 4 faces.
- Removes some fonts from certain pairings.
- Updates performance language around each to reflect less faces.
- Changes bullet points to numbered lists.
Requires https://github.com/18F/web-design-standards/pull/2107 for some of the typography styling changes.
=> Typography updates

package.json
This updates the version of uswds the `master` branch uses to 1.3.1, which was just released in https://github.com/18F/web-design-standards/pull/2119, so that we provide the download link for that version instead of the old one.
Fixes #385.
=> Release USWDS 1.3.1

_data/implementations.yml
Updating version in the docs for the uswds-jekyll theme to 1.3.1
More info here: https://github.com/18F/uswds-jekyll/releases/tag/v1.3.1
=> Updating the uswds-jekyll theme to 1.3.1

pages/getting-started/developers.md
This states / should state that the standards should support IE9 and up until a major release, and then will only support browsers above 2% usage on analytics.gov.
This could potentially be worded in a way where it would not need to be updated in the future, such as after a major release or after browser support changes on analytics.gov. If that's better, we can rewrite it as such.
Fixes https://github.com/18F/web-design-standards/issues/2071
=> Update section on browser support.

_includes/banner.html
This just cherry-picks 4823a39 into the `master` branch so we can get it deployed ASAP and resolve the concerns raised by https://github.com/18F/web-design-standards-docs/issues/315#issuecomment-331022425.
I'm doing this as a hotfix because actually releasing what's currently on the `develop` branch will require also releasing a new version of USWDS (which will take a little while longer to do).
=> Hotfix for fixing gov banner on master branch

_components/sidenav.md
fixes #389 
removes reference to headers being under development as they have been released.
=> Update the lead on the sidenav docs

css/styleguide.scss
- Removes extra spacing on mobile (Fixes #311)
- Removes inline-block display setting from h2's so margins collapse
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/fix-site-typography)
Check whether or not we want/need the additional custom spacing on h2's and revisit how they should be applied.
=> Fix site typography bugs

_layouts/base.html, css/styleguide.scss, pages/home.md
The media block code was applied to the whole site and not scoped to the intended homepage graphic list. This fixes that. Related to: https://github.com/18F/web-design-standards/issues/2141.
Also, fixes https://github.com/18F/web-design-standards/issues/2176.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/fix-media_block)
- Removes antialiasing font smoothing from the homepage hero.
- Adjusts the media block styling so they're side-by-side. 
- Adds the ability to add a `class: class-name` into page frontmatter to add a class to the body, which will have a `page-*` appended to it.
=> Fix media block

_components/buttons.md, _layouts/styleguide.html, pages/ui-components/overview.html
Fixes #411, #412.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/fix-components-url)
**Note**: I don't know why we only have "View in the component library" link for only buttons and not the other components. It should be consistent.
=> Fix broken links

_components/buttons.md
This should not specify an anchor link, but a regular link.
=> Fix content error in buttons docs

_includes/nav/link-item.html
This fixes the issue with anchor generation in the release notes, but I'm not sure it doesn't break something somewhere else. I don't now how this key replace is used in other sections.
A better solution might be to change how the `h2`s on this page generate their anchors, but idk how to do this on a case-by-case basis. It looks like Redcarpet is creating anchor slugs for heds by removing `.`s whereas `slugify` converts them to `-`s.
- - -
Note: Run `npm test` failed to run.
```
npm ERR! uswds-docs@1.3.0 axe: `node config/run-axe.js`
npm ERR! Exit status 1
``
Dunno what that means.
=> Fix sidenav anchor links in releases

pages/whats-new/product-roadmap.md
Fixes 18F/web-design-standards#1459 
This fixes the lingering accessibility issues from an AccessLint scan that was done a while back. Most of these had been addressed already but the following were still present (if I interpreted them correctly) 
```
'http://localhost:4000/about-our-work/product-roadmap/ | critical | ARIA attributes must conform to valid values | ["#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(1) > .usa-label.label-done", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(2) > .usa-label.label-in-progress", "#main-content > .styleguide-content.usa-content > section:nth-of-type(1) > ul > li:nth-of-type(3) > .usa-label.label-in-progress", "#main-content > …
```
=> Accessibility fixes

pages/getting-started/implementations.md
Fixes #351.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/remove-version-implementations/getting-started/implementations/)
=> Remove version from implementations

_posts/2017-11-08-USAGov-case-study.md
This adds the USA.gov case study to the News and Updates section of the site. 
Fixes 18F/web-design-standards#2102
=> Add USA.Gov case study

pages/getting-started/developers.md
Updates the browser support text to be clearer and more explicit. 
Related: https://github.com/18F/web-design-standards/issues/2251
Will be added to [CONTRIBUTING.md](https://github.com/18F/web-design-standards/blob/develop/CONTRIBUTING.md) in the main repo, or at least a link to this text if we'd like it in one place / a single source of truth.
=> Update browser support text

pages/home.md
Updates the content on the Services section on the homepage to accurately reflect 18F's offerings. 
Moved the "Why should you work with us?" content into an accordion bc it was taking up too much space.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/update-services-copy)
Fixes #461.
=> Update Services content on homepage

_data/implementations.yml
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/add-wp-theme/getting-started/implementations/)
Resolves https://github.com/18F/web-design-standards-docs/issues/464.
=> Add "The Standards" WordPress theme

css/styleguide.scss, pages/home.md
Updates the homepage hero copy to more accurately reflect the product vision. Also, adjusts hero spacing to match Sketch designs.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/update-hero-copy)
Resolves #467.
=> Update homepage hero copy

_config.yml, _includes/meta.html, pages/home.md
- Improves homepage meta title
- Adds missing meta description on homepage
- Adds site-wide description in config file
- Fixes #473 issue where the entire page content was being shown in the meta description on component pages by ensuring `page.excerpt` is only used on posts; now component pages use the `lead` text.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/fix-meta-tag-issues)
=> Fix meta tag bugs

pages/getting-started/developers.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/fix-broken-links)
Fixes: #460.
=> Fix broken links to 18F's Front End Guide in "For developers > CSS" section

RELEASE.md
Adds release file which links to docs release section in the main `web-design-standards` repo.
Fixes #386, closes https://github.com/18F/web-design-standards/issues/2124.
=> Add release file

_data/milestones.yml, css/styleguide.scss, pages/whats-new/product-roadmap.md
- Updates the product roadmap with our new roadmap items 
- Removes old milestones which were not relevant to the current work and muddled the page
- Adds in a `To-do` label for items not started yet, and swaps label color so `In progress` is yellow and `To-do` is blue.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/update-roadmap/whats-new/product-roadmap/)
Closes https://github.com/18F/web-design-standards/issues/2205
=> Update product roadmap with 2018 roadmap

_components/typography/03-typesetting.md
Fixes some inaccuracies in the text, removes out of date instruction about `usa-content-list` (now max width is applied to lists by default), updates the path of the SCSS to use the dist path.
Fixes #242.
=> Update typography documentation

pages/whats-new/product-roadmap.md
Move the link to the roadmap list item text instead and off of the label.
This makes it more clear that you can click the individual roadmap item to see the details. 
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/sw-link-roadmap-items/whats-new/product-roadmap/)
=> Link roadmap list item text to GitHub issues 

css/styleguide.scss, pages/whats-new/product-roadmap.md
This removes unnecessary ARIA attributes from the roadmap list. It also removes hover states from labels, as there is no longer functionality that pseudostyling would support.
👀 [preview link](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/dw-fix-roadmap-links/whats-new/product-roadmap/)
=> Strip vestigial ARIA and remove pseudostyling from labels in roadmap

package-lock.json, package.json
Resolves a security vulnerability from an old jQuery dependency.
=> Update jQuery to 3.3.1

_components/search-bar.md
The lead text on the [search bar](https://designsystem.digital.gov/components/search-bar/) says:
>**A block** that allows users to search for specific content if they know what search terms to use or can’t find desired content in the main navigation
but "a block" doesn't seem to make much sense, so I changed it to box, as in a search box. See https://www.nngroup.com/articles/search-visible-and-simple/ Another option is "an element."
=> Update search bar lead text

README.md, _plugins/uswds_version.rb, spec/uswds_version_spec.rb
This adds instructions on how to update the USWDS version to `README.md`.
It's not quite a `RELEASE.md` (#386) but it helps get us there.  I figure it's also useful to put in the `README.md` since devs will want to know how to do it outside of the context of a release, e.g. to get the latest fractal component HTML from a specific USWDS commit.
When writing the docs and trying out the `npm install` commands, I noticed that npm prefixes the dependency name with the `github:` protocol, and it also seems to lowercase the organization name. So I updated `_plugins/uswds_version.rb` to support that.
=> Add instructions on how to update the USWDS version

pages/getting-started/developers.md
The [current documentation](https://designsystem.digital.gov/getting-started/developers/#installation) links to a likely outdated path: `css/lib/uswds.min.css` rather than the actual file at `css/uswds.min.css`. Similar for `js/uswds.min.js`.
=> Fix documented path to css and js

pages/getting-started/developers.md
The `Accessibility` link on in the navigation on this page is pointing to the incorrect ID.
`https://designsystem.digital.gov/getting-started/developers/#notes-on-accessibility`
I updated the page-navigation to link to the existing ID `#accessibility`
I also added in the navigation item to link to **"Browser Support"**, since that is also an `h2` on the page. I figured it should also be available in the navigation, yes?
https://designsystem.digital.gov/getting-started/developers/#browser-support
=> Updated page nav to point to correct IDs / Anchors

pages/getting-started/developers.md
Dependent on the release that includes https://github.com/uswds/uswds/pull/2365.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/document-sass-path-overrides/getting-started/developers/#customization-and-theming)
Would like a review of the content and location of the content.
Fixes #354.
=> Document base asset path and image + font asset paths

pages/whats-new/overview.md
Looks like various markdown files were reorganized in the https://github.com/uswds/uswds repository.
=> Fix link to WHO_IS_USING_USWDS.md

pages/whats-new/overview.md
Updates the blog link to the site's blog (News and updates) instead of the 18F blog. Added a sentence that links to the 18F blog for older posts and historical preservation.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-blog-link/whats-new/)
=> Update blog link to site blog on "What's new" page

css/styleguide.scss, pages/getting-started/developers.md
Uses the more explicit install instructions from the USWDS README: https://github.com/uswds/uswds/blob/develop/README.md
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-dev-instructions/getting-started/developers/)
Fixes #528.
=> Update developer install instructions

_data/implementations.yml, pages/getting-started/implementations.md
Since we have multiple implementations of the same distribution methods (e.g. multiple WordPress themes) we need a way to identify them and ensure our sidebar navigation works.
=> Add name to Implementations page

Gemfile, Gemfile.lock, _config.yml, pages/getting-started/developers.md
The docs site uses the Sass files directly from the uswds npm package - those Sass files do not include any browser prefixes by default, so it's up to developers to incorporate that functionality within their own build process. In the case of the docs site, we're already using Jekyll so this adds the `octopress-autoprefixer` gem to add the prefixes.
Fixes https://github.com/uswds/uswds-site/issues/523
Before: [Preview](https://designsystem.digital.gov/components/form-controls/#dropdown)
After: [Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/bh-dropdown-fix/components/form-controls/#dropdown)
=> Add autoprefixer to Jekyll

pages/getting-started/developers.md
Update side navigation to include anchor links to the newly included README content.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/bh-add-anchor-links/getting-started/developers/)
=> Add anchor links to developer page

Gemfile, Gemfile.lock
The `open-uri-cached` has a vulnerability in it without any resolution path (and none in sight, it hasn't been updated in over 6 years 😬). This is used in conjunction with the Fractal plugin which grabs the components and displays them within the site. It adds some additional caching, but I think the way the plugin is configured it may not actually be adding much value so I've removed it.
=> Remove vulnerable gemfile package

_components/typography/02-pairing-and-styles.md
Documents the correct font weight:
Fixes part of #566:
>Source Sans Pro headings, merriweather body.
>The text "Lead paragraph" is listed as being 400 weight, but is actually displayed at 300 weight.
=> Document correct font weight for "Lead paragraph"

config/run-axe.js
This improves error reporting when aXe tests fail due to failed network requests during page load (see e.g. #563).
To test this out manually, you'll have to make one of the pages visited by aXe 404.  A quick way to do this is to make the following change to `_includes/head.html`:
```diff
--- a/_includes/head.html
+++ b/_includes/head.html
@@ -35,4 +35,4 @@
-<link rel="stylesheet" href="{{ site.baseurl }}/css/styleguide.css">
+<link rel="stylesheet" href="{{ site.baseurl }}/css/styleguideLOL.css">
```
Then re-run `npm run build` and run `npm run axe` and you should see the following error output:
```
Static file server is listening at http://542d59734268:41077.
Chrome is debuggable on http://chrome:9222.
Running aXe on:
/page-templates/docs/ OK
/page-templates/landing/ OK
/ A network …
```
=> Display URL of network requests that fail in aXe tests.

_data/uswds_tokens.yml, css/_uswds-project-settings.scss, package-lock.json, package.json
Dependent on https://github.com/uswds/uswds/pull/2566
- - -
Add new colors and values from USWDS
- Use correct hex values
- Assure all grade 50 colors are AA against white and black
- Sync theme colors with current USWDS defaults
- Add more darker and lighter variants for some theme families
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-update-colors)
=> Implement new colors and color values

_components/utilities/text-styles.md
Add note to font weight and tabular numerals sections saying certain utilities are not included in the default set.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/update-innactive-sections/text-styles/)
Refs #575
=> Update inactive sections to say they're not included

config/gulp/sass.js
We copied and compiled the styleguide css to `assets/styleguide.css`, but the only reference to this file points to `css/styleguide.css`. 
Fixes #335
=> [build] don't copy assets twice

css/_project-custom.scss
Removes the custom focus on the site that was creating two focus colors.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/remove-custom-focus)
=> Remove custom focus

pages/performance/how.md
I noticed the first two ordered list links at the top of this page don't link to their respective h2s; this change corrects the ids for the href values in the frontmatter.
=> USWDS - Docs: Fixes frontmatter href fragment ids to fix links

_includes/banner.html, css/styleguide.scss, package-lock.json
When we restructured the site's govt banner to be semantically correct, we lost some styles for its alignment bc of how it was structured. This fixes that.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/fix-gov-banner-alignment)
Fixes #598.
=> Fix gov banner alignment

_includes/download-buttons.html, pages/documentation/getting-started/download.html
Removes an infinite loop redirect from our download page
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-dl-redirect/)
=> Fix download link redirect

config/gulp/sass.js
Since we aren't relying on jeykll to compile our sass files for us, have the gulp task copy the compiled`styleguide.css` file into `_site`
=> Copy compiled css file to _site

_components/utilities/margin-and-padding.md
Uses the proper pin utilities to build the padding examples.
Fixes #596
=> Fix padding examples

.scss-lint.yml, css/_project-custom.scss, css/_uswds-project-settings.scss, css/_uswds-project-utilities-settings.scss, package-lock.json
Fixes additional stylelint warnings in `css/_project-custom.scss`
The issues left in `css/_project-custom.scss` are related to ColorKeyword and ColorVariable that were caused by this: `@include u-text(white);`
```
[19:41:05] _project-custom.scss:2041 [W] ColorKeyword: Color `white` should be written in hexadecimal form as `#ffffff`
[19:41:05] _project-custom.scss:2041 [W] ColorVariable: Color literals like `white` should only be used in variable declarations; they should be referred to via variable everywhere else.
```
What should we do about these @thisisdano? We probably have a lot of these in the main repo, or will.
---
In other files, there are more stylelint warnings, which tells me we're not linting these files in the uswds main repo bc they were copied from it:
```
Comment: Use …
```
=> Fix remaining stylelint issues

.circleci/config.yml
Apparently, circle doesn't recognize custom variables in the `.Environment` object, so removing that dependency for now :(
=> Remove refs to .Environment in circle config

.circleci/config.yml, package-lock.json
The circle cache is now only rebuilding with changes to `package-lock.json` and I've been getting a lot of circle errors on the `v2` branch because of this. This PR should result in less caching but fewer errors. Wee shall see!
=> Use a more specific circle cache to avoid cache-based errors

_includes/footer.html
Looks like there was a name change when TTS merged into FAS: https://www.gsa.gov/about-us/newsroom/news-releases/gsa-merges-technology-and-acquisition
May want to bring this into the 1.x site as well.
=> Fix footer typo to make TTS plural

css/_uswds-theme-custom-styles.scss
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-scope-bg-color/page-templates/docs/)
- - -
Uses a white background for all `body.layout-demo` pages.
- - -
Fixes #714
=> Use white background for demo pages

_components/form-controls/01-text-input.md
Changes an instance of `the the` to `the`.
* Content review needed: copy editing
=> [Website] - Form controls: Fix typo in 'Text input' section

_components/utilities/flex.md
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-fix-flex-code/utilities/flex/#utility-flex-align)
Updates the code samples for `flex-align` and `flex-justify` to show these utilities on the parent element.
- - -
Fixes https://github.com/uswds/uswds/issues/2913
=> Use correct code samples for flex utilities

_includes/banner.html, package.json, pages/home.md
[Preview 🇺🇸](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-check-favicon/)
- Updated favicon
- Updated banner to reference flag image
- Updated homepage title to get full acronym in small tabs
=> Use updated favicon and homepage title on our site

_components/utilities/border.md, _components/utilities/color.md, _components/utilities/text-styles.md, _data/tokens/color.yml, css/settings/_uswds-theme-utilities.scss, pages/design-tokens/color/theme-tokens.md
This one was one of those little quirks of having a documentation site that does not share the same defaults as its product — similar to the issue of not rendering Source Sans Pro in our component previews.
Since `uswds-site` color settings don't match USWDS defaults, we had a situation where the docs were outputting the default hex code for color tokens/utilities (since that value is set in site data) but were displaying the `uswds-site`-specific defaults in the examples (since the site settings determine the output of the theme utilities and the examples use utilities for styling).
One solution might be to use the USWDS defaults on our site. Ha! That would be too consistent.
For this one, I used custom utility values to make a set of color utilities that output the USWDS defaults — like …
=> Display proper default theme colors

pages/design-tokens/color/system-tokens.md
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-blue-cool-vivid/design-tokens/color/system-tokens/#blue-cool) :sparkles:
We omitted the `blue-cool-vivid` variants on the system tokens page. This reinstates them.
- - -
Fixes #743 
Thanks @bet4a!
=> Add blue-cool-vivid to system color tokens page

_components/utilities/font-size-and-family.md, _data/tokens/typesetting/size.yml, pages/design-tokens/typesetting/font-size.md
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-font-size/utilities/font-size-and-family/) ✨ 
This should update the docs to use the proper USWDS defaults and output the proper utility into the example to display the proper size.
Fixes uswds/uswds-site#745.
=> Fix font-size output in docs

_components/page-templates/page-templates.html, _includes/meta.html
- Remove post excerpt part from meta 
- fix closing section tag on page templates.
- ensures markdown in site lead renders correctly in the meta tag
Will have to re-add post excerpt in subsequent PR as it was breaking the site cc @jeremyzilar.
=> Remove post excerpt part from meta

_data/migration.yml, pages/documentation/getting-started/migration.md
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-update-migration/documentation/migration/) ✨ 
- use the data for the `footer` section
- add migration data for `usa-sitenav__item`
- - -
Fixes #759 
Fixes https://github.com/uswds/uswds-site/issues/758
=> Update migration data

_components/headers/headers.html, _components/typography/typography.md
Within the _Components_ section of the USWDS site at https://v2.designsystem.digital.gov/, some of the second-level navigation links on the sidebar do not lead to anything:
* _Components_ → _Header_ → _Extended header with megamenu_
* _Components_ → _Typography_ → _Typesetting with USWDS_
* _Components_ → _Typography_ → _Included typefaces_
I tested all of the navigation links in the Components section and these were the only broken ones. I did not test any of the navigation links in other sections of the website.
=> USWDS v2 - Sidebar nav links: Fix a few missing/broken IDs

css/settings/_uswds-theme-color.scss
Updates the settings file to align the hover color with what's on uswds that was updated in uswds/uswds/pull/3023.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/mb-update-link-hover/)
=> Change link hover to primary-dark

_includes/migration-table.html
Current red text used on Migration page is too light to pass a11y requirements. `secondary-vivid` seemed the closest to `secondary` although`secondary-dark` would work and may be easier on the eyes.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/mb-update-red-text/documentation/migration/)
Fixes #761.
=> Update deprecated text to secondary-vivid on Migration page

_includes/migration-table-mixins.html
Missed this section
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/mb-update-red-text-mixins/documentation/migration/)
Related #765 #761.
=> Use secondary-vivid for red text on the Migration page (Mixins section)

_config.yml
Using the `master` branch will use the latest release.
[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/mb-v2-update-readme-ref/documentation/developers/)
=> Change ref in install-readme from release-2.0 to master on v2 site

_layouts/landing.html
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/v2-add-v1-banner/) ✨ 
- - -
This adds a banner to the top of the home page, pointing v1.x users to the new v1 documentation site: [v1.designsystem.digital.gov](https://v1.designsystem.digital.gov)
**Note: Only merge once v1.designsystem.digital.gov resolves properly.**
=> Add v1 docs banner to home page

_includes/head.html
This change puts in a temporary meta refresh redirect for `https://v2.designsystem.digital.gov/`.
**This change is being made to the v1 branch.**
- If the reader is on any page on `https://v2.designsystem.digital.gov/`, they will be redirected to the same page/path on `https://designsystem.digital.gov/`.
- If the reader is on any page on `https://v1.designsystem.digital.gov/`, nothing should happen. They should remain on the v1 site.
=> adding a temporary redirect

package-lock.json, package.json
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/use-develop-2.0.3/documentation/developers/)
- - -
- This updates the USWDS package to the Github develop branch, not the `2.0.3` package
- - -
Fixes https://github.com/uswds/uswds-site/issues/778 (Sorry this took so long! 😬)
=> Use develop branch for documentation

pages/design-tokens/z-index.md
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/fix-z-index-utils/design-tokens/z-index/#using-z-index-tokens) :sparkles:
The **Using z-index tokens** section of the z-index token documentation was incorrect. The proper values should be:
**utility:** `.z-[token]`
**mixin:** `@include u-z([token])`
**function:** `z-index([token])` and `z([token])`
- - -
Fixes #790
=> Fix z-index token documentation

_includes/meta.html
[USA Gov blog post](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/fix-busted-metadata/whats-new/updates/2017/11/08/USAGov-case-study/)
[Code.gov blog post](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/fix-busted-metadata/whats-new/updates/2017/07/24/code-gov-case-study/)
- - -
Escape any description to prevent including markup-breaking code in the meta description field.
Fixes #796
=> Strip and escape any description metadata

_data/tokens/special.yml
Just something minor I noticed where it appears that the `full_viewport_height` and `full_viewport_width` tokens are swapped (`100vw` vs `100vh`). This affects the documentation for `.height-viewport` and `.maxh-viewport` (https://designsystem.digital.gov/utilities/height-and-width/#height).
> For some reason `.width-viewport` and `.maxw-viewport` are not available in the documentation
=> [Full Viewport Height / Width] Utility values are swapped in the documentation

Gemfile, Gemfile.lock, _components/utilities/font-size-and-family.md
[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/uswds/uswds-site/dw-fix-data/utilities/font-size-and-family/)
A "where" filter bug in Jekyll 4.0 was causing some data filtering lookups to fail. I'll link the gem to this fix branch temporarily, until we get an official release of Jekyll 4.1
Bug: https://github.com/jekyll/jekyll/issues/7820
Fix branch: https://github.com/jekyll/jekyll/pull/7821
Fixes #818
=> Use jekyll dev branch to fix "where" filter bug

css/_uswds-theme-custom-styles.scss
The `display: block` change regressed the nav, so we'll revert to the old change for now!
=> Revert inline-block work for now

css/_uswds-theme-custom-styles.scss
https://github.com/uswds/uswds-site/issues/863
Added `min-width: 0` to `.usagov-search-autocomplete` to prevent
search from being cutoff.
---
Additional notes `npm test` error'd out. Investigating.
=> [USWDS-Site] - [Mobile Search]: Fix search being cutoff on Firefox mobile.

pages/documentation/getting-started/showcase-all.md
I think folks will have a hard time finding the page to edit otherwise.
=> use direct link to editing showcase page

_components/headers/headers.html
The [basic header](https://designsystem.digital.gov/components/header/#basic) "Guidance" accordion doesn't collapse.
The `aria-controls` for the basic header controls the basic header with megamenu instead of the basic header. Simple typo fix.
=> [Website] - [UI component]: Fixed typo for guidance accordion on header docs

_config.yml
Federalist seems to have updated their URL structure, so I updated our preview URL to match.
Fixes #872
=> Update preview link

_components/accordions.md, _includes/code/components/accordion.html
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-fix-accordion-page/components/accordion/) →
- Fixes `hidden` accessibility guidance
- Adds multiselectable examples, code, and implementation guidance
- Adds default-to-open implementation guidance
Fixes #879
=> Improve accordion guidance

_data/variables.yml
The documentation site listed incorrect variable names for some typography settings:
This updates those with the correct variables.
=> Fix incorrect typography settings var names

_config.yml
USER STORY
As the design system, I want external search engines to easily locate me.
REQUIREMENT
Update page title from `United States Web Design System` to say `U.S. Web Design System (USWDS)` in the config.yml file. Update the description to use the current tagline.
JUSTIFICATION
Use acronym since it is the way we talk about the program
Improve organic search
Improve readability, scannability by reducing USWDS as modifier
=> Update site name and description

css/_uswds-theme-custom-styles.scss, pages/whats-new/product-roadmap.md
This adds the USWDS 2020 Roadmap with the current status of each roadmap item.
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-update-roadmap/about/product-roadmap/)→ 
Fixes #905
=> Add 2020 Roadmap

_includes/code/components/alerts.html, package-lock.json, package.json
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-add-slim-alert/components/alert/)→ 
This adds the `slim` and `no-icon` variants into the preview and code sections of the Alert page.
**Note:** This is in draft pending merge of https://github.com/uswds/uswds/pull/3388
=> Add slim and no-icon alerts

_components/utilities/border.md, _components/utilities/color.md, _components/utilities/display.md, _components/utilities/flex.md, _components/utilities/font-size-and-family.md, _components/utilities/height-and-width.md, _components/utilities/list-reset.md, _components/utilities/margin-and-padding.md, _components/utilities/paragraph-styles.md, _components/utilities/shadow.md, _components/utilities/text-styles.md, _includes/utilities/utility-title-bar.html, package-lock.json, package.json
There were some instances where the utility title bar on our website wasn't showing the accurate options available to the utility (ie, not showing that a utility was responsive when it actually was). This simplifies the code to use fewer custom overrides, and check the data against the defaults in `uswds`.
For instance [this update](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-fix-utility-title-bar/utilities/color/) now shows that `color` outputs only `hover` variants by default and [the current site](https://designsystem.digital.gov/utilities/color/) indicates that `color` is also responsive by default, which it is not.
This also updates jquery to `3.5.0` to fix a Snyk warning
=> Fix output of utility title bars

_data/nav.yml, pages/about/history.md, pages/about/overview.md
**Description**
As a user, I want to learn about the history of USWDS within the context of its mission and vision.
**Requirement**
Move content from [/About/History](https://designsystem.digital.gov/about/history/) to [/About](https://designsystem.digital.gov/about/)
**Supporting Data**
Simplify content within About section. Make content more accessible.
=> Integrate history content on about landing page

_data/tokens/color.yml
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-fix-color-tokens/design-tokens/color/system-tokens/) → 
There are a couple color tokens out of sync with their proper token values. 
Red 60v `#b51d09` → `#b50909`
Red 70v `#8b1303` → `#8b0a03`
Note: This PR is a companion to https://github.com/uswds/uswds/pull/3455. Merge that PR first. Then, rebuild this PR to check that we also see the correct values for the following:
Indigo cool 60v → `#3e4ded`
Indigo cool 70v → `#222fbf`
Indigo cool 80v → `#1b2b85`
When both PR's are merged, this fixes https://github.com/uswds/uswds/issues/3398
=> Fix out-of-sync color tokens

.browserslistrc
Part of https://github.com/uswds/uswds/issues/3450
Adds `not dead` setting to `browserslistrc`.
=> Update browserslistrc: Add 'not dead'.

_includes/banner.html, _includes/footer.html, pages/design-tokens/overview.md, pages/design-tokens/typesetting/overview.md, pages/documentation/maturity-model.md, pages/documentation/overview.md
Adding `role="img"` to SVG's withtin `<img />` so voiceover on Safari
properly identifies them as images instead of group.
https://github.com/uswds/uswds/issues/3316
=> USWDS-3316: Add img role to meaningful SVG images.

pages/design-tokens/typesetting/font-weight.md
Changes the name of the font-weight function in the docs from `weight()` to `font-weight()`.
Fixes #989.
* Relevant code in USWDS: https://github.com/uswds/uswds/blob/v2.7.1/src/stylesheets/core/_functions.scss#L1467-L1483
=> USWDS - Docs: Fix font-weight function docs

_components/data-visualizations.md
For this issue: https://github.com/uswds/uswds-site/issues/992
I've changed the font-sizing in the svg's to use pixels AND be set within the svg `<style>` section. These seemed to fix how the font-size scales when font size settings are are changed in the browser preferences.
**Steps to follow**
1. Pull this branch and and run it locally
2. Open Chrome
3. Change the font size to "Large" or "Very Large" in Preferences -> Appearance -> Font size
4. Verify text is not getting cut off
**Screen shots**
These were take using the Very Large font size setting in Chrome. As you can see, it's not cut off.
=> [ISSUE 992] Fix svg font size handling

_config.yml, _includes/banner.html, _includes/code/components/banner.html, _includes/download-buttons.html, _layouts/landing.html, css/_uswds-theme-custom-styles.scss, css/settings/_uswds-theme-components.scss, pages/documentation/getting-started/download.html
- Update references and links to 2.8.0
- Use new banner text. (Note that we can't style it with settings without affecting our component examples, thus the complicated overrides...)
=> Update references and banner to 2.8.0

CONTRIBUTING.md, README.md
This is the final step of updating the `uswds-site` repo to a default brach of `main` as planned in https://github.com/uswds/uswds-team/issues/23
Generally following the steps outlined [here](http://www.kapwing.com/blog/how-to-rename-your-master-branch-to-main-in-git/).
=> Use `main` instead of `master` for default branch refs

_includes/component-preview-link.html
Fixes the preview link include so it outputs the proper link to federalist previews of complex components and templates.
[Templates](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-update-preview-links/page-templates/) →
[Headers](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-update-preview-links/components/header/) →
=> Fix data and url structure in preview include

_components/utilities/flex.md, package-lock.json, package.json
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-add-align-self-docs/utilities/flex/#utility-flex-align-self) → 
This adds the documentation for the new `align-self` utilites/mixins from https://github.com/uswds/uswds/pull/3621
**Adds align-self utilities and mixins.** Now we have native utilities and mixins for the `align-self` flex property. Similar to the `.flex-align` utilities and mixins, `.flex-align-self` affects the flex alignment of a single item in a flex container.
=> Add align-self docs

_components/buttons.md, _includes/code/components/buttons.html, package-lock.json
Despite the inaccurate name of this branch, this PR adds the accent-warm button variant into the docs!
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-add-accent-cool-docs/components/button/) →
=> Add accent-warm button docs

_includes/banner.html
[Homepage →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-banner-a11y/)
You should be able to open banner and verify `alt` descriptions are gone.
Part of uswds/uswds#3689
The images are decorative so removing `alt`.
=> USWDS - Banner: remove alt from decorative images.

_components/card.md
[Card component settings →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jeffffeffff-je-card-inset-variant-documentation/components/card/#component-variants)
Documentation for a card variant `user-card__media--inset` was referred to in documentation as `usa-card__media--indent` incorrectly. This PR updates that documentation to use the proper name of the class as implemented on the actual component.
Resolves issue 1039: https://github.com/uswds/uswds-site/issues/1039
=> USWDS-Site - Documentation: Fix documentation reference of usa-card__media--indent class to usa-card__media--inset.

_components/form-controls/05-date-picker.md
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-update-date-input-links/components/form-controls/#date-picker) → 
Fixes https://github.com/uswds/uswds/issues/3878
Fixes the link to date-input in the `When to consider something else` section of the date picker component.
=> Fix mangled link to date-input

_components/footer/footer.md, _components/icon-list/icon-list.md, _components/input-prefix-suffix/input-prefix-suffix.md, _components/site-alert/site-alert.md, _components/text-input/text-input.md, css/_uswds-theme-custom-styles.scss, package-lock.json
- Added missing `footer` variants
- Added missing `site-alert` variants
- Use proper type size variants for `icon-list`
- Use proper size variants for `input` and `input-group` (prefix and suffix)
=> Some docs bugfixes related to 2.11.0

_includes/code/preview.html, css/_uswds-theme-custom-styles.scss
Closes #1184. Hides overflow from code, but still shows it on component preview.
Added a new class to component preview section. Works in IE11.
=> USWDS - Components: Only show overflow on preview accordion.

.snyk, css/_uswds-theme-custom-styles.scss, package-lock.json, package.json
closes https://github.com/uswds/uswds-site/issues/1189
because our accordion component applies borders to all `.usa-accordion__content` we were getting undesired results when previewing our accordion component in these nested previews. This updates so that our accordions appear as expected, borderless, with border, borderless + multi-select
=> USWDS-SITE | overrides nested accordion content borders

_includes/code/preview.html
This issue is related to Ticket #22141 on Zendesk. The links on the screenshots were pointing to a non-existent component because it was missing the `demoLink` variable like the button below it.
To test this code:
- Go to [Templates ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-template-preview-fix/templates/) section and select a template
- Click on template screenshot
- Go back and click on button below
Both should take you to the right destination.
=> USWDS - Templates: Fix template screenshots link.

_components/icon-list/icon-list.md
Fixes #1209 by removing `{{ site.baseurl }}` from the links inside variants.
```yml
variants:
- variant: "`.usa-icon-list--[color]`"
description: Colors listed on the [color utilities]({{ site.baseurl }}/utilities/color) page.
```
Was causing issues in `_includes/settings-table-flex.html:23` . The variable value was being turned into a string and resulting in a broken URL ex: `%7B%7B%20site.baseurl%20%7D%7D/utilities/color`.
---
=> USWDS - Icon list: use relative URL in variants.

_templates/form-templates/address/guidance/accessibility.md, _templates/form-templates/name/guidance/accessibility.md, _templates/form-templates/password-reset/guidance/accessibility.md, _templates/form-templates/sign-in/guidance/accessibility.md
- [Address form guidance](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-fix-templates-typo/templates/form-templates/address-form/)
- [Name form](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-fix-templates-typo/templates/form-templates/name-form/)
- [Password reset](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-fix-templates-typo/templates/form-templates/password-reset-form/#accessibility-password-reset-form)
- [Sign in form](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-fix-templates-typo/templates/form-templates/sign-in-form/#sign-in-form-guidance)
Fixes typo in template links. …
=> USWDS - Forms: Fix typo in USWDS template links

_includes/accessibility.html
[
Preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-describedby-guidance/components/form/#known-issues-with-screen-readers)
There's now partial support for `aria-describedby` on Voiceover. This updates the form guidance on `describedby` to reflect that.
Related to [issue #4347](https://github.com/uswds/uswds/issues/4347) in USWDS. Based on changes from [USWDS PR #4414](https://github.com/uswds/uswds/pull/4414).
This affects the components:
- Date range
- Date range picker
=> Date picker: Update date picker a11y guidance for voiceover.

pages/design-tokens/overview.md
Removed "elements like" after colon in first sentence of intro paragraph because it was redundant.
=> Improving copy clarity in intro paragraph

pages/ui-components/overview.md
[Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/copyedit-round-1-components/components/overview/)
Added hyphen for grammatical accuracy.
Deleted "Type below" to make language more accessible and inclusive.
Deleted "about" for concision.
=> Copyedit round 1 Components

Gemfile.lock, _components/link/guidance/usability-should.md, _config.yml, _includes/footer.html, _next/05-get-involved.md, _posts/2018-02-22-nsf-seed-fund.md, _posts/2018-03-22-dds-case-study.md, _posts/2019-04-08-introducing-uswds-2-0.md, files/next/README.md, pages/404.md, pages/about/community.md, pages/about/key-benefits.md, pages/documentation/getting-started-designers/designers/overview.md, pages/documentation/getting-started-developers/resources.md, pages/documentation/implementations.md, pages/documentation/maturity-model.md, pages/documentation/showcase-all.md, pages/whats-new/overview.md
Created a site-wide variable for the uswds support email address, updated the value to match the new gsa.gov address, and replaced all existing references. 
old address: uswds@support.digitalgov.gov 
new address: uswds@gsa.gov
Closes #1451
=> USWDS support email address - update across site

_data/settings.yml, _data/tokens/spacing.yml, _utilities/layout-grid.md, css/old settings/_uswds-project-settings.scss, css/settings/_uswds-theme-utilities.scss
Doc's reflect correct `tablet-lg` value. Closes https://github.com/uswds/uswds/issues/4549.
---
=> Correct tablet-lg references in docs

_includes/navbar.html, _includes/touchpoint-survey-script.html
Closes #1485
[Preview Link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-icon-markup-update/)
=> USWDS-site - Header: update icon markup on header search

Gemfile.lock, _config.yml, _plugins/fractal_component.rb, config/gulp/build.js, package-lock.json, package.json, pages/documentation/maturity-model.md
We updated USWDS Fractal to render to the `/_site` directory instead of `/build`. This PR updates the build and component scripts to use the new directory.
=> Load components from the proper Fractal source

package-lock.json, package.json
Build from develop branch to incorporate new USWDS features. Specifically, this allows us to access the explicit `@frctl/mandelbrot` dependency that's causing our circle builds to fail.
=> Use uswds@develop branch

_components/combo-box/combo-box.md, _components/date-input/date-input.md, _components/date-picker/date-picker.md, _components/date-range-picker/date-range-picker.md, _components/file-input/file-input.md, _components/input-prefix-suffix/input-prefix-suffix.md, _components/radio-buttons/radio-buttons.md, _components/text-input/text-input.md
Resolves #1468 
Switches all `@include usa-form-controls` to `@include form-controls`. This affects the following component pages:
- Combo-box
- Date-input
- Date-picker
- Date-range-picker
- file-input
- Input-prefix-suffix
- Radio-buttons
- Text-input
**Before**
**After**
=> USWDS-Site - Form Component Markdown: Switched package name from usa-form-controls to form-controls

_config.yml
Update the site uswds_version to 3.0. 
This update will be reflected in the header download button as well as in Phase 1 of `Getting started for developers` guide.
:warning: We will need to confirm that the download button works once USWDS 3.0 is released :warning: 
[Preview link ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-v3-header-button/) 
Closes https://github.com/uswds/uswds-site/issues/1524
=> V3 - update uswds_version in header button

pages/documentation/migration-V3.md
[3.0 Migration page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-migrate-3.0/documentation/migration/)
Convert accordions to markdown and standardize formatting for new/old code samples.
Tasks completed:
- Make accordion content easier to understand/edit
- Convert accordions to use as much markdown as possible 
- Add comments to clarify accordion sections
- Standardize text for code changes to be "Old code"/"New code"
- :warning: Inconsistent styling/tags - Had difficulty preserving `<h6>` styles on items inside an ordered list. 
- Standardize presentation of code blocks to use `.site-terminal` styles
=> 3.0 Migration guide - convert accordion to markdown

_config.yml, _includes/footer.html
This PR adds a `touchpoints` key to `_config.yml` that controls whether touchpoints js will be output on the site. I've set it to `false`. Perhaps later this might be connected to an environment variable, and values in `_config.yml` may be set by Federalist for specific branches. 
But, for now, this functionally disables touchpoints until we can troubleshoot what's causing problems between it and out pa11y tests.
=> Add Touchpoints key to site data

package-lock.json, package.json
Removes `snyk protect` from package.json. Updates to Snyk have caused this warning to popup:
```bash
⚠ WARNING: Snyk protect was removed at 31 March 2022.
Please use '@snyk/protect' package instead: https://updates.snyk.io/snyk-wizard-and-snyk-protect-removal-224137 
```
Work was done in snyk and github settings to get the same functionality using the new standard.
The `snyk wizard` command is also deprecated and we'll now need to use `snyk ignore`. See documentation [here →](https://docs.snyk.io/snyk-cli/fix-vulnerabilities-from-the-cli/ignore-vulnerabilities-using-snyk-cli)
=> Remove snyk protect from develop

_components/link/guidance/additional-information.md, _components/link/guidance/usability-must.md
Resolves #1513 
Links to OMB Memo M-17-06 were resulting in a 404 page. This was corrected by updating the anchors to the correct URL: [https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2017/m-17-06.pdf](https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2017/m-17-06.pdf)
I found four instances of the broken link, all of which were on the [link component page](https://designsystem.digital.gov/components/link/)
The old URL was `https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf`
=> USWDS-Site: Update OMB Memo M-17-06 links

pages/documentation/settings.md
Update the settings page to use the new USWDS 3.0 conventions
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-settings-page/documentation/settings/) →
=> Use sass module syntax and USWDS 3.0 conventions throughout

_posts/2022-04-28-introducing-uswds-3-0.md
Adds a note to the intro about our new organization scope with an explicit instruction about how to install the new package
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-add-install-note/whats-new/updates/2022/04/28/introducing-uswds-3-0/) →
=> Add note about organization scope and installing

.circleci/config.yml
This PR attempts to improve CircleCI builds to be faster and more reliable. 
⚠️We still need to update to pa11y 3 to avoid those jekyll page crashing issues that have been bothering us.
The previous `build` job is now split into 3 separate "phases". It uses the `persist_to_workspace` and `attach_workspace` features to re-use the same build per workflow.
1. **Install dependencies ⬇️**
1. Install Ruby deps
1. Install Node deps 
1. **Build the site 🏗️**
1. Jekyll Build
1. Build assets 
1. **Run tests 🧪**
1. Run ruby unit tests & HTML proofer
1. Test pa11y desktop
3. Test pa11y mobile
This changes to workflow so the sub-steps can run at the same time, speeding up builds/rebuilds, and clarity on what exactly failed.
**Before**
**After**
Before you hit Submit, make sure you’ve done whichever of …
=> Circleci: Create install, build, and test jobs for faster builds

pages/documentation/getting-started-developers/phase-two.md
Closes https://github.com/uswds/uswds-site/issues/1590
Preview link: [Getting started for developers - Phase 2 ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-compilation-settings/documentation/getting-started/developers/phase-two-compile/)
From the related issue: "The settings file example in docs would generate a warning for insufficient contrast, if the warnings hadn't been disabled. Since it's typical for people getting started to copy/paste examples, it would be better to have an initial file that didn't disable warnings and had contrasting colors."
Updated the example compile settings in Phase 2 of the Getting Started for Developers guide to include values that compile without warnings. 
To test, open a sample project and use the …
=> USWDS-Site - Compile: Update settings example

_utilities/display.md
Closes: https://github.com/uswds/uswds-site/issues/1498
Preview link: [Display utility page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-display-none/utilities/display/)
The display utility page does not have an clear presentation of `.display-none`. Because this class hides the display of the element, users do not know that the utility class exists unless they look at the code snippet. 
Restructuring the section allows for a display that suggests the utility class and property exist, and that it is behaving as expected when applied to an example. 
=> USWDS-Site - Display utility: Visually demonstrate display-none

_data/packages.yml
I noticed a dependency for usa-radio was "usa-legent".  Its possible it should be "usa-legend"
=> Fix possible typo in packages.yml

_components/date-picker/date-picker.md, _components/date-range-picker/date-range-picker.md
Part 1/2 to close https://github.com/uswds/uswds/issues/4247.
Preview link: [Date range picker page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-date-range-picker/components/date-range-picker/)
Our documentation provided incorrect information about where to add `data-min-date` and `data-max-date` attributes to the date range picker component. Additionally, we do not have have stories to demonstrate how these properties work on date range picker. 
This PR is part 1 of a two-step solution to close https://github.com/uswds/uswds/issues/4247. 
- Part 1: USWDS-Site - Update component instructions to point to the correct attribute elements
- Part 2: USWDS - Create stories for the date range picker component to demonstrate correct placement …
=> USWDS-Site - Date picker and date range picker: update props tables

_config.yml, package-lock.json, package.json
Use USWDS `3.0.2` and update references to `3.0.2`
[Preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/use-3.0.2/) →
=> Use USWDS 3.0.2 and update refs

_components/text-input/guidance/when-to-use.md
-Response to a report that said the "calendar picker" was confusing wording, presumably since we typically use "date picker" language
-I updated the language from "calendar picker" to "date picker"
-I hyperlinked to the "date picker" page for further clarity
=> Update when-to-use for unclear text

.github/workflows/add-to-project.yml
Related to issue https://github.com/uswds/uswds-team/issues/176
Add the Github [add-to-project](https://github.com/marketplace/actions/add-to-github-projects-beta) action to our repos so that newly opened issues are automatically added to our project board. 
⚠️ This PR uses a 7-day PAT (issued on 06/27) in the encrypted secret for testing purposes. We will re-evaluate the use of this action after that 7 day period is up. If we decide to keep this action, we will update the PAT to one with a longer life.
This action works successfully on my[ personal test repo](https://github.com/amyleadem/issue-template/blob/main/.github/workflows/add-to-project.yml). To test on this repo: 
1. First [open a new issue](https://github.com/amyleadem/issue-template/issues/new/choose)
1. See that the new issue …
=> USWDS-Site: Add Github action add-to-project

.github/workflows/add-to-project.yml
Purpose: 
The GitHub action [add-to-project](https://github.com/marketplace/actions/add-to-github-projects-beta) updated this morning and now has new requirements for the PAT used in the `github-token`.
1. Update the `github-token` used to one with correct PAT scope
1. Pin the version of the GitHub action to current version to prevent future breaks
=> USWDS-Site: Update add-to-project GitHub action

.snyk
Closes https://github.com/uswds/uswds-site/issues/1712
`npx snyk test` was throwing errors related to sub-dependencies inside Gulp 4.0.2. 
Update the snyk policy to ignore these alerts for 30 days. 
---
=> USWDS-Site: Repair snyk errors

pages/documentation/getting-started-developers/phase-two.md, pages/documentation/migration-V3.md, pages/documentation/settings.md
Closes https://github.com/uswds/uswds-site/issues/1690
Preview links:
- [Migrating to 3.0](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-config-error/documentation/migration/#format-and-load-your-uswds-settings)
- [Settings](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-config-error/documentation/settings/)
Update documentation surrounding the configuration of `@use "uswds-core" with()` to include a note about error handling. If configured improperly, users can receive an error message that might point them in the wrong direction. Adding a note to clarify what to do when receiving this error should help users get unstuck and successfully compile their .scss files. 
```
Error: This …
```
=> USWDS-Site: Error writeup - uswds-core config

_components/accordion/guidance/implementation.md
Update accordion documentation to use the correct multi-select attribute.
Our current accordion documentation tells users to add the `aria-multiselectable="true"` attribute to trigger a multi-select accordion group, but the attribute is actually `data-allow-multiple`. 
Correcting this will make sure that users are able to successfully trigger the multi-select variant, while also preventing accessibility errors. 
Closes https://github.com/uswds/uswds/issues/4865
Preview link: [Accordion component page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-accordion-multi/components/accordion/#using-the-accordion-)
1. Open the [accordion twig file in USWDS](https://github.com/uswds/uswds/blob/develop/packages/usa-accordion/src/usa-accordion.twig#L1 …
=> USWDS-Site- accordion: Update multiselectable docs 

_components/accordion/guidance/accessibility.md, _components/button-group/guidance/variants/segmented/accessibility.md, _components/link/guidance/usability-must.md, _components/modal/guidance/implementation.md, _components/search/guidance/accessibility.md, _config.yml, _includes/banner.html, _includes/code/accordion.html, _includes/code/preview.html, _includes/nav/page-collapsible.html, _includes/navbar.html, _utilities/clearfix.md, _utilities/display.md, _utilities/flex.md, package-lock.json, package.json, pages/documentation/migration-V3.md, pages/documentation/sample-contract-language.md
Updates USWDS to 3.1.0. Closes #1736.
[Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/use-3.1.0/)
- Adds `type="button"` to non-submit buttons
- Added attribute to guidance pages
- Site banner
- Site accordions
---
=> USWDS - Site: Use USWDS 3.1.0

.snyk
Closes https://github.com/uswds/uswds-site/issues/1742
`npx snyk test` was throwing errors related to sub-dependencies inside Gulp 4.0.2. 
Update the snyk policy to ignore these alerts for 30 days. 
---
=> USWDS-Site: Update snyk ignore

pages/documentation/getting-started-developers/phase-two.md
Updated typo that pointed users to `index.html` when it should be `index.scss`.
Closes #1711 
Preview link: [Phase 2 - Compile](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-phase2-typo/documentation/getting-started/developers/phase-two-compile/#step-1-set-up-your-projects-sass-entry-point)
---
=> USWDS-Site - Fix typo in phase 2 dev guide 

pages/documentation/migration-V3.md
**Added clarity for users migrating from USWDS 1 to USWDS.** We included a note at the top of the 3.0 Migration guide explaining that users updating from 1.x should first update to version 2 via the 2.0 Migration guide. 
Closes #1733 
Related discussion: https://github.com/uswds/uswds/discussions/4895
Preview link: [Migrating to 3.0](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-migration-1x/documentation/migration/)
Users should be able to easily find all the needed instructions for upgrading any version of USWDS to version 3. However, users who are upgrading from 1.x do not have clear instructions for all the steps they need to take to get to 3.x. 
Providing instructions to 1.x users that they must first follow instructions in the 2.0 …
=> USWDS-Site: Instructions for migrating from USWDS 1.x

_data/settings.yml, _data/settings/components/footer.yml
This PR adds $theme-footer-max-width to the documentation. Closes #1696.
Seen on pages
- [documentation/settings/#footer](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-footer-docs/documentation/settings/#footer)
- [components/footer/#component-settings-footer](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-footer-docs/components/footer/#component-settings-footer)
---
=> Docs: add $theme-footer-max-width variable

.snyk
Closes https://github.com/uswds/uswds-site/issues/1772
`npx snyk test` was throwing errors related to sub-dependencies inside Gulp 4.0.2. 
Update the snyk policy to ignore these alerts for 30 days. 
=> USWDS-Site: Update synk ignore

_components/site-alert/guidance/accessibility.md
Added instruction for using descriptive ARIA labels to ensure that assistive technology users can find and understand the site alert from the landmarks menu.
Additionally, added instruction for using ARIA roles to announce content changes to assistive technology users.
Closes https://github.com/uswds/uswds/issues/4589
Preview link: [Site alert accessibility section](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-site-alert-aria/components/site-alert/#accessibility-site-alert)
Site alerts should be included in the page landmarks so that users of assistive technologies can more easily find site alert content on the page. However, if a user excludes the ARIA label, the site alert will not appear in the landmarks menu. 
Additionally, some …
=> USWDS-Site - Site alert: Add aria-label information to accessibility docs

_components/alert/guidance/accessibility.md
Updated accessibility documentation for the alert component to give clearer instructions for adding the appropriate ARIA role. 
Closes https://github.com/uswds/uswds/issues/3832
Preview link: [Alert component page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-alert-aria-update/components/alert/#accessibility-alert)
It is important that users are informed of the attributes the alert component needs to make it accessible. However, our current documentation provides information on only some of the available roles and does not give a clear indication of exactly how and where these attributes should be used.
ARIA provides several `role` attributes that can be added to the alert component to make content more readily available to users of …
=> USWDS-Site - Alert: Update ARIA role guidance

.circleci/config.yml, package.json, pages/documentation/guidance/performance/why.md
Created a separate Jekyll build step to ensure `_site/` builds properly for HTMLProofer test. Fixes #1799.
CircleCI was returning 5 failures, three of them false positives.
```bash
Running 3 checks (Images, Links, Scripts) in ["./_site"] on *.html files...
Checking 648 external links
Checking 853 internal links
Ran on 282 files!
* At ./_site/getting-started/showcase/all/index.html:2611:
External link https://lincs.ed.gov/ failed with something very wrong.
It's possible libcurl couldn't connect to the server, or perhaps the request timed out.
Sometimes, making too many requests at once also breaks things. (status code 0)
* At ./_site/getting-started/showcase/all/index.html:2673:
External link https://www.flra.gov/ failed …
```
=> USWDS - CI: HTMLProofer fix

css/custom-styles/_site-header.scss, js/calculate-anchor-position.js
**Fixed inner links in sidenav.** Subnav links now smooth scroll to correct page section.  Closes #1793.
There's JS to smoothscroll sidenav links to relevant page sections _with_ the sticky nav offset included. Needed to update the `calculate-anchor-position.js` script to point to correct class. Now the offset is calculated correctly.
```diff
-  //start with the height of the header
-  topOffset = $(".usa-nav__primary--desktop").first().outerHeight();
+   //start with the height of the sticky nav
+  topOffset = $(".site-nav.sticky").first().outerHeight();
```
Issue was introduced in main nav update to recommended USWDS markup [PR #1730]. The desktop class for sticky nav `.site-nav-secondary → .site-nav` was changed to more accurately describe it.
```diff
- <nav class="site-nav-secondary …
```
=> USWDS - Main nav: Update offset header class

pages/documentation/getting-started-developers/phase-two.md
Restructured the content in Phase 2 of the Getting Started for Developers guide to add clarity. 
Closes https://github.com/uswds/uswds-site/issues/1708
Recommend releasing this update with the settings page update in PR https://github.com/uswds/uswds-site/pull/1755
Preview link: [Phase 2 Compile ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-add-table-context/documentation/getting-started/developers/phase-two-compile/)
The guide for compiling USWDS Sass should give clear instructions for both users who want to use `uswds-compile` to create their Sass, and those who want to manage their own Sass compilation. However, the current page creates a single set of steps for both processes. Additionally, the instructions for `uswds-compile` can …
=> USWDS-Site: Phase two compile updates

pages/about/community.md
This PR makes some small edits to our community page:
- Use the new DG Community Guidelines name. (It's no longer "Etiquette Guidelines")
- Connect DGCG and TTS CoC into one sentence. (Since participating in the community means following both the DG Guidelines and the TTS Code of Conduct.)
- Clarify that community participation is voluntary. (Be clear that folks who join our community are free _not_ to join our community.)
- Use the new URL for the DG Community Guidelines, since the old URL forwards to it.
=> Simplify and update community guidelines

_components/data-visualizations/data-visualizations.md, package-lock.json, package.json, pages/whats-new/overview.md
Resolved a couple of errors that appeared in `html-proofer` and after the test upgrade to pa11y-ci v3.0 (This upgrade has not been included in this PR). 
Closes [#1860](https://github.com/uswds/uswds-site/issues/1860)
Preview links:
- [Data Visualizations - Bar charts](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-fix-pa11y3-errors/components/data-visualizations/#bar-charts)
- [What's New ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-fix-pa11y3-errors/about/whats-new/)
Tests to upgrade to pa11y-ci 3 revealed a new valid aria error:
html-proofer returned the error:
```
* At …
```
=> USWDS-Site: Resolve pa11y and html-proofer errors

_components/sidenav/sidenav.md, _components/site-alert/site-alert.md, _components/step-indicator/step-indicator.md, _components/summary-box/summary-box.md, _components/table/table.md, _components/tag/tag.md, _components/text-input/text-input.md, _components/time-picker/time-picker.md, _components/tooltip/tooltip.md, _components/typography/typography.md, _components/validation/validation.md, _data/changelogs/side-navigation.yml, _data/changelogs/site-alert.yml, _data/changelogs/step-indicator.yml, _data/changelogs/summary-box.yml, _data/changelogs/table.yml, _data/changelogs/tag.yml, _data/changelogs/text-input.yml, _data/changelogs/time-picker.yml, _data/changelogs/tooltip.yml, _data/changelogs/typography.yml, _data/changelogs/validation.yml, _includes/changelog-table.html
**Added data for group 3 components.** This adds release data to component changelogs from release `3.2.0 → 2.11.0`. Closes #1864.
**Group 3 components**
- [Side navigation](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-group-3/components/side-navigation/)
- [Site alert](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-group-3/components/site-alert/)
- [Step indicator](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-group-3/components/step-indicator/)
- [Summary box](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-group-3 …
=> USWDS-Site - Changelog: Add group 3 changelog items

_includes/changelog-table.html, css/_uswds-theme-custom-styles.scss, package-lock.json
Edited the changelog table content presentation so that all content is displayed at medium widths.
Closes #1869 
Preview link: [Alert changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-table-redo/components/alert/#alert-changelog)
At tablet and desktop widths, the table contents can become constrained, overlap, and can break the borders of the table. 
At `tablet` and `desktop` widths, the table will change in the following ways:
- The `date` column will be hidden
- The `Breaking` tag will move inline with the description
Note: This PR builds on the proposed solution that was already committed into `al-changelog-main` in [d38522c](https://github.com/uswds/uswds-site/pull/1789/commits/d38522c1f8e9a6029d75c8ffbf5c3152 …
=> USWDS-Site - Changelog: Fix table presentation in tablet widths

_data/changelogs/memorable-date.yml
This adds a changelog entry to Memorable Date. We updated the month entry to a `select` from a numeric `input` because our pattern testing showed that a `select` was clearer and reduced confusion. 
Note that this is not a breaking change even though it affects styles and markup. We rewrote the styles to be backward compatible with the old markup
=> Add changelog entry for Memorable Date updates

_components/search/guidance/accessibility.md
Removed `type="button"` from the button example in the accessibility guidance.
It is not necessary to include the type in the example because the meaning can be derived without it. Plus, our component code shows `type="submit"`. 
Closes #1903 
Preview link: Search page
---
=> USWDS-Site - Search: Remove button type

_components/header/header.html
I noticed the usertesting.com link under Further Reading for the Header component was no longer redirecting to the actual post, but to the blog home page instead. It looks like they've redone their url structure, so I updated the page with the current link for that post.
This closes #1381 
=> [uswds-site] - [Header documentation]: Fix external blog post link to usertesting.com

.snyk
Closes #1924
`npx snyk test` was throwing errors related to sub-dependencies of `gulp-sourcemaps@3.0.0`
More details: [Circle CI failure report](https://app.circleci.com/pipelines/github/uswds/uswds-site/4380/workflows/850e896e-9237-47d0-ba34-812c9adf8899/jobs/14887)
Update the snyk policy to ignore these alerts for 30 days. 
Ran the following in the command line:
```
npx snyk ignore --id="SNYK-JS-DECODEURICOMPONENT-3149970" --reason="No available upgrade or patch"
```
=> USWDS-Site: Update snyk ignore (November, round 2)

config/gulp/images.js, gulpfile.js, package-lock.json, package.json
Removed the `gulp-webp` devDependency. `gulp-webp` is not necessary and was introducing vulnerabilities.
Closes #1803 
**Before**
20 vulnerabilities (5 moderate, 15 high)
**After**
7 high severity vulnerabilities
---
=> Remove gulp-webp

pages/design-tokens/typesetting/font-family.md
Added some possible additional edits for @bonnieAcameron's Custom web fonts guidance PR (#1905). This PR includes edits to both the "Customizing family tokens" and "Setting custom fonts" sections.
Preview link: [Font family page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-custom-font-guidance/design-tokens/typesetting/font-family/)
- Removed "Option 2" since it looked like that content is covered by the "Customizing family tokens" section earlier on the page.
- Updated copy in "Customizing family tokens" to differentiate between tokens and settings
- Renamed "Setting custom fonts" to "Creating a custom typeface token" and restructured copy a tiny bit.
- Changed the values in the `$theme-font-role-` settings example from …
=> USWDS-Site - Font family: Custom fonts content edits

pages/about/contribute.md
This issue affects the Contribute page as described in #1935 . I've removed the section "What's on this page" and all of the anchor links beneath it. 
This is a result of a recent change to uswds-site that added the side-nav component to our documentation. The end result for the Contribute page was that there were 3 navigations on a single document. This change will lighten the visual load and make the remaining page navigation more meaningful. 
=> Deleted the what's on this page navigation in the body of the page

_includes/download-buttons-design.html
**Update design assets links to v2.6.0.** I've updated the design assets in the `uswds-for-designers` repo: https://github.com/uswds/uswds-for-designers/releases/tag/v2.6.0. This PR updates the link to the release ZIP.
Both asset links should point to https://github.com/uswds/uswds-for-designers/releases/download/v2.6.0/uswds-for-designers-v2.6.0.zip — there are only two links for analytics tracking purposes. 
=> Update design assets links to v2.6.0

pages/about/key-benefits.md, pages/about/website-policies-and-notices.md
This issue removes duplicative in-page navigation that repeats what is automatically pulled in to the right-side page navigation. There may be others on the site, but these were found in #1942 . 
Pages updated: 
- [Key benefits](https://designsystem.digital.gov/about/key-benefits/)
- [Website policies and notices](https://designsystem.digital.gov/about/website-policies-notices/)
=> Remove duplicative page navigation

_data/implementations.yml
Per #1877, this adds the Vue USWDS project to the implementations page.
=> Add Vue USWDS to implementations page

_layouts/landing.html
Removes top tasks survey banner on homepage. Closes #2019.
=> Homepage: Remove survey banner

_data/changelogs/component-alert.yml, _data/changelogs/component-banner.yml, _data/changelogs/component-date-picker.yml, _data/changelogs/component-footer.yml, _data/changelogs/component-header.yml, _data/changelogs/component-in-page-navigation.yml, _data/changelogs/component-link.yml, _data/changelogs/component-modal.yml, _data/changelogs/component-site-alert.yml, _data/changelogs/component-step-indicator.yml, _data/changelogs/docs-implementations.yml, _data/changelogs/utilities.yml
Added 3.4.0 updates to changelogs.
Guidance changelog updates:
- Implementations #1714 
- Date picker guidance #1695
- Utilities
Component updates:
- Banner
- Header
- In-page nav
- Alert & Site Alert
- Header
- Footer
- Link
- Modal
- Step indicator
[3.4.0 Release notes ](https://github.com/uswds/uswds/releases/tag/v3.4.0)
=> Update changelog with 3.4.0 release notes

_data/changelogs/component-header.yml
Updated the changelog entry for [ USWDS PR #5008](https://github.com/uswds/uswds/pull/5008) so that it warns users of a  potential breaking change.
The break was originally flagged in Slack: https://gsa-tts.slack.com/archives/C3F14AHSQ/p1680208085858799
I have updated the PR description with the same information. We should also consider updating the 3.4.1 release notes. 
Closes #2051 
Preview link: [Header changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-header-changelog-5008/components/header/#changelog)
- Confirm that information accurately reflects and resolves the potential break
- Confirm there are no issues with grammar or punctuation
=> USWDS-Site - Header: Update changelog for #5008 with note about possible break

.circleci/config.yml, .snyk, package-lock.json, package.json
Added an override to long standing `glob-parent` dependency. We no longer have to re-add to snyk ignore every month.
Related [documentation [gDrive 🔒]](https://docs.google.com/document/d/1RX6uYky-P37jysuBy6LEBhuMCQlMAvHU0mRJUow345o/edit#) for this process.
Closes #2068.
Preview link:
[Cloud Pages preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-glob-parent/)
_There haven't been an visual updates. Still worth a peak and make sure everything looks good._
1. Snyk keeps reporting gulp vulnerability.
2. We have to manually override and ignore every month.
3. This patches the dependency so we use the more secure version.
1. Run clean `npm install`
2. Identify vulnerabilities with `no fix available`
3. View versions available in …
=> USWDS-Site - Dependencies: Use overrides to remove reliance on snyk ignore

_data/changelogs/component-file-input.yml, _includes/code/components/file-input.html
Remove `file-input-disabled` from component partial to resolve build error
Closes #2113
[File input →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-remove-file-input-disabled/components/file-input/)
The disabled variant `json` file was removed as part of https://github.com/uswds/uswds/pull/5063, causing build errors on site when it tries to find it.
Remove template capture from the component partial
1. On main, run `npm run build`
2. Confirm error
3. `git checkout cm-remove-file-input-disabled`
4. Run `npm run build`
5. Confirm error is extinguished
6. Vising [file input](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-remove-file-input-disabled/components/file-input/) …
=> Remove file-input-disabled from file-input partial

.snyk, _data/changelogs/docs-implementations.yml, _data/implementations.yml, package.json
Internal PR from https://github.com/uswds/uswds-site/pull/2152. Adds metrostar Comet implementation.
This PR also:
- Ignores code guidelines URL in HTMLProofer because of a false positive [f4166c8](https://github.com/uswds/uswds-site/pull/2167/commits/f4166c86fe41e076ace21c082d51b422a886bf7a).
- Updates snyk ignore (USWDS/Compile warnings) [bb873d2](https://github.com/uswds/uswds-site/pull/2167/commits/bb873d2ff7ff1e65fc897cde0fda7184de8b5428).
=> USWDS-Site - Implementations: Add comet from metrostar

package-lock.json
Minor dependency updates as a result of `npm audit fix`. Resolve `semver` Moderate vulnerability.
Closes #2171
[Site →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-dep-audit-7-11-23/)
Outdated dependencies may be causing vulnerabilities.
`npm audit` before fix:
```bash
semver  <=5.7.1 || 6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix` …
```
=> POAM - July '23: npm audit fix

_data/changelogs/about-research.yml, pages/about/research.md
Removed broken link from research page
Closes #2184
Preview link: [Research page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-500-error/about/research/)
This broken link is causing build errors on uswds-site: http://www.uxbooth.com/articles/an-analytics-first-approach-to-ux-part-1/
Removed the broken link per the recommendation from @jaclinec. 
- Review the content on the research page to make sure it is up-to-date and accurate. 
- Consider finding a suitable replacement link for the reference section
- Confirm that the link is still broken
- Confirm that this update passes tests
- Confirm the changelog is accurate and free from error
=> USWDS-Site: Remove broken reference link on research page

_components/header/header--basic-mega.html, _components/header/header--basic.html, _components/header/header--extended-mega.html, _components/header/header--extended.html, _components/header/header.html, _data/changelogs/component-header.yml, package-lock.json
**Added header variants table to guidance page.** This change also removes empty "**Using the header**" section.
Closes #1976 
Preview link:
[Header variants →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-header-variant-guidance/components/header/#header-variants)
[Header changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-header-variant-guidance/components/header/#latest-updates)
The Header guidance page was missing a variants table that can be found in other component guidance pages. There were also empty implementation sections due to each component containing variants in its frontmatter, which were not displayed in the sections.
Move the `variants` out of …
=> USWDS-Site - Header: Add variants table to guidance page

package-lock.json, package.json
Bump `stylelint` and `@18f/identity-stylelint-config` to resolve semver vulnerability.
_Note:_ This PR takes a similar approach to USWDS #[5373](https://github.com/uswds/uswds/pull/5373), however, Site did not need to update to `postcss` so it was left out for now
This is not a breaking change.
Closes Dependabot alert [#49](https://github.com/uswds/uswds-site/security/dependabot/49)
Dependabot Security Update #2165 
Preview link:
Site →
`Stylelint` has vulnerability in semver dependency. 
Updating this dependency alone causes conflicts with `@18f/identity-stylelint-config`
Bump `stylelint` and relevant dependencies that are needed in order to prevent errors.
- Bump `stylelint 14.13.0 → 15.10.1`
- Bump `@18f/identity-stylelint-config 1.0.0 → 2.0.0`
| Dependency name              | Previous …
=> USWDS-Site - Bump `stylelint` & `@18f/identity-stylelint-config`

css/custom-styles/_site-header.scss, css/settings/_uswds-theme-components.scss
Fixed the line break on the header logo by updating the value of `$theme-header-logo-text-width`  to 50% instead of 33%.
This review should require a low level of effort.
:warning: No changelog needed
Closes #2198
Preview link: [Home page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-update-logo-width/)
For window widths from approximately 1024px to 1225px, the header displays a vertical scrollbar on the right side of the component. 
This happens because the logo text breaks to two lines. Note that in the screenshot above, the "(USWDS)" abbreviation should be shown but is not visible because it got bumped to a second line. 
In USWDS PR https://github.com/uswds/uswds/pull/5008 (Release 3.4.1), we introduced a fix that caused the …
=> USWDS-Site: Update width of header logo

pages/documentation/getting-started-developers/phase-one.md
Fixes an outdated reference to `uswds` package in the installation instructions. After following the steps preceding the edited snippet, a developer should expect `package.json` to include `@uswds/uswds`, not `uswds`.
=> USWDS-Site - Install: Fix package name in package.json example

_data/changelogs/component-pagination.yml
Added changelog entries for https://github.com/uswds/uswds/pull/5358
> Updated the ellipsis color to meet color contrast requirements.
> Updated styles to respect the value added to $theme-pagination-background-color.
[Pagination changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5358/components/pagination/#changelog)
=> USWDS-Site: Add changelog entries for #5358

_data/changelogs/docs-getting-started-devs-phase-2.yml, pages/documentation/getting-started-developers/phase-two.md
Updated the guidance in [Phase 2: Compile](https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/) to add clarity by:
1. Re-organizing content to more clearly identify which instructions are for `uswds-compile` users and which are for users who compile Sass a different way
1. Updating the file names in the code demos to match what `uswds-compile` creates
1. Adding copy to clarify which files are project files and which are USWDS files
⚠️ The changelog date will need to be updated before merge.
Closes #2061
Preview link: [Phase 2: Compile](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-update-compile-instructions/documentation/getting-started/developers/phase-two-compile/)
There is an …
=> USWDS-Site: Add clarity to Phase 2: compile instructions

_includes/changelog-table.html
Added the `Content` tag to the changelog table. 
This review should require a low level of effort. 
Closes #2202
- [Banner](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-affectscontent-tag/components/banner/#changelog)
- [Identifier](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-affectscontent-tag/components/identifier/#changelog)
The content tag currently does not appear in the changelog tables. Here is an example on the [identifer page](https://designsystem.digital.gov/components/identifier/#latest-updates):
And on the banner page:
Including a check for `affectsContent` in the changelog table adds the "Content" tag. 
After:
Identifier
Banner
Confirm that the items …
=> USWDS-Site: Add content tag to changelog table

pages/design-principles/design-principles.md
Resolved html-proofer error related to a 404 link on the Design principles page. 
Closes https://github.com/uswds/uswds-site/issues/2236
Preview link: [Design principles page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-error/design-principles/)
html-proofer is flagging the following error for this link:
```
At ./_site/design-principles/index.html:2820:
External link https://www.performance.gov/tips-for-starting-your-customer-experience-journey/ failed (status code 404)
```
Updating the link to https://www.performance.gov/cx/blog/tips-for-starting-your-customer-experience-journey/ resolves the html-proofer error.
[Old entries in the wayback machine](https://web.archive.org/web/20230000000000*/https://www.performance …
=> USWDS-Site - html-proofer: Update broken performance.gov link

_data/changelogs/component-memorable-date.yml
Added changelog entry for https://github.com/uswds/uswds/pull/5372
> Updated memorable date styles to allow elements to wrap to multiple lines at narrow widths.
Preview link: [Memorable date changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5372/components/memorable-date/#changelog)
=> USWDS-Site: Add changelog entries for #5372

_components/icon-list/icon-list.md, _data/changelogs/docs-settings.yml
Added changelog entries for https://github.com/uswds/uswds/pull/5363
Related to https://github.com/uswds/uswds/pull/5363
> Updated icon list styles to allow `$theme-body-font-size` to accept `2xs` and `3xs` size tokens.
- [Settings changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5363/documentation/settings/#changelog)
- [Icon list - variants](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5363/components/icon-list/#component-variants-icon-list)
=> USWDS-Site - Changelog: Update docs and add changelog for Icon list add size tokens [USWDS#5363]

_data/changelogs/component-input-mask.yml
Added changelog entries for uswds/uswds#5378
Related to uswds/uswds#5378
> Fixed a bug that caused the input mask hover state to adopt disabled styling.
[Input mask changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5378/components/input-mask/#latest-updates)
=> USWDS-Site - Changelog: Add entry for Input mask fix hover state [USWDS#5378]

_data/changelogs/component-form.yml
Add change log item for https://github.com/uswds/uswds/pull/5397
[Form change log](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-hc-input-border-changelog/components/form/#latest-updates) →
=> USWDS-Site - Changelog: Add entry for remove high-contrast disabled border from %block-input-styles [USWDS#5397]

_data/changelogs/utilities-font-size.yml, _utilities/font-size-and-family.md
- Add changelog for font family and size page
- Create changelog entry for uswds/uswds#5388
Related to uswds/uswds#5388.
> Fixed a bug that caused `font-[family]-[size]` utility classes to not generate font-family rules.
[Changelog entry](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5388/utilities/font-size-and-family/#changelog)
=> USWDS-Site - Changelog: Add entry for generate font-[family]-[size] classes [USWDS#5388]

_data/changelogs/docs-settings.yml, _data/changelogs/tokens-color-state.yml, _data/settings/color.yml, _data/tokens/color.yml, css/settings/_uswds-theme-color.scss
- Created changelog entries for uswds/uswds#5402
- Updated settings page with new disabled color settings and values
- Updated tokens page to include new disabled state tokens and show updated token values
> **Warning**
> The tokens page will not show a preview of the new `disabled-lighter` or `disabled-darker` color tokens until release 3.5.1 is installed. Wanted to make a note that the page did show the new color previews locally when I ran `npm link` with the branch from [#5402](https://github.com/uswds/uswds/pull/5402). 
> Before:
> ![image](https://github.com/uswds/uswds-site/assets/93996430/3dd5c51e-ea9e-42ac-afc1-85a7c232b50d)
> After: 
> ![image](https://github.com/uswds/uswds-site/assets/93996430/314ea2a4-e516-4b95-bd91-31a595d0a9d9)
- [Settings - disabled …
=> USWDS-Site - Changelog: Add entry & Doc updates for disabled color changes [USWDS#5402]

_data/changelogs/component-in-page-navigation.yml
Added changelog entries for https://github.com/uswds/uswds/pull/5393
Related to https://github.com/uswds/uswds/pull/5393
> Excluded hidden headers from the in-page navigation link list. Any header with a style of display:none or visibility:hidden will be excluded from the list of links in the component.
[Changelog entry](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5393-2/components/in-page-navigation/#latest-updates)
=> USWDS-Site - Changelog: Add entry for in-page nav exclude hidden headers [USWDS#5393]

css/_uswds-theme-custom-styles.scss, css/settings/_variables.scss
Fixes visual regression of touchpoints survey caused by `inline` external links change in https://github.com/uswds/uswds-site/pull/1322
Closes #2186 
_Scroll to the bottom and view the touchpoints button at mobile breakpoints_
[Banner component page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-touchpoints-regression-fix/components/banner/)
All external links were changed to `inline` elements in https://github.com/uswds/uswds-site/pull/1322. This caused a visual regression in **local builds** only. The survey link on the live build appears to have been unaffected.
From @mejiaj:
> I'm guessing it doesn't happen on production because the way the CSS is bundled and minified for production.
>
> We should still try to fix if we're …
=> USWDS-Site - Touchpoints: Fix visual regression on local builds

_components/card/card.md, _data/changelogs/component-card.yml
Adds missing `header--exdent` class to card variants table.
Closes #2209 
[Card variants →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-card-header-exdent-guidance/components/card/#using-the-card-component-2:~:text=between%20card%20elements.-,Card%20variants,-Variant)
The card variants table was missing the `header--exdent` variant despite the design system offering the class and styles.
Add `usa-card__header--exdent` variant to table.
Exdent classes were added in https://github.com/uswds/uswds/pull/3437 _(May 2020)_
- PR mentions `header--exdent` in the **New Variants** section, but it was not listed in the **Variant Options** table
Guidance was updated in #913 and specifically commit …
=> USWDS-Site - Card: Add header exdent to variant table

_data/changelogs/component-tooltip.yml
Add changelog entry for tooltip opacity fix
https://github.com/uswds/uswds/pull/5475
[Tooltip changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5475/components/tooltip/#changelog)
=> USWDS-Site - Changelog: Set tooltip opacity to 0 [#5475]

_data/changelogs/component-header.yml, _data/changelogs/component-table.yml
Add changelog entry for Safari header bug fix.
https://github.com/uswds/uswds/pull/5443
[Header changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5443/components/header/#changelog)
=> USWDS-Site - Changelog: Safari header bug [#5443]

_data/changelogs/component-breadcrumb.yml
Add changelog entry for text wrap in the breadcrumb component.
https://github.com/uswds/uswds/pull/5497
[Breadcrumb changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5497/components/breadcrumb/#changelog)
=> USWDS-Site - Changelog: Breadcrumb text wrap [#5497]

.snyk
`npx snyk test` was throwing errors.
This PR updates snyk to ignore the following items: 
- SNYK-JS-UNSETVALUE-2400660
- SNYK-JS-ANSIREGEX-1583908
Ran the following in the command line:
```
npx snyk ignore --id="SNYK-JS-UNSETVALUE-2400660" --reason="No available upgrade or patch"
npx snyk ignore --id="SNYK-JS-ANSIREGEX-1583908" --reason="No available upgrade or patch"
```
=> USWDS-Site: Update snyk ignore (September)

_components/icon/icon.md, _data/changelogs/component-icon.yml, _includes/component.html, _includes/disclaimer.html
**Added social media icon disclaimer.** This disclaimer explains that social media icons are subject to separate terms and conditions, and that our inclusion of these icons does not constitute an endorsement of these services.
Closes #2285 
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/dw-social-media-disclaimer/components/icon/) → 
Our general counsel suggests that we add a disclaimer to our icon component page to explain that social media icons are subject to separate terms and conditions, and that our inclusion of these icons does not constitute an endorsement of these services.
Our icon component page now includes the following disclaimer, provided by counsel:
> Use of any social media icons placed on this page …
=> USWDS-Site - Icon: Add social media icon disclaimer

_includes/banner.html
Updated banner markup to reflect the latest changes as of `3.6.0`
Closes #2305 
[Site →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-update-banner-code-3.6.0/)
There are minor changes to the banner markup that the banner on our site does not reflect.
Replace markup with component example code from our site.
- HTML is formatted a bit better
- Removes defined icon sizes from the American flag
- Slight changes to alt text
1. Inspect banner for visual regressions.
2. Run manual and automated accessibility tests to ensure there are no regressions.
=> USWDS-Site - Banner: Update markup

.snyk, package-lock.json
Ignores two snyk vulnerabilities causing build and `npx snyk test` errors.
Closes #2321
[Update snyk ignore (September)](https://github.com/uswds/uswds-site/pull/2287)
Build and `npx snyk test` and test builds were failing. 
The failures are the same as last month's Snyk Update
- SNYK-JS-UNSETVALUE-2400660
- SNYK-JS-ANSIREGEX-1583908
Re-add the snyk ID's to the snyk ignore
1. Run `npx run test` and check for errors
2. Check to see if the automated tests on this branch pass.
=> USWDS-Site: Update snyk ignore (October)

_data/changelogs/component-identifier.yml
Add changelog entry for identifier screen reader copy edit.
https://github.com/uswds/uswds/pull/5491
[Identifier changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5491/components/identifier/#changelog)
=> USWDS-Site - Changelog: Identifier screen reader update [#5491]

_data/changelogs/component-card.yml, _data/changelogs/docs-settings.yml
Add changelog entry for `$theme-card-padding-y` fix.
https://github.com/uswds/uswds/pull/5571
- [Card changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5571/components/card/#changelog)
- [Settings changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5571/documentation/settings/#changelog)
=> USWDS-Site - Changelog: Add entry for $theme-card-padding-y fix [#5571]

_data/changelogs/component-site-alert.yml
Add changelog entry for removing site alert top margin.
https://github.com/uswds/uswds/pull/5550
[Site alert changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5550/components/site-alert/#changelog)
=> USWDS-Site - Changelog: Create entry removing site alert top margin [#5550]

_data/changelogs/component-icon.yml
Changelog entry for https://github.com/uswds/uswds/pull/5589
> **Added the X social media icon.** We also preserved the legacy Twitter icon to allow teams to make the decision on when to update their social media information.
https://github.com/uswds/uswds/pull/5589
[Preview Icon page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/dw-add-x-icon/components/icon/) →
=> USWDS-Site - Changelog: Create entry for X social media icon [#5589]

pages/documentation/getting-started-developers/phase-one.md
Updated installation instructions to use the `--save--exact` flag and added a note about pinning dependencies.
Closes #2231
[Phase 1: Install page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-pin-install/documentation/getting-started/developers/phase-one-install/#step-3-install-uswds)
In the [migration page](https://designsystem.digital.gov/documentation/migration/#2-install-the-uswds-30-package), we recommend installing USWDS with the `--save-exact` flag. However, in the [getting started for developers guide](https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/#step-3-install-uswds), we recommend using the `--save` flag. 
This inconsistency can cause confusion to users. Additionally, …
=> USWDS-Site: Add note about pinning dependencies

_includes/utilities/responsive-variants.html
Corrected `padding-y-2` example to display the proper output. The setting outputs `padding-top` and `padding-bottom` and not `padding-left/right`
As discovered in this [slack thread](https://gsa-tts.slack.com/archives/C050HRGN7/p1700063752861839?thread_ts=1700062601.785029&cid=C050HRGN7) 🔒 by @caleywoods. Thanks Caley!
[Responsive variants →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-responsive-example-fix/utilities/margin-and-padding/#responsive-variants-2)
Responsive variant currently displays incorrect values in it's output example.
Update to match actual output.
1. Visit any utility page with a responsive variants section
- [Margin and padding](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/p …
=> USWDS-Site - Responsive variants: Correct padding-y-2 example

_includes/component-package.html
Closes #2362. Fixes incorrect markup in component package section.
Before/After
**Preview links**
| Current | Feature branch |
|:--------|:--------|
| [Default] | [Preview] |
[Default]: https://designsystem.digital.gov/components/table/#table-package
[Preview]: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-bugfix-component-markup-fix/components/table/#table-package
=> USWDS-Site - Bugfix: Fix markup in dependency table

pages/design-principles/design-principles.md
Removed the link to the Federal Crowdsource Mobile Testing Program on the [design principles page](https://designsystem.digital.gov/design-principles/#government-resources-3) because the page is returning a 404. An alternative link on digital.gov (that matches the wayback machine from 2022) states that the program is no longer active.
- [Wayback machine for broken link](https://web.archive.org/web/20220211172854/https://digital.gov/services/mobile-application-testing-program/) (Feb 2022)
- Alternative [Federal Crowdsource Mobile Testing Program page](https://digital.gov/services/service_mobile-testing-program/)  on digital.gov
Preview link: [Design principles](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-mobile-testi …
=> USWDS-Site - HTML-Proofer: Fix error on design principles page

pages/documentation/guidance/performance/http2.md
Removed the Akamai  link from the [HTTP/2 performance page](https://designsystem.digital.gov/performance/http2/#how-to-upgrade-to-http2) because it now returns a `Moved Permanently (status code 301)` error. 
I could not find a equivalent page on Akamai with the content found in the [Wayback Machine](https://web.archive.org/web/20231101075143/https://http2.akamai.com/) (Nov 2023). 
Preview link: [HTTP/2 page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-akamai/performance/http2/#how-to-upgrade-to-http2)
- Confirm that removing the link makes sense
- Confirm the updated page content renders as expected
- Confirm html proofer check passes
=> USWDS-Site - HTML proofer: Remove Akamai HTTP/2 link

.snyk, _components/header/header.html
Fixed snyk and html-proofer build errors. Also added descriptive link text according to recommendations from @sarah-sch.
- [Header component page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-snyk-nov/components/header/)
1. `npx snyk test` was throwing errors.
2. `npm run proof` threw an error for a 404 link. 
1. Updated to ignore the following items: 
- SNYK-JS-UNSETVALUE-2400660
- SNYK-JS-ANSIREGEX-1583908
Ran the following in the command line:
```
npx snyk ignore --id="SNYK-JS-UNSETVALUE-2400660" --reason="No available upgrade or patch"
npx snyk ignore --id="SNYK-JS-ANSIREGEX-1583908" --reason="No available upgrade or patch"
```
2. Replaced the current [404 link](https://help.usertesting.com/hc/en-us/articles/115003372331-What …
=> USWDS- Site: Fix snyk and html-proofer errors

_data/changelogs/about-policies.yml, pages/about/website-policies-and-notices.md
Removed the open government link from the website policies page. 
Closes #2133
[Website policies page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-open-govt-link/about/website-policies-notices/#required-content-notice)
The GSA open government link on the [website policies page](https://designsystem.digital.gov/about/website-policies-notices/#required-content-notice) returned a 404 so in the doc updates for 3.5.0 we added "pending" copy while we waited to find a replacement link ([PR #2096](https://github.com/uswds/uswds-site/pull/2096/files#diff-a066b23cde022edc6967714a5bcfb4fb28c2aa3e56dc5fd0dedc08d4a761b905R179)). However, we have not been able to find a suitable replacement for this link. 
Per the guidance on …
=> USWDS-Site: Remove open government link

pages/design-principles/design-principles.md
Replaced the Performance.gov CX link and link description. 
The previous page ([Improving Customer Experience: Cross-Agency Priority Goal](https://www.performance.gov/CAP/cx/)) returns a 404. 
This page conveys a similar message to the original: [Delivering Excellent, Equitable, and Secure Federal Services and Customer Experience](https://www.performance.gov/pma/cx/)
More discussion about the decision in this [Slack thread](https://gsa-tts.slack.com/archives/C050HRGN7/p1702065728604979) (:lock:).
[Design principles page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-cap/design-principles/#government-resources-4)
- Confirm that replacing the link is appropriate and makes sense
- Confirm the updated page content …
=> USWDS-Site - HTML-Proofer: Fix Performance.gov CX link 

_data/changelogs/component-header.yml
**Improved the display of header navigation dropdown button for long links.** The expander icon will now be vertically centered.
uswds/uswds#5654
[Preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5654/components/header/)
=> USWDS-Site - Changelog:  Vertically center nav elements [#5654]

_data/monthly-calls.yml
Updated the November 2023 monthly call description so that it says "November 2023 script and more at Digital.gov" instead of "November 2023 event page at Digital.gov".
[Monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-nov-mc-script/about/monthly-calls/)
We needed to publish the [November 2023 monthly call description](https://designsystem.digital.gov/about/monthly-calls/) before the script was uploaded to the digital.gov counterpart. Because of this, we added a "missing_script" setting that updated the "script and more at Digital.gov" text to instead say "event page at Digital.gov". 
Now that the script has been added to the digital.gov page, this PR removes the "missing_script" data field. This should update the …
=> USWDS-Site - Monthly call: Add script text to November 2023 MC entry

_data/changelogs/component-footer.yml
Updated changelog entry for uswds/uswds#5289 to include a note about layout grid.
[Footer changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-footer-grid/components/footer/#latest-updates)
Users who import footer but not `layout-grid` may experience visual regressions if they've:
- Modified standard breakpoint utility classes in the markup of the footer
- Use `layout-grid` utilities elsewhere on the site
Update changelog to alert users of this change:
> **This update reduces the footer package size**. Thanks @danbrady! (#5289) <br><br> If you notice changes in your layout after making this update, your Sass might be missing the `usa-layout-grid` package. You can include it by adding `@forward usa-layout-grid` to …
=> USWDS-Site - Footer changelog: Update to include layout grid

css/_uswds-theme-custom-styles.scss
Resolves minor scss style issues by running prettier.
Closes #2449 
Preview link:
The latest site merge brought in a `lintSass` error due to minor sass style conflcits. 
Run prettier.
1. Checkout this branch.
2. Run `npm run lint`.
3. Confirm there are no issues.
4. Confirm file changes are minor.
5. Confirm no unintended visual regression on affected classes.
=> USWDS-Site: Run prettier

_data/implementations.yml, _next/04-00-looking-ahead.md, css/_uswds-theme-custom-styles.scss, package.json, pages/documentation/guidance/accessibility.md
Updated links to resolve HTML proofer errors.
- [Accessibility page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-jan24/documentation/accessibility/#government-usability-testing-resources)
- [Implementations page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-jan24/documentation/implementations/)
- [Next - looking ahead page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-jan24/next/looking-ahead/)
Received the following HTML proofer error:
```
* At ./_site/documentation/accessibility/index.html:2896: …
```
=> USWDS-Site - HTML-proofer: Fix broken links

.snyk
Updated snyk ignore files
`npx snyk test` is throwing the following error:
```
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1
introduced by @uswds/compile@1.1.0 > gulp@4.0.2 > gulp-cli@2.3.0 > yargs@7.1.2 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1 and 4 other path(s)
This issue was fixed in versions: 3.0.1, 4.1.1, 5.0.1, 6.0.1
✗ Missing Release of Resource after Effective Lifetime [Medium Severity][https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116] in inflight@1.0.6
introduced by @uswds/compile@1.1.0 > del@6.1.1 > rimraf@3.0.2 > glob@7.2.3 > inflight@1.0.6 and 1 other path(s)
No upgrade or patch available
✗ Prototype Pollution [High …
```
=> USWDS-Site: Fix snyk errors

_utilities/flex.md
Fix `aria-controls` for `code-flex-align-self` to restore the accordion functionality for this code section.
The `aria-controls` for the code segment demonstrating `flex-align-self` was missing the `self` which caused the collapse/expand functionality of the accordion component to not work. Accordion functionality was restored by fixing the `aria-controls` attribute to be `code-flex-align-self`.
1. Desired state: When viewing the code example for flex align self, clicking the +/- on the accordion component expands or collapses the code example within the accordion component.
2. Actual state: When viewing the code example for flex align self, clicking the +/- on the accordion component has no effect on whether or not the code example accordion component expands or collapses.
1. The …
=> USWDS-Site - Flex: Fix aria-controls to restore expand/collapse of the code example accordion for flex-align-self

_data/implementations.yml
Americana Stack is a Remix Stack for US Federal web sites on AWS. Includes US Web Design System, react-uswds, and pre-commit hooks for linting and type checking.
=> Add Americana Stack to implementations

_data/changelogs/component-date-picker.yml, _data/issues/date-picker.yml
Adds changelog entry for uswds/uswds#5701 and removes the known issue resolved by PR.
>  **Adds focus styles to calendar button in high contrast mode.** Now, the calendar icon changes to the `highlight` high contrast token.
> The focus indicator is not visible around the calendar icon in high contrast mode. More information on GitHub: [uswds#5535](https://github.com/uswds/uswds/pull/5535)
[Date picker changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5701/components/date-picker/#latest-updates)
=> USWDS-Site - Changelog: Add entry for high contrast date picker fix [#5701]

_data/changelogs/component-footer.yml
Adds changelog entry for uswds/uswds#5675
>  **Resolved style specificity issues between `usa-footer` and `usa-layout-grid`.** This resolves visual regressions potentially caused by removing layout grid dependency.
[Footer changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5675/components/footer/#latest-updates)
=> USWDS-Site - Changelog: Add entry for footer grid fix

_data/changelogs/component-button-group.yml
Changelog entry for uswds/uswds#5657.
uswds/uswds#5657.
[Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-button-group/components/button-group/#latest-updates)
=> USWDS-Site - Changelog: Add entry for button group wrapping lines

_components/text-input/guidance/usability.md, _data/changelogs/component-text-input.yml, _data/changelogs/component-validation.yml
Added changelog entries for Validation & Text Input component.
Related to uswds/uswds#5233 & #2477.
Preview link:
- [Validation](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-validation-text-input/components/validation/)
- [Text input](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-changelog-validation-text-input/components/text-input/)
=> USWDS-Site - Changelog: Add entry for validation & text input

_data/changelogs/about-research.yml, pages/about/research/overview.md
Replaced the "For federal government employees (coming soon)" text on the [research page](https://designsystem.digital.gov/about/research/) with a link to the newly released [fed recruitment page](https://designsystem.digital.gov/about/research/recruitment/general-fed/). 
Closes #2528 
[Research page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-link-fed-research/about/research/#how-to-participate-in-research)
The [recruitment for feds page](https://designsystem.digital.gov/about/research/recruitment/general-fed/) needs to be linked from the [main research page](https://designsystem.digital.gov/about/research/) where it says 'How to participate in research > For federal government employees"
1. Confirm that the updated text …
=> USWDS-Site - Research page: Add link to fed recruitment page

_components/typography/accessibility.md, _components/typography/typography.md, _data/accessibility-tests/typography.yml, _data/changelogs/component-typography-accessibility.yml, _data/changelogs/component-typography.yml, _includes/accessibility-tests/checklist-feedback.html, _includes/accessibility-tests/compliance-tag.html, _includes/accessibility-tests/index.html, _includes/component.html, _layouts/styleguide.html
- Added typography accessibility tests page.
- Moved compliance-tag.html reference to styleguide.html
- This allowed the compliance tag to be added to pages with the styleguide layout. 
- Note: This is the same change added to #2538
> [!Important]
> We need to confirm the changelog dates before merge.
- [Creating accessibility checklists process doc](https://docs.google.com/document/d/14WTCsdzgwpoz_Miztd66RmEGfwwSEUFCVN1DkSQITTE/edit) (Google docs 🔒)
- [Accessibility checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit#gid=97481116) (Google sheets 🔒)
Closes #2533 
- [Typography - accessibility test page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-typography-checklist/co …
=> USWDS-Site: Add typography accessibility tests page

.snyk, package-lock.json, package.json
**Snyk updates**
Snyk ignored three gulp related vulns.
```bash
❌ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1 
❌ Missing Release of Resource after Effective Lifetime [Medium Severity][https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116] in inflight@1.0.6 
❌ Prototype Pollution [High Severity][https://security.snyk.io/vuln/SNYK-JS-UNSETVALUE-2400660] in unset-value@1.0.0
```
The second one `SNYK-JS-INFLIGHT` seems new.
**Dependency updates**
| Dependency | Old      | New      |
| ---------- | -------- | -------- |
| axe-core   | 4.8.3    | 4.8.4    |
| express    | 4.18.2   | 4.19.1   |
| postcss    | 8.4.32   | 8.4.38   |
| sass       | 1.69.5   | 1.72.0 …
=> USWDS-Site - Dependencies: Security updates

_data/changelogs/docs-accessibility.yml, pages/documentation/guidance/accessibility.md
Updated the content on the accessibility page to match the content in the [Accessibility page draft](https://docs.google.com/document/d/1n4DcDUbL5jVDVT3HY7TE6I4LLrY0CmKUhUDKCo873E8/edit?usp=sharing) (Google docs 🔒) .
> [!Note]
> Because this is a time sensitive update, we are taking an iterative approach to developing this content. In this initial phase, we are updating the text content only. Later, in issue #2568 we will work on enhancing the visual organization.
Closes #2554 
[Accessibility page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-a11y-page/documentation/accessibility/)
1. Confirm all content matches the content in [Accessibility page draft](https://docs.google.com/document/d/1n4DcDUbL5jVDVT3HY7TE6I4LLrY0CmKUhUDKCo873 …
=> USWDS-Site - Accessibility page: Replace content

_config.yml
Updated the `uswds_version` in `config.yml` to 3.8.0
> [!Note]
> This task is already documented in 2.3 of the [Release process doc](https://docs.google.com/document/d/1Ux0TJf_wi3Sfikg_lZL0yXQhaY_stTr8-B_eAUY9B1U/edit#heading=h.lpffzr7li3xp) (Google Docs :lock:). I also added a confirmation task in 3.15 so that this is less likely to be missed in the future.
Closes #2570 
[Home page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-update-version-3.8.0/)
1. Confirm that `config.yml` shows the current USWDS version for `uswds_version`. 
1. Confirm the current USWDS version is shown in the download button in the page header
=> USWDS-Site: Update uswds_version to 3.8.0

_data/changelogs/docs-accessibility.yml, _data/changelogs/docs-sample-contract-language.yml, pages/documentation/sample-contract-language.md, pages/documentation/showcase.md
Updated treasury.gov and digital.gov links. Now, links no longer redirect or cause `htmlproofer` errors.
> [!Important]
> We should confirm the changelog date in `_data/changelogs/docs-sample-contract-language.yml` before merge. 
Closes #2603 
[Showcase page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-update-links-april-2024/documentation/showcase/)
>[!NOTE]
>Not a user facing change due to redirect already bringing users here. Opted to not create a changelog for showcase.
[Sample contract language page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-update-links-april-2024/documentation/sample-contract-language/)
HTMLProofer flagged two new issues caused by the …
=> USWDS-Site - HTMLProofer: Update links to target redirects

_config.yml
Updated the hash url in `_config.yml` to point to the 3.8.0 release hash. 
Closes #2614 
[Download page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-hash-url/download/)
Our site data points to the 3.6.1 hash.txt file in [_config.yml](https://github.com/uswds/uswds-site/blob/main/_config.yml#L47). This reference should point to 3.8.0.
This PR updated the url to reflect the correct USWDS release. I also added a task to the [release process doc](https://docs.google.com/document/d/1Ux0TJf_wi3Sfikg_lZL0yXQhaY_stTr8-B_eAUY9B1U/edit) (Google docs :lock:) so that this isn't neglected in the future.
> [!Note]
> It would be great if we could reuse `uswds_version` in the url definition for the hash reference. However,  I could not find a …
=> USWDS-Site: Update hash url to 3.8.0

_utilities/display.md, pages/design-tokens/z-index.md
Fixes the typo for .z-100. Previously was `400`, changed text to `100`.
=> USWDS-Site - Display/:Fixes the typo for .z-100

_components/tag/accessibility-tests.md, _components/tag/tag.md, _data/accessibility-tests/tag.yml, _data/changelogs/component-tag-accessibility.yml, _data/changelogs/component-tag.yml
Added accessibility tests page for the tag component.
> [!Note]
> The tag accessibility tests page does not include the tests for interactive tags that are included in the [spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit#gid=97481116) (Google sheets 🔒).  This is because there is some ambiguity about the role of interactive tags in the design system and because we do not currently offer examples of interactive tags. Please confirm that the expected tests are included on this page.
> [!Important]
> We should update changelog dates before merge.
Closes #2526
- [Tag accessibility tests page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-a11y-tests-tag/components/tag/accessibility-t …
=> USWDS-Site: Add tag accessibility tests page

_data/changelogs/component-validation.yml
Added changelog entry for uswds/uswds#5835
> **Fixed a bug which caused non-interactive checklist items to receive focus on tab.** Now, only the interactive input will receive focus.
> 
uswds/uswds#5835
[Preview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5835/components/validation/#latest-updates)
=> USWDS-Site - Changelog: Remove tabindex from validation checklist items [#5835]

_data/changelogs/component-input-mask.yml
Created changelog for uswds/uswds#5518
> **Fixed a bug that caused input mask to break when it is not a direct child of a form.** Nested input masks will now initialize and work properly.
uswds/uswds#5518
[Input mask changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5518/components/input-mask/#latest-updates)
=> USWDS-Site - Changelog: Nested input masks [#5518]

_data/changelogs/component-footer.yml, _data/packages.yml
Added changelog item and restored `usa-layout-grid` dependency to `_data/packages.yml` footer package.
uswds/uswds#5930
[Footer component page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5930/components/footer/#package)
[Component packages page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-changelog-5930/components/packages/)
1. Confirm `usa-layout-grid` package is listed as a dependency on the component package page packages table for `usa-footer`.
2. Confirm `usa-layout-grid` package is listed as a dependency on the footer component page.
3. Approve changelog data and description.
=> USWDS-Site - Changelog:  Restore footer’s layout-grid dependency [#5930]

.snyk
Updated snyk ignore files
`npx snyk test` is throwing the following error:
```
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1
introduced by @uswds/compile@1.1.0 > gulp@4.0.2 > gulp-cli@2.3.0 > yargs@7.1.2 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1 and 4 other path(s)
This issue was fixed in versions: 3.0.1, 4.1.1, 5.0.1, 6.0.1
✗ Uncontrolled resource consumption [High Severity][https://security.snyk.io/vuln/SNYK-JS-BRACES-6838727] in braces@2.3.2
introduced by @uswds/compile@1.1.0 > gulp@4.0.2 > glob-watcher@5.0.5 > chokidar@2.1.8 > braces@2.3.2 and 6 other path(s)
This issue was fixed in versions: 3.0.3
✗ Missing Release of Resource after …
```
=> USWDS-Site: Fix snyk errors 

_data/changelogs/utilities.yml, _utilities/overview.md, pages/design-principles/design-principles.md
Utils example is missing a comma that could lead to subsequent settings being ignored.
On Utilities page - [Source →](https://designsystem.digital.gov/utilities/) 
Originally reported in [slack →](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1719430471449389). Thanks @bmartinez287!
Preview link: [Utilities →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-utils-example-fix/utilities/#:~:text=background%2Dcolor%22%2C-,%22color%22%2C,-%22display%22%2C) 
Added a comma to color utility in code example.
=> USWDS-Site - Bug: Add missing comma to utils example

.snyk
**Updated snyk ignore files**
`npx snyk` test is throwing the following error:
```
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1
introduced by @uswds/compile@1.1.0 > gulp@4.0.2 > gulp-cli@2.3.0 > yargs@7.1.2 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1 and 4 other path(s)
This issue was fixed in versions: 3.0.1, 4.1.1, 5.0.1, 6.0.1
✗ Uncontrolled resource consumption [High Severity][https://security.snyk.io/vuln/SNYK-JS-BRACES-6838727] in braces@2.3.2
introduced by @uswds/compile@1.1.0 > gulp@4.0.2 > glob-watcher@5.0.5 > chokidar@2.1.8 > braces@2.3.2 and 6 other path(s)
This issue was fixed in versions: 3.0.3
✗ Missing Release of Resource …
```
=> USWDS-Site: Updates Snyk Alerts

pages/design-tokens/color/overview.md
Replaced broken w3 COGA Gap Analysis link.
**Note:** No changelog was created since this change restores expected functionality. 
Closes #2753
[Color token overview →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-w3-gap-analysis-link/design-tokens/color/overview/#further-reading-2)
HTML-Proofer caught a newly broken link to w3c github pages.
Replace the link with the relevant w3.org link
1. Visit [color token landing page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-w3-gap-analysis-link/design-tokens/color/overview/#further-reading-2)
2. Confirm that the W3C: Gap analysis link works as expected. 
3. Compare it's content to the [Wayback …
=> USWDS-Site - HTML-Proofer: Replace broken w3 COGA Gap Analysis link

pages/design-principles/design-principles.md, pages/documentation/guidance/accessibility.md
Replaced outdated inclusive design principle link on the design principles page.
Closes #2770 
[Design Principals page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-fix-inclusive-design-link/design-principles/)
On the Design Principles page, a link in the Practical Actions section formerly pointing to "Inclusive Design Principles" is broken and now leads to spam.
Replace with updated `.info` link
> https://inclusivedesignprinciples.info/
Inclusive Design link now appropriately takes users to the right page.
1. Visit the [design principles](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-fix-inclusive-design-link/design-principles/) page
2. Click each of the "Inclusive …
=> USWDS-Site - Link: Replace broken Inclusive Design link

.circleci/config.yml, Gemfile.lock, _config.yml, package-lock.json, package.json
Updated `uswds_version` and the package hash url in `config.yml` to point to 3.8.2.
>[!important]
> We should update the uswds version to 3.8.2 in the package.json before merge.
N/A
[Home page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/release-3.8.2/)
- Confirm that the "Download" button in the header shows the correct version number
- On the download page, confirm:
- The version number is correct
- The listed SHA-256 hash matches the release hash
- Confirm that the package.json uses uswds version 3.8.2
=> USWDS-Site: Documentation updates for 3.8.2

.snyk, package.json
Updated the html proofer script to ignore blog posts that are 3 years old or older
**note:** This PR also updates Snyk ignore to avoid CI failure
Closes #2788
Closes #2790
HTML Proofer began flagging a broken link from a 2021 blog post.
In #2618 we added an alert to outdated blog posts. We deemed 3+ years to be outdated and mention that these pages may have outdated information as well as broken links.
Since the broken link that was flagged in #2788 does not have a suitable replacement, I've added the blog posts from 2021 and later to our HTML Proofer ignore script.
- Blog posts from 2021 and before are no longer scanned for broken links.
- Snyk ignore updated for another this month
1. Confirm CircleCI checks pass
2. Run `npm run proof` script and confirm it runs without errors
3. Confirm …
=> USWDS-Site - HTMLProofer: Update script to ignore 2019-2021 blog posts

pages/about/community.md
chat.18f.gov is currently in the process of being redirected to https://18f.gsa.gov/chat/, but in the meantime we will link directly to the Google Form. See related [Slack thread](https://gsa-tts.slack.com/archives/C04MSAWM2GM/p1724688256321579) (🔒)
[Preview link
](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/abj-slack-googleform-links/)
1. Navigate to the Community page
2. In the `Join the community` section, ensure both links point to https://docs.google.com/forms/d/1vcsvQ64qt5mYNyVajcwtYDRMqEOyPzsXZBGM5c4_BD8/viewform?edit_requested=true
=> USWDS-Site - Bug: Update chat.18f.gov links to go directly to Google Form

pages/documentation/showcase.md
Adding pbgc.gov to the Showcase page.
Closes #2766 
[Preview link. ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/brunerae-pbgc-showcase/documentation/showcase/)
1. Navigate to Showcase
2. Ensure that Pension Benefit Guaranty Corporation is listed
3. Click on link and ensure you're taken to https://www.pbgc.gov/
=> USWDS-Site - Showcase: Adding pgbd.gov to Showcase

_data/changelogs/component-identifier.yml
Add a changelog for PR uswds/uswds#5892
>[!important]
Related to uswds/uswds#5892
[Identifier changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5892/components/identifier/#latest-updates)
=> USWDS-Site: Add changelog for Spanish identifier USA.gov link update[#5892] 

_data/changelogs/component-memorable-date.yml
Changelog for uswds/uswds#6028
uswds/uswds#6028
[Form component changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cb-changelog-6028/components/memorable-date/)
=> Changelog: Memorable Date remove numeric months [#6028]

_data/changelogs/component-pagination.yml
**This PR provides a changelog entry for the updates made to the pagination component.** The text-decoration styles has been removed so that the pagination page numbers show up as links.
[USWDS - Pagination: Updated text-decoration value to better show pagination links #5970](https://github.com/uswds/uswds/pull/5970)
Preview link:
[Pagination - Latest Updates](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/rc-changelog-pagination-5970/components/pagination/)
=> USWDS-Site: Add changelog for text-decoration style fix for pagination component [#5970]

_components/sidenav/accessibility-tests.md, _components/sidenav/sidenav.md, _data/accessibility-tests/side-navigation.yml, _data/changelogs/component-side-navigation-accessibility.yml, _data/changelogs/component-side-navigation.yml
Added accessibility test page for side navigation component
Closes #2857 
Preview link: [Side Navigation Component Page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/rc-side-nav-checklist/components/side-navigation/)
3. Confirm that the main component page links to the accessibility tests page from the accessibility guidance section.
4. Confirm that the main component page shows the accessibility tests summary.
5. Check that accessibility tests page provides the correct counts for each test …
=> USWDS-Site: Added side navigation accessibility test page

_components/in-page-navigation/accessibility-tests.md, _components/in-page-navigation/in-page-navigation.md, _data/accessibility-tests/in-page-navigation.yml, _data/changelogs/component-in-page-navigation-accessibility.yml, _data/changelogs/component-in-page-navigation.yml, _includes/accessibility-tests/wcag-details.html
Added accessibility test page for in page navigation component
Closes #2856
Preview link: [In-page Navigation Component Page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/rc-in-page-nav-checklist/components/in-page-navigation/)
3. Confirm that the main component page links to the accessibility tests page from the accessibility guidance section.
4. Confirm that the main component page shows the accessibility tests summary.
5. Check that accessibility tests page provides the correct counts for …
=> USWDS-Site: Added in page navigation accessibility test page

_data/changelogs/about-monthly-calls.yml, _data/monthly-calls.yml
Adding August Monthly Call content to Monthly Calls page 
> [!Important]
> The changelog date will need to be updated before merge.
Closes #2846 
Related to #[6025 ](https://github.com/uswds/uswds/issues/6025)
[Monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-augMCvideo_MCspg/about/monthly-calls/)
Needed to get Monthly Calls page up to date with August video. 
August Monthly Call summary has been done. We just received video and it needs to be added to page. 
Need someone to look and make sure link to video works.
=> Add August MC video to Monthly Calls page

_data/changelogs/about-monthly-calls.yml, _data/monthly-calls.yml
Adding September and October Monthly Call content to Monthly Calls page 
> [!Important]
> The changelog date will need to be updated before merge.
Closes #2849 and #2916
[[Monthly calls page]](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-septMC-MCspage/about/monthly-calls/)
Needed to get Monthly Calls page up to date with September and October call info. 
September Monthly Call summary was approved and is ready to be added to the page. Video will not be going up until later in the month. Will need a new ticket or branch off this when it's ready.
Need someone to look and make sure links work and content is clean and clear.
=> Add September and October Monthly Call to MCs page

_data/changelogs/component-step-indicator.yml
Add a changelog for PR uswds/uswds#6146
>[!important]
Related to uswds/uswds#6146
[Step indicator changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-6146/components/step-indicator/#latest-updates)
=> USWDS-Site: Add changelog for step indicator aria-label removal [#6146]

_data/changelogs/component-time-picker.yml
Add a changelog for PR uswds/uswds#6147
>[!important]
Related to uswds/uswds#6147
[Time picker changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-6147/components/time-picker/#latest-updates)
=> USWDS-Site: Add changelog for time picker hint text [#6147]

_components/pagination/guidance/implementation.md
Replaced Nunjucks reference with Twig
Closes #2809 
[Pagination page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-nunjucks-ref/components/pagination/)
Nunjucks is mentioned in pagination guidance and we no longer use it. We should replace with more general guidance or remove it completely.
Replaced "Nunjucks" references with "Twig" and added a link to the related source code. 
- Confirm the copy update is appropriate and accurate
- Confirm the new link points to the correct location
=> USWDS-site: Replace nunjucks reference

_data/issues/memorable-date.yml
Fixed the JSON for the memorable date known issues. This restores a date that appears to have been accidentally removed in [this commit](https://github.com/uswds/uswds-site/commit/3b936c352bdc468d7f6166d23f097c90e0e66422#diff-90736ba5f46722bbc7703af5d00cb5ca1553bc7223bf292892be20f07e909a06L13). 
N/A
The [known issues section on the memorable date page](https://designsystem.digital.gov/components/memorable-date/#known-issues) is broken.
Fix the missing content in the JSON. 
[Memorable date known issues](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-fix-memorable-date-known-issue/components/memorable-date/#known-issues-2)
Confirm the memorable date known issue section displays as expected.
=> USWDS-Site: Fix known issues on memorable date page

_data/monthly-calls.yml
Added link to October monthly call video and Q&A discussion link to[ monthly calls page](https://designsystem.digital.gov/about/monthly-calls/).
Closes [#6214](https://github.com/uswds/uswds/issues/6214)
[Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-MCspg-Octupdates/about/monthly-calls/)
Had to publish summary before video and Q&A were ready. Now they are. Updating the page.
Check and make sure links work and go to correct location.
Check for any typos or other text issues
=> Monthly calls page: Add October video and Q&A link

.snyk
**Updated snyk ignore files**
`npx snyk` test is throwing the following error:
```
✗ Missing Release of Resource after Effective Lifetime [Medium Severity][https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116] in inflight@1.0.6
introduced by @uswds/compile@1.2.0 > del@6.1.1 > rimraf@3.0.2 > glob@7.2.3 > inflight@1.0.6
No upgrade or patch available
```
Updated snyk ignore. Ran the following in the command line:
```
npx snyk ignore --id="SNYK-JS-INFLIGHT-6095116" --reason="No available upgrade or patch"
```
To test, run `npx snyk` test and check for errors.
[Ignoring Snyk Alerts](https://docs.google.com/document/d/1RX6uYky-P37jysuBy6LEBhuMCQlMAvHU0mRJUow345o/edit#heading=h.fa3sv1ray42g)
=> USWDS-Site: Updates Snyk Alert

_data/changelogs/about-monthly-calls.yml, _data/monthly-calls.yml
Adding November Monthly Call content to Monthly Calls page 
> [!Important]
> The changelog date will need to be updated before merge.
Closes #6215
[Monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-novMC-MCspage/about/monthly-calls/)
Needed to get Monthly calls page up to date with November call info. 
November Monthly call summary was approved and is ready to be added to the page. Video will not be going up until later in the month. Will need a new ticket or branch off this when it's ready.
Need someone to look and make sure links work and content is clean and clear.
=> Add November summary to Monthly calls page

_data/implementations.yml
Thanks @caseywatts for originally submitting this. Created this PR to verify commits via cherry picking and build site preview on cloud.gov pages.
From #3013:
>The Salesforce Lightning implementation of USWDS was archived in January 2024 this year:
https://github.com/GSA/uswds-sf-lightning-community
>
>This pull request marks that implementation as "archived" on the Implementations page.
[Implementations page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-test-commit-signature/documentation/implementations/)
=> USWDS-Site - Implementations: Salesforce Lightning is Archived  

_data/changelogs/docs-showcase.yml, pages/documentation/showcase.md
Removed the 404 link to VA Caseflow from the showcase page. 
N/A
[Showcase page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-dec-2/documentation/showcase/)
HTML-proofer flagged the following failure:
```
* At ./_site/documentation/showcase/index.html:2820:
External link https://github.com/department-of-veterans-affairs/caseflow failed (status code 404)
```
Removed the VA Caseflow link from the showcase page because no suitable replacement could be found. 
> [!note]
> The [link in the wayback machine](https://web.archive.org/web/20241214215433/https://github.com/department-of-veterans-affairs/caseflow) shows the repo seemed to be in active …
=> USWDS-Site: HTML-proofer fixes

_together/04-get-involved.md, pages/patterns/complex-form/establish-trust.md
Updated the link to CDC's "Communicating With and About People with Disabilities" page.
Here is the page content for the affected urls:
[Before](https://web.archive.org/web/20241217214129/https://www.cdc.gov/ncbddd/disabilityandhealth/materials/factsheets/fs-communicating-with-people.html) | [After](https://www.cdc.gov/disability-and-health/articles-documents/communicating-with-and-about-people-with-disabilities.html)
N/A
- [Together - Get involved](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-dec-3/together/get-involved/)
- [Establish trust pattern](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-dec-3/patterns/complete-a-complex-form/establish-t …
=> USWDS-Site - HTML-proofer: Fix broken CDC link

package-lock.json, package.json
Installed USWDS Compile `1.2.1`
[Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-install-compile-1.2.1/)
- Site now uses the latest version of compile
- Sass deprecation warnings are limited to only site custom 
1. Run `npm install` without error
2. Run `npx gulp buildSass` and confirm deprecation warnings are limited to site custom sass (check file path)
3. No regressions on site preview
| Dependency name              | Previous version | New version |
| ---------------------------- | :--------------: | :---------: |
| @uswds/compile |     1.2.0      |   1.2.1   |
=> USWDS-Site: Install Compile 1.2.1

pages/about/contribute.md
Updated the link to the "Good first issue" items in GitHub on the contribute page.
N/A
[Contribute page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-html-proofer-jan/about/contribute/)
HTML-proofer is flagging the following broken links:
```
* At ./_site/about/contribute/index.html:2664:
External link https://github.com/uswds/uswds/issues?q=is%3Aissue+label%3A%22Good+First+Issue%22 failed (status code 404)
* At ./_site/about/contribute/index.html:2682:
External link https://github.com/uswds/uswds/issues?q=is%3Aissue+label%3A%22Good+First+Issue%22 failed (status code 404)
HTML-Proofer found 2 failures!
```
- Confirm the updated url is a suitable replacement
- …
=> USWDS-Site - HTML-proofer: Update broken "good first issue" links

_components/site-alert/accessibility-tests.md, _components/site-alert/site-alert.md, _data/accessibility-tests/site-alert.yml, _data/changelogs/component-site-alert-accessibility.yml, _data/changelogs/component-site-alert.yml
Added accessibility test page for site alert component.
> [!Important]
> We need to update changelog dates before merge
Closes #2909
- [Site alert page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-site-alert-checklist/components/site-alert/)
- [Site alert accessibility page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-site-alert-checklist/components/site-alert/accessibility-tests/)
3. Confirm that the main component page links …
=> USWDS-Site: Site alert accessibility checklist

_components/alert/accessibility-tests.md, _components/alert/alert.md, _data/accessibility-tests/alert.yml, _data/changelogs/component-alert-accessibility.yml, _data/changelogs/component-alert.yml
Added accessibility test page for alert component.
> [!Important]
> We need to update changelog dates before merge
Closes #2906
- [Alert component page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-alert-checklist/components/alert/)
- [Alert accessibility page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-alert-checklist/components/alert/accessibility-tests/)
3. Confirm that the main component page links to the accessibility …
=> USWDS-Site: Alert accessibility checklist

_data/changelogs/component-date-picker.yml
Add a changelog for PR uswds/uswds#5679
>[!important]
[Date picker changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-5679/components/date-picker/#latest-updates)
=> USWDS-Site: Add changelog for date picker translations [#5679]

_components/card/accessibility-tests.md, _components/card/card.md, _data/accessibility-tests/card.yml, _data/changelogs/component-card-accessibility.yml, _data/changelogs/component-card.yml
Added accessibility test page for card component
> [!Important]
> We need to update changelog dates before merge
Closes #2911 
[Card Component Page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/rc-card-accessibility-checklist/components/card/)
[Card Accessibility Tests Page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/rc-card-accessibility-checklist/components/card/accessibility-tests/)
3. Confirm that the main component page links to …
=> USWDS-Site: Card Accessibility Checklist

_components/link/guidance/usability-should.md
The example `docx` link in the documentation was broken. This PR fixes that by replacing it with a working link.
Closes #3131
[Preview link 👀 ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/mh/fix-broken-link-to-508/components/link/)
=> USWDS-Site [Link]: fix broken link to docx in link example

pages/documentation/showcase.md
https://dsld.od.nih.gov/ is currently displaying a 404. However, Dietary Supplement Label Database (DSLD)
website states the following:
```
Please note: DSLD is temporarily unavailable. Please check back in a day or two.
```
We will circle back and re-add once the site is back online.
=> Remove broken link to https://dsld.od.nih.gov/

Gemfile.lock, _components/validation/validation.md, _data/changelogs/component-validation.yml, package-lock.json, package.json
Fixes https://github.com/uswds/uswds-site/issues/3147
[Preview url](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/js-fix-3147/components/validation/)
**NOTE:** this uses similar styling to other components that have notes about the specific component usage. See examples for the [banner](https://designsystem.digital.gov/components/banner/) and [data visualizations](https://designsystem.digital.gov/components/data-visualizations/) components while keeping the [`Known issues`](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/js-fix-3147/components/validation/#known-issues) section for folks using 3.12.0 and below.
=> Update validation component to denote deprecation past v3.12.0
